@startuml
sprite $10green [41x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
0000000000000BBBBBAAAAAAAAAAAAABBBB0000000000000
0000000000000BBBCCCBBBBBBBBBBCCCBBB0000000000000
0000000000BBBBACEEDDDDDDDDDDDDEDBABBBB0000000000
0000000000BBCDCCDEDDDDDDDDDDDDDDCCDCBB0000000000
00000000BBABDEEDDDDDDDDDDDDDDDDDDDEDBAAA00000000
00000000BBCDDEDDDDDDDDDDDDDDDDDDDDDDDBAA00000000
000000BBBBCEDDDDDDDDDDDDDDDDDDDDDDDDDCBAAA000000
000000BBBDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAA000000
000000AABDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBB0000
0000AAAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDBBB0000
0000AAABCDDDDDDDDEEEEDDDDDDDEEEEEDDDDDDEDBAA0000
0000AAACDDDDDDDDEEFFEDDDDDDEEFFFEEDDDDDDCBCBB000
0000AAACDDDDDDEEFFundeA7nedFEEDDDDEFFundeA7nedundeA7nedundeA7nedFFEEDDDDDDCBB000
000AABBCDDDDDEFFundeA7nedundeA7nedundeA7nedFEEDDDEFundeA7nedundeA7nedundeA7nedFundeA7nedundeA7nedundeA7nedFEDDDDDEDBA000
000AACDDDDDDEEFundeA7nedundeA7nedundeA7nedundeA7nedFEEDDEFFundeA7nedFEEEundeA7nedundeA7nedundeA7nedEDDDDDDCAA000
000AACDDDDDDEEFFFundeA7nedundeA7nedFEEDDEFundeA7nedundeA7nedFEDEFundeA7nedundeA7nedFDDDDDDCAA000
000AACDDDDDDDEEEEFundeA7nedFEEDDEFundeA7nedundeA7nedFDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEundeA7nedundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEundeA7nedundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEundeA7nedundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEundeA7nedundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEundeA7nedundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEFundeA7nedundeA7nedFEDEFundeA7nedundeA7nedFDDDDDDCAA000
000AACDDDDDDDDDDEFundeA7nedFEEDDEFundeA7nedundeA7nedFEEEFundeA7nedundeA7nedEDDDDDDCAA000
000AACEDDDDDDDDDEFundeA7nedFEEDDEEFundeA7nedundeA7nedFFFundeA7nedundeA7nedFEDDDDDDCAA000
000ABDEDDDDDDDDDEFundeA7nedFEEDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDCAA000
000BBCCDDDDDDDDDEEFEEDDDDDEEFFFFFEEDDDDDDEDBA000
000BB9BCDDDDDDDDDEEEDDDDDDDDEEEEEDDDDDDDEEDBB000
0000AABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBB000
0000AABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCAAA0000
0000AAABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAAAA0000
000000AAACDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAA000000
000000AAAABDDDDDDDDDDDDDDDDDDDDDDDDDDEECBB000000
00000000AAACDDDDDDDDDDDDDDDDDDDDDDDDEDDCBB000000
00000000AA8ACDDDDDDDDDDDDDDDDDDDDDDEEDBABB000000
0000000000AABCDEDDDDDDDDDDDDDDDDDDCCDCBB00000000
0000000000AABBDEDDDDDDDDDDDDDDDDDCBABBBB00000000
000000000000BBBCBCEEEDDDDDDEEECBBBAA000000000000
000000000000000BBCEEEEDDDDDEEECBB000000000000000
}

!define MSIMG_10GREEN_G <img:../sprites/GeneralSymbols/10green_gray.png>
!define MSIMG_10GREEN_C <img:../sprites/GeneralSymbols/10green.png>
@enduml