@startuml
sprite $5green [43x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000BBBBBAAAAAAAABBBBB000000000000000
000000000000000BBBCCCCBBBBCCCCBBB000000000000000
000000000000AAAAACEEDDDDDDDDEECAAAAA000000000000
000000000000AABCCCDEDDDDDDDDEDCCCBAA000000000000
00000000BBBBBBDDDDDDDDDDDDDDDDDDDDBBBBBB00000000
00000000BBCDDCDDDDDDDDDDDDDDDDDDDDCDDCBB00000000
000000BBBBDEEDDDDDDDDDDDDDDDDDDDDDDEEDBBBB000000
000000BBBDEDDDDDDDDDDDDDDDDDDDDDDDDDDEDBBB000000
0000BBBCDEEDDDDDDDDDDDDDDDDDDDDDDDDDDEEDCBBB0000
0000BBCDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDCBB0000
0000AABDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDBAA0000
000BBDBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBDBA000
000BBCDDDDDDDDDDDDDEFFFFFFFEEDDDDDDDDDDDDDCBB000
000ABDEDDDDDDDDDDDDEundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDEDBA000
000AACDDDDDDDDDDDDDFundeA7nedundeA7nedundeA7nedFFFFFEDDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDDDFundeA7nedundeA7nedFFEEEEEDDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDDEFundeA7nedFEEDDDDDDDDDDDDDDDDDDCAA000
0BBCCDDDDDDDDDDDDDEFundeA7nedFFEEEDDDDDDDDDDDDDDDDDCCBB0
0BBCEEDDDDDDDDDDDDEFundeA7nedundeA7nedFFFEEDDDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedFFFEEDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDEFFundeA7nedFundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDDEEEEEFundeA7nedundeA7nedundeA7nedFDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDDDDDDDEFundeA7nedundeA7nedFEDDDDDDDDDDDDEECBB0
0BBDEEDDDDDDDDDDDDDDDDDDEFundeA7nedundeA7nedFEDDDDDDDDDDDDEEDBB0
0BBCDDDDDDDDDDDDDDDEEEEEEFundeA7nedundeA7nedFDDDDDDDDDDDDDDDCBB0
0BBCBCDDDDDDDDDDDDEEFEEFFundeA7nedundeA7nedFEDDDDDDDDDDDDDCBCBB0
000AACDDDDDDDDDDDEEFFFFFundeA7nedundeA7nedFFEDDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFFEDDDDDDDDDDDDDDCAA000
000AACEDDDDDDDDDDDEEEFFFEEEDDDDDDDDDDDDDDECAA000
000BBDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDBB000
000BBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBB000
0000AAACDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCAAA0000
0000AAAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAAAA0000
000000AABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAA000000
000000BBCEEDDDDDDDDDDDDDDDDDDDDDDDDDDEECBB000000
000000BBCDDCCDDDDDDDDDDDDDDDDDDDDDDDEDDCBB000000
000000BBBBBACDDDDDDDDDDDDDDDDDDDDDDEEDB7BB000000
0000000000AAACDEDDDDDDDDDDDDDDDDEDCCDCBB00000000
0000000000AABBDDDDDDDDDDDDDDDDDDDDBABBBB00000000
000000000000ABBBBCEEEEDDDDEEEECBBBBA000000000000
000000000000000BBCEEEEEDDEEEEECBB000000000000000
}

!define MSIMG_5GREEN_G <img:../sprites/GeneralSymbols/5green_gray.png>
!define MSIMG_5GREEN_C <img:../sprites/GeneralSymbols/5green.png>
@enduml