@startuml
sprite $8green [43x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000BBBBBAAAAAAAABBBBB000000000000000
000000000000000BBBCCCCBBBBCCCCBBB000000000000000
000000000000AAAAACEEDDDDDDDDEECAAAAA000000000000
000000000000AABCCCDEDDDDDDDDEDCCCBAA000000000000
00000000BBBBBBDDDDDDDDDDDDDDDDDDDDBBBBBB00000000
00000000BBCDDCDDDDDDDDDDDDDDDDDDDDCDDCBB00000000
000000BBBBDEEDDDDDDDDDDDDDDDDDDDDDDEEDBBBB000000
000000BBBDEDDDDDDDDDDDDDDDDDDDDDDDDDDEDBBB000000
0000BBBCDEEDDDDDDDDDDDDDDDDDDDDDDDDDDEEDCBBB0000
0000BBCDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDCBB0000
0000AABDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDBAA0000
000BBDBCDDDDDDDDDDDDDDEEEDDDDDDDDDDDDDDDCBDBA000
000BBCDDDDDDDDDDDDDEEFFFFFEEDDDDDDDDDDDDDDCBB000
000ABDEDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFFEDDDDDDDDDDDDEDBA000
000AACDDDDDDDDDDDDEFundeA7nedundeA7nedFFFundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDEEFundeA7nedFFEEFundeA7nedundeA7nedFEDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDEEFundeA7nedFEEEEFundeA7nedFEDDDDDDDDDDDDCAA000
0BBCCDDDDDDDDDDDDDEFundeA7nedFEEEFFundeA7nedFEDDDDDDDDDDDDDCCBB0
0BBCEEDDDDDDDDDDDDEFundeA7nedundeA7nedFFFFundeA7nedFEDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFFEDDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDDEFFFFFFFFFFEDDDDDDDDDDDDEECBB0
0BBCEEDDDDDDDDDDDEFundeA7nedundeA7nedFEDEFFundeA7nedFEEDDDDDDDDDDDEECBB0
0BBDEEDDDDDDDDDDDEFundeA7nedundeA7nedFEDDEFundeA7nedFFEDDDDDDDDDDDEEDBB0
0BBCDDDDDDDDDDDDDEFundeA7nedundeA7nedFEDEEFundeA7nedFFEDDDDDDDDDDDDDCBB0
0BBCBCDDDDDDDDDDDEFundeA7nedundeA7nedFFEEFundeA7nedundeA7nedFEEDDDDDDDDDDDCBCBB0
000AACDDDDDDDDDDDDEFundeA7nedundeA7nedFFFundeA7nedundeA7nedFFEDDDDDDDDDDDDCAA000
000AACDDDDDDDDDDDDDEFFundeA7nedundeA7nedundeA7nedundeA7nedFFEDDDDDDDDDDDDDCAA000
000AACEDDDDDDDDDDDDEEEFFFEEEDDDDDDDDDDDDDECAA000
000BBDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDBB000
000BBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBB000
0000AAACDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCAAA0000
0000AAAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAAAA0000
000000AABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAA000000
000000BBCEEDDDDDDDDDDDDDDDDDDDDDDDDDDEECBB000000
000000BBCDDCCDDDDDDDDDDDDDDDDDDDDDDDEDDCBB000000
000000BBBBBACDDDDDDDDDDDDDDDDDDDDDDEEDB7BB000000
0000000000AAACDEDDDDDDDDDDDDDDDDEDCCDCBB00000000
0000000000AABBDDDDDDDDDDDDDDDDDDDDBABBBB00000000
000000000000ABBBBCEEEEDDDDEEEECBBBBA000000000000
000000000000000BBCEEEEEDDEEEEECBB000000000000000
}

!define MSIMG_8GREEN_G <img:../sprites/GeneralSymbols/8green_gray.png>
!define MSIMG_8GREEN_C <img:../sprites/GeneralSymbols/8green.png>
@enduml