@startuml
sprite $9green [44x48/16] {
000000000000000000000000000000000000000000000000
00000000000000000BBBAAAAAAAABBB00000000000000000
00000000000000000BBBAAAAAAAABBB00000000000000000
0000000000000AAAACDDCCCCCCCCDDCAABA0000000000000
00000000000AABBBACEEEEDDDDEEEECABBBAA00000000000
00000000000AABCDCDEEDDDDDDDDEEDCDCBAA00000000000
00000000BBBAABDEDDDDDDDDDDDDDDDDEDBA9A0000000000
00000000BBBABCDDDDDDDDDDDDDDDDDDDDCBAA0000000000
00000000CCCBCDDDDDDDDDDDDDDDDDDDDDDCBAAA00000000
00000000CEEDDDDDDDDDDDDDDDDDDDDDDDDDDBAA00000000
000000AABEEDDDDDDDDDDDDDDDDDDDDDDDDDDCBAAA000000
0000BBAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAABB0000
0000BBABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBABB0000
0000BBBDDDDDDDDDDDDDDDEEEDDDDDDDDDDDDDDDDBBB0000
0000BDDDDDDDDDDDDDDDEEFFFEEDDDDDDDDDDDDDDEDB0000
0000BDEDDDDDDDDDDDDEFFundeA7nedundeA7nedFFFEDDDDDDDDDDDDDEDB0000
0000ACDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDDCA0000
00BB9CDDDDDDDDDDDEFFundeA7nedFFFFundeA7nedundeA7nedundeA7nedEDDDDDDDDDDDDDC9BB00
00BBBCDDDDDDDDDDDEFundeA7nedundeA7nedFEDEFundeA7nedundeA7nedFEDDDDDDDDDDDDCBBB00
00BCDDDDDDDDDDDDDEFundeA7nedundeA7nedEDDEFundeA7nedundeA7nedFEDDDDDDDDDDDDDDCB00
00BDEEDDDDDDDDDDDEFundeA7nedundeA7nedFDDEFFundeA7nedFEEDDDDDDDDDDDEEDB00
00BCEEDDDDDDDDDDDEFundeA7nedundeA7nedFEEEFundeA7nedundeA7nedFEEDDDDDDDDDDDEEDB00
00BCEEDDDDDDDDDDDEFFundeA7nedundeA7nedFFFFundeA7nedundeA7nedFEEDDDDDDDDDDDEECB00
00BCEEDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEEDDDDDDDDDDDEECB00
00BCEEDDDDDDDDDDDDDEFFFFFFundeA7nedundeA7nedFEDDDDDDDDDDDDEECB00
00BCEEDDDDDDDDDDDDDDEEEEEFFundeA7nedFEDDDDDDDDDDDDEECB00
00BDEEDDDDDDDDDDDDDDDDDDEFundeA7nedundeA7nedFEDDDDDDDDDDDDEEDB00
00BCEEDDDDDDDDDDDDDDEDEEEundeA7nedundeA7nedundeA7nedEDDDDDDDDDDDDDEEDB00
00BCCCDDDDDDDDDDDDEEFFFFundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDDCCCB00
00BB9CDDDDDDDDDDDDEFundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedundeA7nedFEDDDDDDDDDDDDDDC9BB00
00BBACDDDDDDDDDDDDEFFFFFFEEDDDDDDDDDDDDDDDCABB00
0000ACEDDDDDDDDDDDDEEEEEEEDDDDDDDDDDDDDDDEDB0000
0000BDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDB0000
0000BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCB0000
0000BBACDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBB0000
0000BB9BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCB9BB0000
000000AAACDDDDDDDDDDDDDDDDDDDDDDDDDDDDCAAA000000
000000AAAACDDDDDDDDDDDDDDDDDDDDDDDDDDCAAAA000000
00000000AABCDDDDDDDDDDDDDDDDDDDDDDDDCBAA00000000
00000000AAAACDDDDDDDDDDDDDDDDDDDDDDCAAAA00000000
0000000000AABCDEDDDDDDDDDDDDDDDDEDCBAA0000000000
00000000000AABDDDDDDDDDDDDDDDDDDDDBAA00000000000
00000000000AACBCBCEEEEDDDDEECBBBCBCAA00000000000
0000000000000BBAACEEEEEDDEEEC8AAABB0000000000000
}

!define MSIMG_9GREEN_G <img:../sprites/GeneralSymbols/9green_gray.png>
!define MSIMG_9GREEN_C <img:../sprites/GeneralSymbols/9green.png>
@enduml