@startuml
sprite $cutandpaste [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFE97668BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFB44444446BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FB44444444448EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
E6444444444446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
A4446BEEB944446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
6444BFFFFFE84446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
4444DFFFFFFFB4446EFFFFFFFFFFFFFFFFFFFFFFFFFFEB97
4444AFFFFFFFFB4447EFFFFFFFFFFFFFFFFFFFFFFEB84444
74444DFFFFFFFFA4448FFFFFFFFFFFFFFFFFFEB96444448B
B44444BFFFFFFFF74448EFFFFFFFFFFFFFEB844444449DFF
F8444447BDEFFFFB44447EFFFFFFFFEB96444444449EFFFF
FE84444444679ABA444444BFFFFEB86444444446AEFFFFFF
FFFD86444444444444444448B9644444444446BEFFFFFFFF
FFFFFEDA8764444444444444444444444447BFFFFFFFFFFF
FFFFFFFFFFEEDB96444444444444444448DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD944444444444448DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEB744444444444447BFFFFFFFFFFFFFFF
FFFFFFFFFEDBA864444444444444444446BEFFFFFFFFFFFF
FFFFFEB97444444444444444444444444446AEFFFFFFFFFF
FFFD9444444444444444444AEB864444444446AEFFFFFFFF
FFA4444444444666444444BFFFFEB964444444449EFFFFFF
F944444469BDEFFD44446DFFFFFFFFFDB7444444449DFFFF
B444447BFFFFFFF94447EFFFFFFFFFFFFFEB964444448DFF
744449FFFFFFFFD4447EFFFFFFFFFFFFFFFFFFDA7444448B
44448FFFFFFFFE6446EFFFFFFFFFFFFFFFFFFFFFFEB84444
4444DFFFFFFFE7446DFFFFFFFFFFFFFFFFFFFFFFFFFFEB97
6444DFFFFFFD6446DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
94448FFFFD84446DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
E4444688644446DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FB44444444447EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFB44444446BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFE96668BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_CUTANDPASTE_G <img:../sprites/GeneralSymbols/Cut_and_paste_gray.png>
!define MSIMG_CUTANDPASTE_M <img:../sprites/GeneralSymbols/Cut_and_paste_mono.png>
!define MSIMG_CUTANDPASTE_C <img:../sprites/GeneralSymbols/Cut_and_paste.png>
@enduml