@startuml
sprite $pointercircle [48x48/16] {
0000000000000000000589EEEE9850000000000000000000
00000000000000005EEEEEEEEEEEEEE50000000000000000
000000000000039EEEEEEEEEEEEEEEEEE930000000000000
0000000000089EEEEEEEEEEEEEEEEEEEEEE9800000000000
00000000005EEEEEEEEEEEEEEEEEEEEEEEEEE80000000000
0000000009EEEEEEEEEEEEEEEEEEEEEEEEEEEE9000000000
00000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00000000
0000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000000
000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE000000
000009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE900000
00005EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE80000
0008EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE8000
0009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE9000
003EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE300
009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE900
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
05EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE50
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
5EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE5
8EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE8
9EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE9
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
9EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
8EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
5EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
05EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
003EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0008EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
00005EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
000009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
00000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0000000009EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
00000000005EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0000000000089EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
000000000000039EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
00000000000000005EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0000000000000000000589EEEEEEEEEEEEEEEEEEEEEEEEEE
}

!define MSIMG_POINTERCIRCLE_G <img:../sprites/GeneralSymbols/Pointer_circle_gray.png>
!define MSIMG_POINTERCIRCLE_M <img:../sprites/GeneralSymbols/Pointer_circle_mono.png>
!define MSIMG_POINTERCIRCLE_C <img:../sprites/GeneralSymbols/Pointer_circle.png>
@enduml