@startuml
sprite $pointercircle [48x48/16] {
00000000000000C9BBBCCDDDDDDCCBBBAC00000000000000
000000000000BCBBCDDDDDDDDDDDDDDCBBCB000000000000
0000000000BDBCDDDDDDDDDDDDDDDDDDDDCBDB0000000000
00000000CABBDDDDDDDDDDDDDDDDDDDDDDDDCBAC00000000
0000000B8BCDDDDDDDDDDDDDDDDDDDDDDDDDDCB0B0000000
000000BCBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBB000000
00000ABBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBB00000
0000BDBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCB0000
000B9BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB9B000
00CABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAC00
00ABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBA00
0B8BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC8B0
0ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBA0
B5CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC0B
ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBA
ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB9
BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCB
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
B4CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0B8CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00ABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00CABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
000B8BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0000BCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00000BCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
000000BBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0000000B5BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00000000CABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0000000000BCBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
000000000000BBBBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00000000000000C7BBBCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
}

!define MSIMG_POINTERCIRCLE_G <img:../sprites/GeneralSymbols/Pointer_circle_gray.png>
!define MSIMG_POINTERCIRCLE_C <img:../sprites/GeneralSymbols/Pointer_circle.png>
@enduml