@startuml
sprite $sliderbarvertical [48x48/16] {
FFFFFFFFFFFFFFFFFFB48FFFFFFFFD7777BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFEB9EEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD8768BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFEB9EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD8768BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFB9FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FEFFFFFFFEB9EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEEEEA47D8DFFFFFD8768BFFFFFFFFFFFFF
FFFFFFFFFFFFFA4444444446EFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFA44444444446EFFFFEB9EFFFFFFFFFFFFFF
FFFFFFFFFFFFFA44444444444DFFFD8768BFFFFFFFFFFFFF
FFFFFFFFFFFFFA4444444444BFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEDDDD946B6BFFFFFFEA9EEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FEFFFFFFD9769BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEDA8DEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD9769DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEDA8DEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD9769DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEDA8DEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEA87ADFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEB98BEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEB87ADFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEB87BDFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEB97BDFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEA87ADFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEB98BEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFDA87ADFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEDA8DEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD9769BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFEDA8DEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD9769BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFEB9EEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFD8768BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFEB9EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB47FFFFFFFFFFBAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB48FFFFFFFFD7667BFFFFFFFFFFFFF
}

!define MSIMG_SLIDERBARVERTICAL_G <img:../sprites/GeneralSymbols/Slider_bar_vertical_gray.png>
!define MSIMG_SLIDERBARVERTICAL_M <img:../sprites/GeneralSymbols/Slider_bar_vertical_mono.png>
!define MSIMG_SLIDERBARVERTICAL_C <img:../sprites/GeneralSymbols/Slider_bar_vertical.png>
@enduml