@startuml
sprite $tasklistorbacklog [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFE8777777777777777777777778DFFFFFFFFFFFFFFFF
FFFFFD44444444444444444444444446DFFFFFFFFFFFFFFF
FFFFFD448999999999999999999997446DFFFFFFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB4446DFFFFFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB44446DFFFFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB444446DFFFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB4444446DFFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB44444446DFFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB444444446DFFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB4444444446DFFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB44444444446DFFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFB444444444446EFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFD777777777644DFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD44DFFFFF
FFFFFD44EFFFFFFFFBEFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFFD9FFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFF9DFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFEA999BFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFD7BB7DFEA9999999999999AEFFFFE44DFFFFF
FFFFFD44EFFD7996DFD444444444444444DFFFFE44DFFFFF
FFFFFD44EFFD8DA7BAD877777777777777EFFFFE44DFFFFF
FFFFFD44EFFE88889BFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFEEED9EFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFE7887BFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFD6BB7EFE766666666666666DFFFFE44DFFFFF
FFFFFD44EFFD8B87DFD444444444444444DFFFFE44DFFFFF
FFFFFD44EFFD7BA7DFEBBBBBBBBBBBBBBBEFFFFE44DFFFFF
FFFFFD44EFFEBABBFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFDDDDFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFD7997DFFDDDDDDDDDDDDDDDFFFFFE44DFFFFF
FFFFFD44EFFD9FF9DFD444444444444444DFFFFE44DFFFFF
FFFFFD44EFFD9FF9DFD444444444444444DFFFFE44DFFFFF
FFFFFD44EFFD7997EFFEEEEEEEEEEEEEEEFFFFFE44DFFFFF
FFFFFD44EFFFEDDEFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFEAAAAEFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFD7BB7DFEAAAAAAAAAAAAAAAEFFFFE44DFFFFF
FFFFFD44EFFD9FF9DFD444444444444444DFFFFE44DFFFFF
FFFFFD44EFFD8EE8DFE777777777777777DFFFFE44DFFFFF
FFFFFD44EFFE8888EFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD44EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44DFFFFF
FFFFFD448999999999999999999999999999999844DFFFFF
FFFFFD444444444444444444444444444444444444DFFFFF
FFFFFE877777777777777777777777777777777778EFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_TASKLISTORBACKLOG_G <img:../sprites/GeneralSymbols/Task_List_or_backlog_gray.png>
!define MSIMG_TASKLISTORBACKLOG_M <img:../sprites/GeneralSymbols/Task_List_or_backlog_mono.png>
!define MSIMG_TASKLISTORBACKLOG_C <img:../sprites/GeneralSymbols/Task_List_or_backlog.png>
@enduml