@startuml
sprite $servicebusrelayold [48x48/16] {
FFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE66EFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF9447FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE644444DFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF84444446EFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB444444449FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD4444444444BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB77644446779FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEDFB4444BFEFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFEB746EB4444BF66BEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFB64444EB4444BF6446BFFFFFFFFFFFFFFFFFFF
FFFFFFFFE9444444EB4444BF644449FFFFFFFFFFFFFFFFFF
FFFFFFFE74444444EB4444BF6444448FFFFFFFFFFFFFFFFF
FFFFFFF844444467FB4444BF7444444AFFFFFFFFFFFFFFFF
FFFFFFB44444ADFFFB4444BFFD744444DFFFFFFFFFFFFFFF
FFFFFE64446EFFFFFB4444AFFFF944447FFFFFFFFFFFFFFF
FFFFFB4444DFFFFFFB4444AFFFFE64444DFFFFFFFFFFFFFF
FFFFF94447FFFFFFFB4444AFFFFFA4444AFFFFFFFFFFFFFF
FFFFFFEEEFFFFFFFFB4444AFFFFFB44447FFFFFFFFFFFFFF
FFFFEBBBBBBBBBBBB84444AFFFFFD44444BBBEFFFFFFFFFF
FFFFB44444444444444444BFFFFFD4444444448EFFFFFFFF
FFFFB44444444444444444BFFFFFD44444444444BFFFFFFF
FFFFB44444444444444444AFFFFFD444444444444DFFFFFF
FFFFB44444444444444444AFFFFFD4444444444447FFFFFF
FFFFB44446BBBBBBB84444AFFFFFEBBBBBBB844444BFFFFF
FFFFB44449FFFFFFFB4444AFFFFFFFFFFFFFFB44447FFFFF
FFFFB44449FFFFFFFB4444AFFFFFFFFFFFFFFF74444EFFFF
FFFFB44449FFFFFFFB4444AFFFFFFFFFFFFFFFB4444DFFFF
FFFFB44449FFFFFFFB4444AFFFFFFFFFFFFFFFB4444BFFFF
FFFFB44449FFFFFFFB4444AFFFFFFFFFFFFFFFB4444BFFFF
FFFFB44448EEEEEEFB4444AFEEEEEEEEEEEEEEB4444BFFFF
FFFFB44444444446EB4444BF7444444444444444444BFFFF
FFFFB44444444444EB4444BF6444444444444444444BFFFF
FFFFB44444444444EB4444BF6444444444444444444BFFFF
FFFFE64444444444EB4444BF6444444444444444444DFFFF
FFFFFE9888888889FB4444BFBAAAAAA99999999999BFFFFF
FFFFFFFFFFFFFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB78644446879FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD4444444444BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB444444449FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF84444446EFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE644444DFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF8447FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE64EFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_SERVICEBUSRELAYOLD_G <img:../sprites/Deprecated/Service_Bus_Relay_old_gray.png>
!define MSIMG_SERVICEBUSRELAYOLD_M <img:../sprites/Deprecated/Service_Bus_Relay_old_mono.png>
!define MSIMG_SERVICEBUSRELAYOLD_C <img:../sprites/Deprecated/Service_Bus_Relay_old.png>
@enduml