@startuml
!ifdef MS_SPRITESPATH
!else
!define MS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-microsoft-icons/master/sprites
!endif

!includeurl MS_SPRITESPATH/Cloud/accounts_microsoft_account.puml
!includeurl MS_SPRITESPATH/Cloud/accounts_work_account.puml
!includeurl MS_SPRITESPATH/Cloud/analysis_service.puml
!includeurl MS_SPRITESPATH/Cloud/azure_acitve_directory_access_control.puml
!includeurl MS_SPRITESPATH/Cloud/azure_active_directory.puml
!includeurl MS_SPRITESPATH/Cloud/azure_active_directory_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_active_directory_health_monitoring.puml
!includeurl MS_SPRITESPATH/Cloud/azure_active_directory_health_monitoring_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_advisor.puml
!includeurl MS_SPRITESPATH/Cloud/azure_alert.puml
!includeurl MS_SPRITESPATH/Cloud/azure_api_management.puml
!includeurl MS_SPRITESPATH/Cloud/azure_api_management_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_application_gateway.puml
!includeurl MS_SPRITESPATH/Cloud/azure_application_gateway_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_application_insights.puml
!includeurl MS_SPRITESPATH/Cloud/azure_application_insights_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_azure_api_apps.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_azure_api_apps_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_mobile_app_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_mobile_app_was_mobile_services.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_web_app_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_web_app_was_websites.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_worker_pools.puml
!includeurl MS_SPRITESPATH/Cloud/azure_app_service_worker_pools_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_automation.puml
!includeurl MS_SPRITESPATH/Cloud/azure_automation_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_automation_runbooks.puml
!includeurl MS_SPRITESPATH/Cloud/azure_automation_runbooks_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_backup.puml
!includeurl MS_SPRITESPATH/Cloud/azure_backup_backup_agent.puml
!includeurl MS_SPRITESPATH/Cloud/azure_backup_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_backup_recovery_vault.puml
!includeurl MS_SPRITESPATH/Cloud/azure_batch.puml
!includeurl MS_SPRITESPATH/Cloud/azure_biztalk_services.puml
!includeurl MS_SPRITESPATH/Cloud/azure_biztalk_services_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_biztalk_services_hybrid_connections.puml
!includeurl MS_SPRITESPATH/Cloud/azure_biztalk_services_hybrid_connections_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_biztalk_services_hybrid_connection_manager.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cache_including_redis.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cache_including_redis_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cache_redis_product_icon_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_service.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_services_web_role.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_services_web_roles.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_services_worker_role.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_services_worker_roles.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cloud_service_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_computer_vision_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_emotion_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_luis_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_recommendations_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_speech_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_textanalytics_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognative_services_web_language_model_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cognitive_services.puml
!includeurl MS_SPRITESPATH/Cloud/azure_compute_autoscaling.puml
!includeurl MS_SPRITESPATH/Cloud/azure_container_service.puml
!includeurl MS_SPRITESPATH/Cloud/azure_container_service_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_content_delivery_network_cdn.puml
!includeurl MS_SPRITESPATH/Cloud/azure_content_delivery_network_cdn_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_cortona_management_suite.puml
!includeurl MS_SPRITESPATH/Cloud/azure_database_general_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_dataservices_category_rollup.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_catalog.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_catalog_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_factory.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_factory_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_lake.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_lake_analytics.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_lake_analytics_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_lake_store.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_lake_store_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_warehouse.puml
!includeurl MS_SPRITESPATH/Cloud/azure_data_warehouse_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_devtest_labs.puml
!includeurl MS_SPRITESPATH/Cloud/azure_devtest_labs_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_dns.puml
!includeurl MS_SPRITESPATH/Cloud/azure_dns_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb_database.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb_docdb_account.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb_docdb_collections_1.puml
!includeurl MS_SPRITESPATH/Cloud/azure_documentdb_document_2.puml
!includeurl MS_SPRITESPATH/Cloud/azure_event_hubs.puml
!includeurl MS_SPRITESPATH/Cloud/azure_event_hubs_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_expressroute.puml
!includeurl MS_SPRITESPATH/Cloud/azure_express_route_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_functions.puml
!includeurl MS_SPRITESPATH/Cloud/azure_functions_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_hdinsight.puml
!includeurl MS_SPRITESPATH/Cloud/azure_hdinsight_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_hockeyapp.puml
!includeurl MS_SPRITESPATH/Cloud/azure_hockeyapp_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_iothub_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_iot_hub.puml
!includeurl MS_SPRITESPATH/Cloud/azure_keyvault_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_key_vault.puml
!includeurl MS_SPRITESPATH/Cloud/azure_load_balancer_automatic.puml
!includeurl MS_SPRITESPATH/Cloud/azure_load_balancer_feature.puml
!includeurl MS_SPRITESPATH/Cloud/azure_load_balancer_feature_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_machine_learning.puml
!includeurl MS_SPRITESPATH/Cloud/azure_machine_learning_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_management_portal.puml
!includeurl MS_SPRITESPATH/Cloud/azure_management_portal_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_media_services.puml
!includeurl MS_SPRITESPATH/Cloud/azure_media_services_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_mobile_engagement.puml
!includeurl MS_SPRITESPATH/Cloud/azure_mobile_engagement_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_multi_factor_authentication.puml
!includeurl MS_SPRITESPATH/Cloud/azure_multi_factor_authentication_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_mysql_cleardb_database.puml
!includeurl MS_SPRITESPATH/Cloud/azure_mysql_cleardb_database_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_notification_hubs.puml
!includeurl MS_SPRITESPATH/Cloud/azure_notification_hubs_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_remoteapp.puml
!includeurl MS_SPRITESPATH/Cloud/azure_remoteapp_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_rights_management_rms.puml
!includeurl MS_SPRITESPATH/Cloud/azure_scheduler.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sdk.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sdk_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_search.puml
!includeurl MS_SPRITESPATH/Cloud/azure_search_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_security_center.puml
!includeurl MS_SPRITESPATH/Cloud/azure_security_center_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_queues.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_queues_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_relay.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_topics.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_bus_topics_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_fabric.puml
!includeurl MS_SPRITESPATH/Cloud/azure_service_fabric_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_site_recovery.puml
!includeurl MS_SPRITESPATH/Cloud/azure_site_recovery_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_database.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_database_generic.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_database_generic_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_database_premium.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_datasync.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_datawarehouse.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_datawarehouse_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_stretch_database.puml
!includeurl MS_SPRITESPATH/Cloud/azure_sql_stretch_database_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_stack.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storage.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storage_blob.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storage_files.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storage_queue.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storage_table.puml
!includeurl MS_SPRITESPATH/Cloud/azure_store.puml
!includeurl MS_SPRITESPATH/Cloud/azure_store_marketplace.puml
!includeurl MS_SPRITESPATH/Cloud/azure_store_marketplace_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storsimple.puml
!includeurl MS_SPRITESPATH/Cloud/azure_storsimple_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_stream_analytics.puml
!includeurl MS_SPRITESPATH/Cloud/azure_stream_analytics_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_subscription.puml
!includeurl MS_SPRITESPATH/Cloud/azure_traffic_manager.puml
!includeurl MS_SPRITESPATH/Cloud/azure_traffic_manager_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machine.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machines_availability_set.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machines_availability_set_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machines_linux_penguin_shadow_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machine_2_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_machine_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_network.puml
!includeurl MS_SPRITESPATH/Cloud/azure_virtual_network_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vm_container.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vm_scale_set.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vm_scale_set_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vm_symbol_only.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vpn_gateway.puml
!includeurl MS_SPRITESPATH/Cloud/azure_vpn_gateway_color.puml
!includeurl MS_SPRITESPATH/Cloud/azure_webapp_webjobs.puml
!includeurl MS_SPRITESPATH/Cloud/azure_webapp_webjobs_color.puml
!includeurl MS_SPRITESPATH/Cloud/bot_services.puml
!includeurl MS_SPRITESPATH/Cloud/cloud_office_365.puml
!includeurl MS_SPRITESPATH/Cloud/container_service.puml
!includeurl MS_SPRITESPATH/Cloud/logic_apps.puml
!includeurl MS_SPRITESPATH/Cloud/logic_apps_color.puml
!includeurl MS_SPRITESPATH/Cloud/microsoft_azure.puml
!includeurl MS_SPRITESPATH/Cloud/monitor.puml
!includeurl MS_SPRITESPATH/Cloud/network_security_group.puml
!includeurl MS_SPRITESPATH/Cloud/network_security_group_color.puml
!includeurl MS_SPRITESPATH/Cloud/newart_nativesize.puml
!includeurl MS_SPRITESPATH/Cloud/office_365.puml
!includeurl MS_SPRITESPATH/Cloud/office_365_subscription.puml
!includeurl MS_SPRITESPATH/Cloud/oms_log_analytics.puml
!includeurl MS_SPRITESPATH/Cloud/operations_management_suite_oms.puml
!includeurl MS_SPRITESPATH/Cloud/operations_management_suite_oms_color.puml
!includeurl MS_SPRITESPATH/Cloud/os_image.puml
!includeurl MS_SPRITESPATH/Cloud/power_bi_embedded.puml
!includeurl MS_SPRITESPATH/Cloud/resourcegroup_color.puml
!includeurl MS_SPRITESPATH/Cloud/resource_group.puml
!includeurl MS_SPRITESPATH/Cloud/service_bus.puml
!includeurl MS_SPRITESPATH/Cloud/service_endpoint.puml
!includeurl MS_SPRITESPATH/Cloud/sql_database_pools.puml
!includeurl MS_SPRITESPATH/Cloud/sql_elastic_pools.puml
!includeurl MS_SPRITESPATH/Cloud/storage.puml
!includeurl MS_SPRITESPATH/Cloud/unidentified_feature_object.puml
!includeurl MS_SPRITESPATH/Cloud/unidentified_feature_object_color.puml
!includeurl MS_SPRITESPATH/Cloud/vhd.puml
!includeurl MS_SPRITESPATH/Cloud/vhd_data_disk.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_bitbucket_code_source.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_bitbucket_code_source_color.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_codeplex_source.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_codeplex_source_color.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_color.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_dropbox_code_source.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_dropbox_code_source_color.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_github.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_github_color.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_git_repository.puml
!includeurl MS_SPRITESPATH/Cloud/visual_studio_team_services_git_repository_color.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks_color.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks_mono.puml
@enduml