@startuml
sprite $analysisservice [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFF
44444444444444444444DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44444444444444444444DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44444444444444444444DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44777777777777777744DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44EFFFFFFFFFFFFFFF74DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44EFFFFFFFFFFFFFFF74DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44EFFFFFFFFFFFFFFF74DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44EFFFFFB66BFFFFFF74DFFFFFFFFFFFFFFFFFFFFFFFFFFF
44EFFFFB4444DFFFFF74DFFFFFFEAAAAAAAAAAAAAAAAAAAA
44EFFFFA44449EFFFF74DFFFFFFD44444444444444444444
44EFFFFB4444467BEFB7DFFFFFFD44444444444444444444
44EFFFFF944AEB8647ADEFFFFFFD44444444444444444444
44EFFFFFFB4EFFFED96469BEFFFD46BBBBBBBBBBBBBBBB44
44EFFFFFFE4DFFFFFFDBA7468BEE99FFFFFFFFFFFFFFFE44
446777777D6BB7777747EFEB8647BDFFFFFFFFFFFFFFFE44
444444444B7AA4444444DFFFFEB9646ADFFFFDBEFFFFFE44
DDDDDDDDDF88EDDDDDDDFFFFFFFFDBA6469B8447EFFFFE44
FFFFFFFFFFA6FFFFFFFFFFFFFFFD49FFDB744444BFFFFE44
FFFFFFFFFFB6EFFFFFFFFFFFFFFD47FFFFF94444AFFFFE44
FFFFFFFFFFD4DFFFFFFFFFFFFFFD47FFFD844444DFFFFE44
FFFFFFFFFFE6BFFFFFFFFFFFFFFD48FE947BD99DFFFFFE44
FFFEEEEEEEE6AFDEEEEEEEEFFFFEBD946BFFFFFFFFFFFE44
FFE6444444B88B444444446EFFFEA66BDDDDDDDDDDDDDB44
FFE44444449A7B444444444EFFB66AD94444444444444444
FFE44444448B6D444444449EB64AED977777777777777778
FFE4477777AD4D9777778BB749EFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFE6BFFFFFFD748EFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFF6BFFFFD848DFFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFF78EFE847BB8EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFB446847BFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFE64444BFFFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFE44446FFFFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFF7444AFFFFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFE97AFFFFFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46FFFFFFFFFFFFFFFF64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE46EFFFFFFFFFFFFFFE64EFFFFFFFFFFFFFFFFFFFFFFFF
FFE44777777777777777744EFFFFFFFFFFFFFFFFFFFFFFFF
FFE64444444444444444446EFFFFFFFFFFFFFFFFFFFFFFFF
FFFEDDDDDDDDDDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_ANALYSISSERVICE_G <img:../sprites/Cloud/Analysis_Service_gray.png>
!define MSIMG_ANALYSISSERVICE_M <img:../sprites/Cloud/Analysis_Service_mono.png>
!define MSIMG_ANALYSISSERVICE_C <img:../sprites/Cloud/Analysis_Service.png>
@enduml