@startuml
sprite $azureremoteappcolor [48x48/16] {
FFFFFFFFFFFFFFFFFEB9764444679BEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEB8644444444444448BEFFFFFFFFFFFFFF
FFFFFFFFFFFFEA64444444444444444446AEFFFFFFFFFFFF
FFFFFFFFFFFB644444479BBBBBB974444446BFFFFFFFFFFF
FFFFFFFFFE8444448BEFFFFFFFFFFEB8444448EFFFFFFFFF
FFFFFFFFD644449EFFFFFFFFFFFFFFFFE944446DFFFFFFFF
FFFFFFFB44447DFFFFFFFFFFFFFFFFFFFFD74444BFFFFFFF
FFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFA4444BFFFFFF
FFFFFD4444BFFFFFFFFFFFFFFFFFFFFFFFFFFB4444DFFFFF
FFFFE6444BFFFFFFFFFFFFFFFFFFFFFFEEFFFFD4446EFFFF
FFFF8444BFFFFFFFFFFFFFFFFFFFFFFEA9EFFFFB4448FFFF
FFFB444AFFFFFFFFFFFFFFFFFFFFFFEA889EFFFFA444BFFF
FFE6447FFFFFFFFFFFFFFFFFFFFFFEA88889FFFFF7446EFF
FFB444DFFFFFFFFFFFFFFFFFFFFFEA88888BFFFFFD444AFF
FE6449FFFFFFFFFFFFFFFFFFFFFEA88888BFFFFFFF9446EF
FB444DFFFFFFFFFFFFFFFFFFFFEA88888BFFFFFFFFE444BF
F8448FFFFFFFFFFFFFFFFFFFFEA88888BFFFFFFFFFF8448F
E644BFFFFFFFFFFFFFFFFFFFEA88888BFFFFFFFFFFFB444E
B444EFFFFFFFFFBBFFFFFFFFA88888BFFFFFFFFFFFFE444B
9447FFFFFFFFFB88BFFFFFFB88888AFFFFFFFFFFFFFF7449
7449FFFFFFFFB8888BFFFFFB88888BFFFFFFFFFFFFFF9447
644BFFFFFFFF988888BFFFFFB88888BFFFFFFFFFFFFFB446
444BFFFFFFFFE988888BFFFFFB88888BFFFFFFFFFFFFB444
444BFFFFFFFFFE988888BFFFFFB88888BFFFFFFFFFFFB444
444BFFFFFFFFFFE988888BFFFFFB88888BFFFFFFFFFFB444
444BFFFFFFFFFFFE988888BFFFFFB88888BFFFFFFFFFB444
644BFFFFFFFFFFFFE988888BFFFFFB88888BFFFFFFFFB446
7449FFFFFFFFFFFFFE988888BFFFFFB8888AFFFFFFFF9447
9447FFFFFFFFFFFFFFB88888AFFFFFFB88AEFFFFFFFF7449
B444EFFFFFFFFFFFFB88888AEFFFFFFFBBFFFFFFFFFE444B
E444BFFFFFFFFFFFB88888AEFFFFFFFFFFFFFFFFFFFB446E
F8448FFFFFFFFFFD88888AEFFFFFFFFFFFFFFFFFFFF8448F
FB444DFFFFFFFFD88888AEFFFFFFFFFFFFFFFFFFFFE444BF
FE6449FFFFFFFD88888AEFFFFFFFFFFFFFFFFFFFFF9446FF
FFA444DFFFFFD88888AEFFFFFFFFFFFFFFFFFFFFFD444BFF
FFE6447FFFFF98888AEFFFFFFFFFFFFFFFFFFFFFF7446EFF
FFFB444AFFFFE988AEFFFFFFFFFFFFFFFFFFFFFFA444BFFF
FFFF8444BFFFFE99EFFFFFFFFFFFFFFFFFFFFFFB4448FFFF
FFFFE6444BFFFFEEFFFFFFFFFFFFFFFFFFFFFFB4446EFFFF
FFFFFD4444BFFFFFFFFFFFFFFFFFFFFFFFFFFB4446DFFFFF
FFFFFFB4444AFFFFFFFFFFFFFFFFFFFFFFFFA4444DFFFFFF
FFFFFFFB44447DFFFFFFFFFFFFFFFFFFFFD74446DFFFFFFF
FFFFFFFFD644449EFFFFFFFFFFFFFFFFE944446DFFFFFFFF
FFFFFFFFFE8444448BEFFFFFFFFFFEB8444448EFFFFFFFFF
FFFFFFFFFFFB644444479BBBBBB974444446BFFFFFFFFFFF
FFFFFFFFFFFFEA64444444444444444446BEFFFFFFFFFFFF
FFFFFFFFFFFFFFEB8444444444444468BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEB9764444679BEFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREREMOTEAPPCOLOR_G <img:../sprites/Cloud/Azure_RemoteApp_COLOR_gray.png>
!define MSIMG_AZUREREMOTEAPPCOLOR_M <img:../sprites/Cloud/Azure_RemoteApp_COLOR_mono.png>
!define MSIMG_AZUREREMOTEAPPCOLOR_C <img:../sprites/Cloud/Azure_RemoteApp_COLOR.png>
@enduml