@startuml
sprite $azuremultifactorauthentication [48x48/16] {
FFFFFFFFFFFFFFFFFFFEEBB8746BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEDBB97644444446EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB644444444444444DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFE4444446BEA444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFD4444446B96444444AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFE44444444444444448FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF6444444679BBDB646FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF8446BDEFFFFFFFB44EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA44DFFFFFFFFFFE44DFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB46FFFFFFFFFFFF64BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFD44EFFFFFFFFFFF84AFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFE44DFFFFFFFFFFFA48FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF74BFFFFFFFFFFFB46FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF849FFFFFFFFFFFD44EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFA47FFFFFFFFFFFE44DFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFB46FFFFFFFFFFFF64BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFD44EFFFFFFFFFFF84AFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFE64DFFFFFFFFFFFA49FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF74BFFFFFFFFFFFEBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF849FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFA47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB46FFFFFFFFEDBA878EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD44EFEDBA8644444448FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFE446644444444444446FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB444444444444444444EFFFFFFFFFFFFFF
FFFFFFFFFFFFFF9444444444444444444DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB444444444444444444BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB4444444444444444449FFFFFFFFFFFFFF
FFFFFFFFFFFFFFE44444444BDD74444447FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF6444444BFFFE6444446FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF7444446FFFFFA444444EFFFFFFFFFFFFF
FFFFFFFFFFFFFFF9444446EFFFF9444444DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB444444AFFFD6444444BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFD44444449FF944444449FFFFFFFFFFFFF
FFFFFFFFFFFFFFFE44444446FFA44444447FFFFFFFFFFFFF
FFFFFFFFFFFFFFFF64444444EFB44444446FFFFFFFFFFFFF
FFFFFFFFFFFFFFFF74444444AB844444444EFFFFFFFFFFFF
FFFFFFFFFFFFFFFF9444444444444444444DFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB444444444444444444BFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD4444444444444444449FFFFFFFFFFFF
FFFFFFFFFFFFFFFFE4444444444444444447FFFFFFFFFFFF
FFFFFFFFFFFFFFFFF6444444444444444446FFFFFFFFFFFF
FFFFFFFFFFFFFFFFF7444444444444444444EFFFFFFFFFFF
FFFFFFFFFFFFFFFFF9444444444466444444DFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB4444448BDEEB444444EFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD444444ABA87444468BFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE64444444678ABDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB4478ABEEFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREMULTIFACTORAUTHENTICATION_G <img:../sprites/Cloud/Azure_Multi_Factor_Authentication_gray.png>
!define MSIMG_AZUREMULTIFACTORAUTHENTICATION_M <img:../sprites/Cloud/Azure_Multi_Factor_Authentication_mono.png>
!define MSIMG_AZUREMULTIFACTORAUTHENTICATION_C <img:../sprites/Cloud/Azure_Multi_Factor_Authentication.png>
@enduml