@startuml
sprite $azurevirtualnetworkcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFE9BFFFFFFFFFFFFFFFFFFB9EFFFFFFFFFFFF
FFFFFFFFFFFE746EFFFFFFFFFFFFFFFFE647EFFFFFFFFFFF
FFFFFFFFFFE744AFFFFFFFFFFFFFFFFFFA447EFFFFFFFFFF
FFFFFFFFFE744AFFFFFFFFFFFFFFFFFFFFA447EFFFFFFFFF
FFFFFFFFE744AFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFF
FFFFFD644AFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446DFFFFF
FFFFD644AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446DFFFF
FFFD644AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446DFFF
FFD644AFFFFFFEDEFFFFFFFDDFFFFFFFEDEFFFFFFB446DFF
FD644AFFFFFE9667BFFFFD8668EFFFFB7669EFFFFFB446DF
D6449FFFFFFA66667DFFE866669FFFE76666BFFFFFFB446D
6447FFFFFFF866666BFFD666667EFFB666668FFFFFFF9446
7446EFFFFFF866666BFFD666667EFFD666669FFFFFFF7447
E7447EFFFFFB66668EFFFA6666AFFFF86666BFFFFFF9447E
FE6447EFFFFFD879EFFFFFB88BFFFFFE978BFFFFFF9447EF
FFD6447EFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFF9447EFF
FFFD6447EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9447EFFF
FFFFE6447EFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9447EFFFF
FFFFFE6448EFFFFFFFFFFFFFFFFFFFFFFFFFFF9448EFFFFF
FFFFFFE7448EFFFFFFFFFFFFFFFFFFFFFFFFF9448EFFFFFF
FFFFFFFE7448FFFFFFFFFFFFFFFFFFFFFFFF9448EFFFFFFF
FFFFFFFFE7448FFFFFFFFFFFFFFFFFFFFFF9448EFFFFFFFF
FFFFFFFFFE7448FFFFFFFFFFFFFFFFFFFF9448EFFFFFFFFF
FFFFFFFFFFE8448FFFFFFFFFFFFFFFFFF9448EFFFFFFFFFF
FFFFFFFFFFFE844DFFFFFFFFFFFFFFFFE448FFFFFFFFFFFF
FFFFFFFFFFFFFA9FFFFFFFFFFFFFFFFFF99FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREVIRTUALNETWORKCOLOR_G <img:../sprites/Cloud/Azure_Virtual_Network_COLOR_gray.png>
!define MSIMG_AZUREVIRTUALNETWORKCOLOR_M <img:../sprites/Cloud/Azure_Virtual_Network_COLOR_mono.png>
!define MSIMG_AZUREVIRTUALNETWORKCOLOR_C <img:../sprites/Cloud/Azure_Virtual_Network_COLOR.png>
@enduml