@startuml
sprite $azurecognativeservicesrecommendationscolor [48x48/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA988889AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA880078AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA880078AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA99AAA98800889AAA99AAAAAAAAAAAAAAA
AAAAAAAAAAAAAA9789986B0000B7999979AAAAAAAAAAAAAA
AAAAAAAAAAAAA97BDDDD00000000DDDDA79AAAAAAAAAAAAA
AAAAAAAAAAAA97B0000000DDDD0000000A79AAAAAAAAAAAA
AAAAAAAAAAAA9A8000C6777777774B0009B9AAAAAAAAAAAA
AAAAAAAAAAAAA96C07A7888888887970A79AAAAAAAAAAAAA
AAAAAAAAAAAAA97C7D788888888887B8A79AAAAAAAAAAAAA
AAAAAAAAAAAAA9895788888887888875A99AAAAAAAAAAAAA
AAAAAAAAAAAA96A678888888778888876B69AAAAAAAAAAAA
AAAAAAAAA977870578888887878888875078779AAAAAAAAA
AAAAAAAAA97000A378888870777788870B00079AAAAAAAAA
AAAAAAAAA97000A0788887D877997888DA00079AAAAAAAAA
AAAAAAAAA97000907887400000678887D900079AAAAAAAAA
AAAAAAAAA97000A378874000094788873A00079AAAAAAAAA
AAAAAAAAA988870578874000077888875088889AAAAAAAAA
AAAAAAAAAAAA96A778878776787888876A79AAAAAAAAAAAA
AAAAAAAAAAAAA98A5788788888888875999AAAAAAAAAAAAA
AAAAAAAAAAAAA97C7D788888888887A7B78AAAAAAAAAAAAA
AAAAAAAAAAAAA96C08A7888888887970B69AAAAAAAAAAAAA
AAAAAAAAAAAA999000B3777777774A000999AAAAAAAAAAAA
AAAAAAAAAAAA98B000000DDCCDD000000A78AAAAAAAAAAAA
AAAAAAAAAAAAA97B0000000000000000A78AAAAAAAAAAAAA
AAAAAAAAAAAAAA98A9897C0000C7899978AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA99AAA98800899AAA98AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA880089AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA870089AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA999999AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}

!define MSIMG_AZURECOGNATIVESERVICESRECOMMENDATIONSCOLOR_G <img:../sprites/Cloud/Azure_Cognative_Services_recommendations_COLOR_gray.png>
!define MSIMG_AZURECOGNATIVESERVICESRECOMMENDATIONSCOLOR_C <img:../sprites/Cloud/Azure_Cognative_Services_recommendations_COLOR.png>
@enduml