@startuml
sprite $azurevmscalesetcolor [48x48/16] {
BCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA0000000000
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCA90000000000
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCA90000000000
DDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA90000000000
DDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA90000000000
DDDCCCCCCCCCCCCCCBABCCCCCCCCCCCCCCCCA90000000000
DDDCCCCCCCCCCCCCBAABABCCCCCCCCCCCCCCBBAAA0C00000
DDDCCCDDDDDDDDDCCCCCCCDDDDDDDDDDDDDDCCCCBA6A0000
DDDCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCA90000
DDDCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCA90000
DDDCCCDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA90000
DDDCCCDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA90000
DDDCCCDDDCCCCCCCCCCCCCCBACCCCCCCCCCCCCCCCCA90000
DDDCCCDDDCCCCCCCCCCCCCAB9ABCCCCCCCCCCCCCCCA8DDDD
DDDCCCDDDCCCCDDDDDDDDCCCCCCCDDDDDDDDDDDDDDCCCBAA
DDDCCCDDDCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCB
DDDCCCDDDCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCCCCCAABABCCCCCCCCCCCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCCCBA9CCAAACCCCCCCCCCCCCC
DDDCCCDDDCCDDDDCCCCCCCCCBADB0000B8ABCCCCCCCCCCCC
DDDCCDDDDCCDDDDCCCCCCCCCAAA000000ADACCCCCCCCCCCC
DDDDDDDDDCCDDDDCCCCCCCDDCBABA00B6ABCCDCCCCCCCCCC
CDDDCCDDDCCDDDDCCCCCCCDFEDCBA89ABCCDDDCCCCCCCCCC
ABCBBCDDDCCDDDDCCCCCCCDFFEDCCBABCDDEEDCCCCCCCCCC
0000ABDDDCCDDDDCCCCCCCDFFFFEDCCDDEEEEDCCCCCCCCCC
0000ABDDDCCDDDDCCCCCCCDFFFFFFDDDEEEEEDCCCCCCCCCC
0000ABDDDCCDDDDCCCCCCCDFFFFFFDDEEEEEEDCCCCCCCCCC
0000ABDDDCCDDDDCCCCCCCDFFFFFFDDEEEEEEDCCCCCCCCCC
0000ABDDDDDDDDDCCCCCCCDFFFFFFDDEEEEEEDCCCCCCCCCC
0000AADDDDCDDDDCCCCCCCDEFFFFFDDEEEEEDDCCCCCCCCCC
0000BBBCCCCCDDDCCCCCCCCCDEFFFDDEEEEDCCCCCCCCCCCC
00000CCBBABBDDDCCCCCCCCCCDEFFDDEEDDCCCCCCCCCCCCC
00000000009BDDDCCCCCCCCCCCCDEDDDDCCCCCCCCCCCCCCC
00000000009BDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
00000000009BDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
00000000009BDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
00000000009BDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
0000000000AACDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBA
00000000000AAAA999999999AABBBBBBBBA9999999999AA6
00000000000000000000000B69AAAAAAAAA9900000000000
00000000000000000000000A59AAAAAAAAA9900000000000
000000000000000000000A889AAAAAAAAAA9980000000000
000000000000000099AAAAAABBBBBBBBBBBBAAAAAA990000
00000000000000009ACCCCCCCCCCCCCCCCCCCCCCCB990000
000000000000000099CCCCCCCCCCCCCCCCCCCCCCCB980000
}

!define MSIMG_AZUREVMSCALESETCOLOR_G <img:../sprites/Cloud/Azure_VM_Scale_Set_COLOR_gray.png>
!define MSIMG_AZUREVMSCALESETCOLOR_C <img:../sprites/Cloud/Azure_VM_Scale_Set_COLOR.png>
@enduml