@startuml
sprite $azuredatafactorycolor [48x48/16] {
00000C7BBAAAABCC00000000000000000000000000000000
0DABBBCCDDDDDCCCBB8C0000000000000000000000000000
BABCDEEEEEEEEEEEDDBBACC0000000000000000000000000
CBDEEEEEEEEEEEEEEEDBCBB0000000000000000000000000
A5BDDDDDDDDDDDDDDDCBABA0000000000000000000000000
A9ABBBCCCCCCCCCBBBBABB90000000000000000000000000
BBA99AAAAAAAAAAAAABCCB90000000000000000000000000
BBBBBAA9999AAABBCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB90000000000000000000000000
BBBBBBBBBBBCCCCCCCCCCB9000000000AAA8000000000BBA
BBBBBBBBBBBCCCCCCCCCCB90000000DAABB800000000ACAB
BBBBBBBBBBBCCCCCCCCCCB9000000C9ABCB80000000AABCC
BBBBBBBBBBBCCCCCCCCCCB900000B9ACCCB8000000AABCCC
BBBBBBBBBBBCCCCCCCCCCB90000A7ACCCCB80000D9ABCCCC
BBBBBBBBBBBCCCCCCCCCCB9000ACACCCCCB8000B9ABCCCCC
BBBBBBBBBBBCCCCCCCCCCB900AABCCCCCCB800B8ACCCCCCC
BBBBBBBBBBBCCCCCCCCCCB90AABCCCCCCCB80ADACCCCCCCC
BBBBBBBBBBBCCCCCCCCCCB99ABCCCCCCCCB8ABBCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCB9ABCCCCCCCCCB8ABCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCBACCCCCCCCCCCBBBCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCBCCCCCCCCCCCCBBCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCC99999CCCCA9999BCCCB9999ACCCCC
BBBBBBBBBBBCCCCCCCC99099BCCCA9009BCCCB8909ACCCCC
BBBBBBBBBBBCCCCCCCC99099BCCCA9009BCCCB8909ACCCCC
BBBBBBBBBBBCCCCCCCC99099BCCCA9009BCCCB8909ACCCCC
BBBBBBBBBBBCCCCCCCC99999CCCCA9999BCCCB9999ACCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
}

!define MSIMG_AZUREDATAFACTORYCOLOR_G <img:../sprites/Cloud/Azure_Data_Factory_COLOR_gray.png>
!define MSIMG_AZUREDATAFACTORYCOLOR_C <img:../sprites/Cloud/Azure_Data_Factory_COLOR.png>
@enduml