@startuml
sprite $azurecontainerservice [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFBDDBEFFFFFFFFFFFFDDEBEFFFFFFFFFFFFFF
FFFFFFFFFD976AB448BEFFFFFFDA769B447BEFFFFFFFFFFF
FFFFFFFF978BDBB444468BFFFA79ADAB444448BFFFFFFFFF
FFFFFFFEBBDDDBB4444444EFFBBDBEAB4444444EFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444EFFFFFFFF
FFFFFFFE99BDDBB444446AFFFA8BBEAB4444469FFFFFFFFF
FFFFFFFFB8679BB4448BEFFFFD96799B4447BEFFFFFFFFFF
FFFFFFFFFFEB6BB6AEFFFFFFFFFEB79D6ADFFFFFFFFFFFFF
FFFD9BD8BEFFFFFFFFFFD9BE8BEFFFEFFFFFFB8BD8BEFFFF
DA767AD4469BFFFFFDA767AD4468BFFFFFD9667BB4469DFF
88BBDAD444446AFFFA8BBEAD444446AFFE98ADBBB444446A
BBDBDAD4444444EFFDBDBEAD4444444EFEDBDDBBB4444444
BBDBDAD4444444EFFDBDBEAD4444444EFEDBDDBBB4444444
BBDBDAD4444444EFFDBDBEAD4444444EFEDBDDBBB4444444
BBDBDAD4444444EFFDBDBEAD4444444EFEDBDDBBB4444444
BBDBDAD4444444EFFDBDBEAD4444444EFEDBDDBBB4444444
BBDBDAD4444444EFFDBDBEAD4444444EFEBBDDBBB4444444
87ABDAD444448BFFF97BBEAD444448BFFE88ADBBB444448B
EB877AD446AEFFFFFEB877AD446AEFFFFFEB877BB447BEFF
FFFEABE9DFFFFFFFFFFFEABE9DFFFFFFFFFFFDADD9DFFFFF
FFFFFFFFFFEB7BB6ADFFFFFFFFFEB8AD69DFFFFFFFFFFFFF
FFFFFFFFB8679BB4447AEFFFFD977AAB4446ADFFFFFFFFFF
FFFFFFFEA9BDDBB4444448FFFA9BBEAB4444447EFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEDBDDDBB4444444EFFDBDBEAB4444444DFFFFFFFF
FFFFFFFEBBDDDBB4444446EFFBBDBEAB4444446EFFFFFFFF
FFFFFFFF978BBBB44447BEFFFA68ADAB44446AEFFFFFFFFF
FFFFFFFFFD966AB449DFFFFFFFDA769B448BFFFFFFFFFFFF
FFFFFFFFFFFEBDDBEFFFFFFFFFFFEBBEBEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURECONTAINERSERVICE_G <img:../sprites/Cloud/Azure_Container_Service_gray.png>
!define MSIMG_AZURECONTAINERSERVICE_M <img:../sprites/Cloud/Azure_Container_Service_mono.png>
!define MSIMG_AZURECONTAINERSERVICE_C <img:../sprites/Cloud/Azure_Container_Service.png>
@enduml