@startuml
sprite $azurecognativeservicescomputervisioncolor [48x48/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA9999AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA988ADDA889AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA896B000000B799AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA998C0897667980C899AAAAAAAAAAAAAAA
AAAAAAAAAAAAAA80A07967888877870A08AAAAAAAAAAAAAA
AAAAAAAAAAAA988B0677888888887870C889AAAAAAAAAAAA
AAAAAAAAAAA99800797888888888879700899AAAAAAAAAAA
AAAAAAAAAA99900C5788888887788875B009A9AAAAAAAAAA
AAAAAAAAA998000797887088864788887000899AAAAAAAAA
AAAAAAAAA88D0006788870788687888760000899AAAAAAAA
AAAAAAAA97D00006788887788778888760000089AAAAAAAA
AAAAAAAA88D00006788888888888888750000088AAAAAAAA
AAAAAAAA99800006688877788778888760000899AAAAAAAA
AAAAAAAAA998000788887578864788877000899AAAAAAAAA
AAAAAAAAAA99800A47887668866788739009A9AAAAAAAAAA
AAAAAAAAAAA99800678888888888887600999AAAAAAAAAAA
AAAAAAAAAAAA998AD67888888888875C0899AAAAAAAAAAAA
AAAAAAAAAAAAAA80AC577888888776CA68AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA998C8A776677A8D899AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA997C000000C899AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA989B9AC989AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA9999AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}

!define MSIMG_AZURECOGNATIVESERVICESCOMPUTERVISIONCOLOR_G <img:../sprites/Cloud/Azure_Cognative_Services_Computer_Vision_COLOR_gray.png>
!define MSIMG_AZURECOGNATIVESERVICESCOMPUTERVISIONCOLOR_C <img:../sprites/Cloud/Azure_Cognative_Services_Computer_Vision_COLOR.png>
@enduml