@startuml
sprite $azuresearchcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFEDBBBDDEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFDBBBBBBBBBBEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEBBBBBBBBBBBBBDEFFFFFFFFFF
FFFFFFFFFFFFFFEEFFFFFDBBBBBBBBBBBBBBBBEFFFFFFFFF
FFFFFFFFFFEDBBBBBDEFDBBBBBBBBBBBBBBBBBBEFFFFFFFF
FFFFFFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFFFF
FFFFFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFF
FFFFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFFF
FFFFFFEBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFFFF
FFFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFF
FFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFF
FFFFFEBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFF
FFFFFEBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFF
FFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFF
FFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFF
FFFDBBBBBBBBBBBBBBBBBBAAAAABBBBBBBBBBBBBBBBBBFFF
FFDBBBBBBBBBBBBBBBBA976644678ABBBBBBBBBBBBBBBBFF
FDBBBBBBBBBBBBBBBB9644444444447ABBBBBBBBBBBBBBDF
EBBBBBBBBBBBBBBBA8444444444444469BBBBBBBBBBBBBBE
DBBBBBBBBBBBBBBB744444689976444448BBBBBBBBBBBBBD
BBBBBBBBBBBBBBB844447BDEEEEDA644449BBBBBBBBBBBBB
BBBBBBBBBBBBBB944449DEEEEEEEFE84446ABBBBBBBBBBBB
BBBBBBBBBBBBBB74449EEEEEEEEFFFE74448BBBBBBBBBBBB
BBBBBBBBBBBBB94447DEEEEEEEFFFFFD6446ABBBBBBBBBBB
DBBBBBBBBBBBB8444BEEEEEEFFFFFFFF94449BBBBBBBBBBB
EBBBBBBBBBBBB6446DEEEEEEFFFFFFFFD4448BBBBBBBBBBE
FBBBBBBBBBBBA6447EEEEEEFFFFFFFFFE6447BBBBBBBBBBF
FEBBBBBBBBBBA6448EEEEEFFFFFFFFFFE7446BBBBBBBBBEF
FFDBBBBBBBBBA6448EEEEFFFFFFFFFFFE6446BBBBBBBBDFF
FFFDBBBBBBBBA6447EEEEFFFFFFFFFFFE6447BBBBBBBBFFF
FFFFEBBBBBBBB7444BEEFFFFFFFFFFFFB4448BBBBBBDFFFF
FFFFFFDBBBBBB84449EEFFFFFFFFFFFF74449BBBBDEFFFFF
FFFFFFFFEEEEED6444BFFFFFFFFFFFFB4447DEEEFFFFFFFF
FFFFFFFFFFFFFF94446DFFFFFFFFFFB6444BFFFFFFFFFFFF
FFFFFFFFFFFFFD444446BFFFFFFFFB64449FFFFFFFFFFFFF
FFFFFFFFFFFFD644444448BEEEDB744447EFFFFFFFFFFFFF
FFFFFFFFFFFD644444444444664444447EFFFFFFFFFFFFFF
FFFFFFFFFFD644444444444444444449EFFFFFFFFFFFFFFF
FFFFFFFFFD644444449D8644444468DFFFFFFFFFFFFFFFFF
FFFFFFFFD64444444AFFFEBB99ABEFFFFFFFFFFFFFFFFFFF
FFFFFFFD64444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFD64444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFD64444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF74444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFD4444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFE4444449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF844449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFE866AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURESEARCHCOLOR_G <img:../sprites/Cloud/Azure_Search_COLOR_gray.png>
!define MSIMG_AZURESEARCHCOLOR_M <img:../sprites/Cloud/Azure_Search_COLOR_mono.png>
!define MSIMG_AZURESEARCHCOLOR_C <img:../sprites/Cloud/Azure_Search_COLOR.png>
@enduml