@startuml
sprite $azurecortonamanagementsuite [48x48/16] {
FFFFFFFFFFFFFFFFFFEDDBBBBBBDDEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDBBBBBBBBBBBBBBDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEBBBBBBBBBBBBBBBBBBBBEFFFFFFFFFFFFF
FFFFFFFFFFFEBBBBBB987664466789BBBBBBEFFFFFFFFFFF
FFFFFFFFFFDBBBBA7644444444444467ABBBBDFFFFFFFFFF
FFFFFFFFFBBBBA74444444444444444447ABBBBFFFFFFFFF
FFFFFFFEBBBB844444444444444444444448BBBBEFFFFFFF
FFFFFFEBBBA6444444468BBBBBA8644444446ABBBEFFFFFF
FFFFFFBBB944444449DFFFFFFFFFFD944444449BBBFFFFFF
FFFFFBBB94444449EFFFFFFFFFFFFFFE94444449BBBFFFFF
FFFFDBBA444446BFFFFFFFFFFFFFFFFFFB644444ABBDFFFF
FFFEBBB644447EFFFFFFFFFFFFFFFFFFFFE744446BBBEFFF
FFFBBB844447EFFFFFFFFFFFFFFFFFFFFFFE744447BBBFFF
FFEBBA44446EFFFFFFFFFFFFFFFFFFFFFFFFE64444ABBEFF
FFBBB74444BFFFFFFFFFFFFFFFFFFFFFFFFFFB44446BBBFF
FEBBA44449FFFFFFFFFFFFFFFFFFFFFFFFFFFF944449BBEF
FDBB74444EFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44447BBDF
FBBB44449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94444ABBF
EBB94444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD44449BBE
DBB84446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF64447BBD
DBB64448FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94446BBD
BBB6444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB4446BBB
BBB4444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB4444BBB
BBA4444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD4444ABB
BBA4444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD4444ABB
BBB4444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB4444BBB
BBB6444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB4446BBB
DBB64448FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94446BBD
DBB74446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF64447BBD
EBB94444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD44449BBE
FBBA44449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94444ABBF
FDBB74444EFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64447BBDF
FEBB944449FFFFFFFFFFFFFFFFFFFFFFFFFFFF944449BBEF
FFBBB64444BFFFFFFFFFFFFFFFFFFFFFFFFFFD44446BBBFF
FFEBB944446EFFFFFFFFFFFFFFFFFFFFFFFFE644449BBEFF
FFFBBB744447EFFFFFFFFFFFFFFFFFFFFFFE744447BBBFFF
FFFEBBA644447EFFFFFFFFFFFFFFFFFFFFE744446ABBEFFF
FFFFDBB9444446BFFFFFFFFFFFFFFFFFFD6444449BBDFFFF
FFFFFBBB94444449EFFFFFFFFFFFFFFEA4444449BBBFFFFF
FFFFFEBBB944444449DFFFFFFFFFFEA64444449BBBEFFFFF
FFFFFFEBBB96444444469BDDDDB97444444449BBBEFFFFFF
FFFFFFFEBBBA744444444444444444444447ABBBEFFFFFFF
FFFFFFFFEBBBB9644444444444444444469BBBBEFFFFFFFF
FFFFFFFFFFDBBBB964444444444444469BBBBDFFFFFFFFFF
FFFFFFFFFFFEBBBBBA976444444678ABBBBBEFFFFFFFFFFF
FFFFFFFFFFFFFEBBBBBBBBAAAABBBBBBBBEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDBBBBBBBBBBBBBBDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEDDBBBBBBDDEFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURECORTONAMANAGEMENTSUITE_G <img:../sprites/Cloud/Azure_Cortona_Management_Suite_gray.png>
!define MSIMG_AZURECORTONAMANAGEMENTSUITE_M <img:../sprites/Cloud/Azure_Cortona_Management_Suite_mono.png>
!define MSIMG_AZURECORTONAMANAGEMENTSUITE_C <img:../sprites/Cloud/Azure_Cortona_Management_Suite.png>
@enduml