@startuml
sprite $azuresqlstretchdatabasecolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEEEEEEEFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEDBBBBBBBBBDEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEBBBBBBBBBBBBBBDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEDBBBBBBBBBBBBBBBBDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFEBBBBBBBBBBBBBBBBBBBDFFFFFFFFFFFFFFF
FFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBDFFFFFFFFFFFFFF
FFFFFFFFFFFEDDDBBBBBBBBBBBBBBBBBBBEFFFFFFFFFFFFF
FFFFFFEDDDBDDEEEEDBBBBBBBBBBBBBBBBDFFFFFFFFFFFFF
FFFDB9988888889ABEFDBBBBBBBBBBBBBBBFFFFFFFFFFFFF
FFB888888888888889EFDBBBBBBBBBBBBBBEFFEEEFFFFFFF
FFB888776666677889EFDBBBBBBBBBBBBBBDDBBBBBDFFFFF
BEFD964444444447BEFDABBBBBBBBBBBBBBBBBBBBBBBEFFF
AADEFEDBBBBBBDEFFEB79BBBBBBBBBBBBBBBBBBBBBBBBEFF
A99ABDDEEEEEEDBA87769BBBBBBBBBBBBBBBBBBBBBBBBDFF
A9999999AA87777777769BBBBBBBBBBBBBBBBBBBBBBBBBEF
A99999999976777777769BBBBBBB97ABBBBBBBBBBBBBBBDF
A99999999976777777769BBBBBBB9679BBBBBBBBBBBBBBDF
A99999999976777777769BBBBBBB96778BBBBBBBBBBBBBDF
A999999999767777777778777778777768BBBBBBBBBBBBDF
A9999999997677777777766666667777767ABBBBBBBBBBDF
A99999999976777777777777777777777768BBBBBBBBBBEF
A9999999997677777777666666666777778BBBBBBBBBBDFF
A999999999767777777789999999877779BBBBBBBBBBBEFF
A99999999976777777769BBBBBBB96679BBBBBBBBBBBBEFF
A99999999976777777769BBBBBBB967ABBBBBBBBBBBBBBDE
A99999999976777777769BBBBBBB98BBBBBBBBBBBBBBBBBD
A99999999976777777769BBBBBBBBBBBBBBBBBBBBBBBBBBB
A99999999976777777769BBBBBBBBBBBBBBBBBBBBBBBBBBB
A99999999976777777769BBBBBBBBBBBBBBBBBBBBBBBBBBD
A99999999976777777769BBBBBBBBBBBBBBBBBBBBBBBBBDF
B9999999997677777777ABBBBBBBBBBBBBBBBBBBBBBBDEFF
EB99999999767777778BEEEEEEEEEEEEEEEEEEEEEEEFFFFF
FFEBBA99997777779BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFEEDDDBBBBDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURESQLSTRETCHDATABASECOLOR_G <img:../sprites/Cloud/Azure_SQL_Stretch_Database_COLOR_gray.png>
!define MSIMG_AZURESQLSTRETCHDATABASECOLOR_M <img:../sprites/Cloud/Azure_SQL_Stretch_Database_COLOR_mono.png>
!define MSIMG_AZURESQLSTRETCHDATABASECOLOR_C <img:../sprites/Cloud/Azure_SQL_Stretch_Database_COLOR.png>
@enduml