@startuml
sprite $azurebiztalkserviceshybridconnections [48x48/16] {
FFFFFFFFFFFFFFFFFFFEA744469DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEA4444444448EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD6444444444444BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE644448BBB964444BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFD4448EFFFFFEA4444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF96BFFFFFFFFFB4447FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFDBBEFFFB444DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF94446DFFF7449FFFFFFFFFFFFFF
FFFFFFFFFEEEEEEEFFFF9444446EFFB446FFFFFFFFFFFFFF
FFFFFFB8644444447EFE4444444BFFD444ABBBBBDFFFFFFF
FFFFD644444444444BFD44444449FFE44444444446BFFFFF
FFFB4444444444446EFE4444444AFFE4444444444447EFFF
FFB44449BDEEEEEEEFFF8444444DFFB44467777644447FFF
FE6446DFFFFFFFFFFFFFE64444BFFF8448FFFFFFD7444AFF
FB444DFFFFFFFFFFFFFFFEB89DFFFD444BFFFFFFFE7444EF
F8448FFFFFFFFFFFBAEFFFFFFFFFE7446EFFFFFFFFD444BF
F744AFFFFFFFFFFE446BFFFFFFFD7444BFFFFFFFFFF8448F
F644BFFFFFFFFFFD44448BEEED944449FFFFFFFFFFFA447F
F644BFFFFFFFFFFFA44444464444448FFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFB64444444444BFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFEB7444446AEFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFEDBDEFFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFFFFEDDDEFFFFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFFEA6444447BEFFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFFFB64444444446BFFFFFFFFFFFFB446F
F644BFFFFFFFFFFFF94444444444444BFFFFFFFFFFFB446F
F744AFFFFFFFFFFF944449DEEEB84444DFFFFFFFFFFB446F
F8448FFFFFFFFFFB4447DFFFFFFFB644DFFFFFFFFFFB447F
FB444DFFFFFFFFE6446EFFFFFFFFFEABFFFFFFFFFFF8448F
FE6447EFFFFFFFB444DFFFB88AEFFFFFFFFFFFFFFFB444BF
FFB4447DFFFFFF8448FFFA44446DFFFFFFFFFFFFFB6446EF
FFF84444677777444BFFD4444447FFFEDDDDDDDB84444BFF
FFFE8444444444444DFFA4444444EFE6444444444444BFFF
FFFFFB64444444444EFF94444444DFB444444444447DFFFF
FFFFFFFDBAAAA9444DFFB4444444EFE8666666669BFFFFFF
FFFFFFFFFFFFFF644BFFE644444AFFFFEEEEEEFFFFFFFFFF
FFFFFFFFFFFFFF9447FFFD74449FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD444BFFFFDBEFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF7444BFFFFFFFFFB69FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFD4444AEFFFFFE9444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB444469BBB844446EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB4444444444446DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFD84444444449EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD964447AEFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONS_G <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_Connections_gray.png>
!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONS_M <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_Connections_mono.png>
!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONS_C <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_Connections.png>
@enduml