@startuml
sprite $azurevpngatewaycolor [48x48/16] {
000000000000000C8AABBCCCCCCBAAA9C000000000000000
0000000000000BDAABCCCCCCCCCCCCBAADB0000000000000
00000000000D9AACCCCCCCCCCCCCCCCCCAA9D00000000000
0000000000B8ABCCCCCCCCCCCCCCCCCCCCBA8B0000000000
000000000C9ACCCCCCCCCCCCCCCCCCCCCCCCA9B000000000
0000000009ABCCCCCCCCCCCCCCCCCCCCCCCCBA9000000000
00000000ABBCCCCCCCCCCCCCCCCCCCCCCCCCCBAA00000000
0000000B9ACCCCCCCCCCBAAA9AABCCCCCCCCCCA9C0000000
0000000AABCCCCCCCCBAA8C00D9AABCCCCCCCCBA90000000
00000009ACCCCCCCCBA9C000000D9ABCCCCCCCCA9D000000
000000A7BCCCCCCCBA900000000009ABCCCCCCCB0A000000
000000AABCCCCCCCA8B0000000000C9ACCCCCCCCAA000000
0000009ACCCCCCCCA9000000000000AABCCCCCCCA9000000
0000009ACCCCCCCBBA000000000000A8BCCCCCCCA9000000
0000009ACCCCCCCB8C00000000000009ACCCCCCCA9000000
0000009BCCCCCCCA9000000000000009ACCCCCCCA9000000
0000009BCCCCCCCA9000000000000009ACCCCCCCA9000000
000BBAABCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCBAAAA000
00AABCDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCBAA00
0ACBDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBA0
0AACDDDDDDDDDDDDDDDDDDDCDDDDDDDCCCCCCCCCCCCCCA90
09BDDDDDDDDDDDDDDDDDDDCBBDDDDDCCCCCCCCCCCCCCCA90
09BDDDDDDDDDDDDDDDDDDCBADBDDDDCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDDDCBACBDBDDCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDDCBAC00BDBCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDCBAAAA9AAABCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDDCCCAA8BCCCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDCCDDDDDDDAA8BDCCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDCBCDDDDDDAA7BCCCCCCBACCCCCCCCCCCB90
09BDDDDDDDDDDCABCDDDDDBAABCCCCCBAACCCCCCCCCCCB90
09BDDDDDDDDDDCA9BCDDDDCCCCCCCCBA9ACCCCCCCCCCCB90
09BDDDDDBBBBBAAA8BCDDDDDCCCCCBA99AAAAAABCCCCCB90
09BDDDDCAA000000A9BDDDDCCCCCCA900000009BCCCCCB90
09BDDDDCA6BBBBBBAACDDDDCCCCCCA7A0000009BCCCCCB90
09BDDDDDCCCCCBAAACDDDDCCCCCCCCA799BBBBBCCCCCCB90
09BDDDDDDDDDDCAACDDDDCCBBCCCCCCA9ACCCCCCCCCCCB90
09BDDDDDDDDDDCACDDDDDCADDBCCCCCCAACCCCCCCCCCCB90
09BDDDDDDDDDDCCDDDDDCCA97BCCCCCCCBCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDDDCCA97BCCCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDCBBBA97BBBBCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDCB0DDDDD7BBCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDDCCB5B00ABBCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDDCCCCB5BABBCCCCCCCCCCCCCCCCCCB90
09BDDDDDDDDDDDDDCCCCCCB7BBCCCCCCCCCCCCCCCCCCCB90
0ABDDDDDDDDDDDDDCCCCCCCBBCCCCCCCCCCCCCCCCCCCCA90
0AACDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA0
0B9BCDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB6B0
00ACBCDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBAA00
}

!define MSIMG_AZUREVPNGATEWAYCOLOR_G <img:../sprites/Cloud/Azure_VPN_Gateway_color_gray.png>
!define MSIMG_AZUREVPNGATEWAYCOLOR_C <img:../sprites/Cloud/Azure_VPN_Gateway_color.png>
@enduml