@startuml
sprite $azureapimanagementcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEDDBBBBDDEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEBBBBBBBBBBBBDEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEBBBBBBBBBBBBBBBBDFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFDBBBBBDEEFFFEEBBBBBBEFFFFFFFFFF
FFFFFFFFFFFFFFFFDBBBBEFFFFFFFFFFEDBBBBEFFFFFFFFF
FFFFFFFFFFFFFFFDBBBDFFFFFFFFFFFFFFEBBBBFFFFFFFFF
FFFFFFFFFFFFFFEBBBDFFFFFFFFFFFFFFFFEBBBBFFFFFFFF
FFFFFFFFFFFFFFBBBDFFFFFFFFFFFFFFFFFFEBBBEFFFFFFF
FFFFFFFFFFEEFEBBBFFFFFFFFFFFFFFFFFFFFDBBBFFFFFFF
FFFFFFEDBBBBBBBBDFFFFFFFFFFFFFFFFFFFFFBBBEFFFFFF
FFFFEBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFDBBDFFFFFF
FFFEBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFEBBBFFFFFF
FFEBBBBBEFFFFEEEFFFFFFFFFFFFFFFFFFFFFFFBBBFFFFFF
FFBBBBDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBEFFFFF
FDBBBEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBEFFFFF
EBBBDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBEFFFFF
DBBBEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBEFFFFF
BBBBFFFFFFFFFFFFFFEEDBBDEEFFFFFFFFFFFFEBBBBDEFFF
BBBDFFFFFFFFFFFFEBBBBBBBBBBEFFFFFFFFFFDBBBBBBEFF
BBBDFFFFFFFFFFFFEBBBBBBBBBBBDFFFFFFFFFBBBBBBBBDF
BBBDFFFFFFFFFFFFFBBBBBBBBBBBBBFFFFFFFFFFFFEBBBBE
BBBBFFFFFFFFFFFFFEDEFFFFFDBBBBDFFFFFFFFFFFFEBBBB
DBBBEFFFFFFFFFFFFFFFFFFFFFFBBBBDFFFFFFFFFFFFDBBB
EBBBDFFFFFFFFFFFFFFB977AEFFFBBBBFFFFFFFFFFFFDBBB
FDBBBEFFFFFFFFFFFF9444444BFFEBBBDFFFFFFFFFFFBBBB
FEBBBBEFFFFFFFFFF944444444DFFDBBBFFFFFFFFFFEBBBD
FFEBBBBDEFFFFFFFE4444444447FFEBBBEEEEEEEEEDBBBBE
FFFEBBBBBBBBBBBB94444444444EFFBBBBBBBBBBBBBBBBEF
FFFFEBBBBBBBBBBB74444444444DFFBBBBBBBBBBBBBBBDFF
FFFFFFEBBBBBBBBB84444444444EFFBBBBBBBBBBBBBDEFFF
FFFFFFFFFEEEEEEEB4444444447FFEBBBEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF944444444BFFDBBBFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE8444444BFFFBBBDFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB8679DFFFDBBBFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFDBBBDFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEDFFFFFFEBBBBBFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFBBBBDDDBBBBBBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBBBBBBBBBBBBEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBBBBBBBBBBDFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEDBBBBDEFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREAPIMANAGEMENTCOLOR_G <img:../sprites/Cloud/Azure_API_Management_COLOR_gray.png>
!define MSIMG_AZUREAPIMANAGEMENTCOLOR_M <img:../sprites/Cloud/Azure_API_Management_COLOR_mono.png>
!define MSIMG_AZUREAPIMANAGEMENTCOLOR_C <img:../sprites/Cloud/Azure_API_Management_COLOR.png>
@enduml