@startuml
sprite $azuredocumentdbdocdbcollections1 [48x48/16] {
FFFFFFFB444444444444444444444444444444BFFFFFFFFF
FFFFFFFA4688888888888888888888888888864BFFFFFFFF
FFFFFFFA4AFFFFFFFFFFFFFFFFFFFFFFFFFFFB44BFFFFFFF
FFFFFFFA4AFFFFFFFFFFFFFFFFFFFFFFFFFFFB444BFFFFFF
FFFFFFFA4AFFFFFFFFFFFFFFFFFFFFFFFFFFFB4444BFFFFF
FFD88886468888888888888888888888AEFFFB44444BFFFF
FFB4466666666666666666666666666648EFFB444444BFFF
FFB4DFEEEEEEEEEEEEEEEEEEEEEEEEEE847EFD9999974BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFF9447EFFFFFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFF94447EFFFFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFF944447EFFFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFF9444447EFFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFF94444447EFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDD74DFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFFFDBDFFFFFFFFA79DFFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFD6449FFFFFFFF7444DFFFFFFFF74DFFA4BFF
FFB4DFFFFFFD4444AFFFFFFFF94448FFFFFFFF74DFFA4BFF
FFB4DFFFFFFA446DFFFFFFFFFFD646FFFFFFFF74DFFA4BFF
FFB4DFFFFFF844AFFFFFFFFFFFF846FFFFFFFF74DFFA4BFF
FFB4DFFFFFF744BFFFFFFFFFFFF946FFFFFFFF74DFFA4BFF
FFB4DFFFFFF744BFFFFFFFFFFFF946FFFFFFFF74DFFA4BFF
FFB4DFFFFFF744BFFFFFFFFFFFF946FFFFFFFF74DFFA4BFF
FFB4DFFFFFF744BFFFFFFFFFFFFA44EFFFFFFF74DFFA4BFF
FFB4DFFFFFD444EFFFFFFFFFFFFB448DFFFFFF74DFFA4BFF
FFB4DFFFFD4449FFFFFFFFFFFFFF8444DFFFFF74DFFA4BFF
FFB4DFFFFB447EFFFFFFFFFFFFFFD644AFFFFF74DFFA4BFF
FFB4DFFFFE9448FFFFFFFFFFFFFE7446BFFFFF74DFFA4BFF
FFB4DFFFFFF844DFFFFFFFFFFFFB446EFFFFFF74DFFA4BFF
FFB4DFFFFFFA44BFFFFFFFFFFFFA449FFFFFFF74DFFA4BFF
FFB4DFFFFFFB44BFFFFFFFFFFFF944AFFFFFFF74DFFA4BFF
FFB4DFFFFFFB44BFFFFFFFFFFFF944AFFFFFFF74DFFA4BFF
FFB4DFFFFFFB44BFFFFFFFFFFFF944AFFFFFFF74DFFA4BFF
FFB4DFFFFFFB44AFFFFFFFFFFFF944AFFFFFFF74DFFA4BFF
FFB4DFFFFFFB446EFFFFFFFFFEB644BFFFFFFF74DFFA4BFF
FFB4DFFFFFFE6446DFFFFFFFFB4446EFFFFFFF74DFFA4BFF
FFB4DFFFFFFFE976DFFFFFFFFB669DFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFFFFEEFFFFFFFFFEFFFFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74BEEA4BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7446644BFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7478888DFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74DFFFFFFF
FFB4788888888888888888888888888888888844DFFFFFFF
FFB4444444444444444444444444444444444444EFFFFFFF
}

!define MSIMG_AZUREDOCUMENTDBDOCDBCOLLECTIONS1_G <img:../sprites/Cloud/Azure_DocumentDB_DocDB_collections_1_gray.png>
!define MSIMG_AZUREDOCUMENTDBDOCDBCOLLECTIONS1_M <img:../sprites/Cloud/Azure_DocumentDB_DocDB_collections_1_mono.png>
!define MSIMG_AZUREDOCUMENTDBDOCDBCOLLECTIONS1_C <img:../sprites/Cloud/Azure_DocumentDB_DocDB_collections_1.png>
@enduml