@startuml
sprite $azurevirtualmachinesavailabilitysetcolor [48x48/16] {
ABCCCCCC999BCCCCCBD9ACCCCCCB99BCCCCCB999CCCCCCBA
BCCCCCCC999BCCCCCCD9ACCCCCCB99BCCCCCB999CCCCCCCB
CCCCCCCC999BCCCCCCD9ACCCCCCB99BCCCCCB999CCCCCCCC
CCCCCCCC999BCCCCCCD9ACCCCCCB99BCCCCCB999CCCCCCCC
CCCCCCCB999BCCCCCBD9ABCCCCCA99BCCCCCB999BCCCCCCC
CCCCC9999999999999D99999999A999999999999999CCCCC
CCCCC99000000000000000000000000000000000099CCCCC
CCCCB99000000000000000000000000000000000099BCCCC
9999999AABBBBBBBBBBBBBBBBBBBBBBBBBAAA00009999999
000000ABCDDDDDDDDDDDDDDDDDDDDDDDDCCA9C0000000000
AAAAAAABDDDDDDDDDDDDDDDDDDDDDDDDCCCB4C0009999999
BBBBB9ABDDCCCCCCCCCCCCCCCCCCCCCCCCCB0C00099BBBBB
CCCCC9ABDDCCCCCCCCCCCBBCCCCCCCCCCCCB0C00099CCCCC
CCCCC9ABDDCCCCCCCCCCBAABCCCCCCCCCCCBAAAAA99CCCCC
CCCCC9ABDDCCCDDDDDDDCCCCDDDDDDDDDDDDCCCAD99CCCCC
CCCCC9ABDDCCDDDDDDDDDDDDDDDDDDDDDDDDDCCCA99CCCCC
CCCCC9ABDDCCDDDCCCCCCCCCCCCCCCCCCCCCCCCCA99CCCCC
BCCCB9ABDDCCDDDCCCCCCCCCCCCCCCCCCCCCCCCCA99BBBBB
CCCCCCABDDCCDDDCCCCCCCCCCBABCCCCCCCCCCCCAA000000
000000ABDDCCDDDCCCCCCCCBA4BDABCCCCCCCCCCAA000000
AAAAA9ABDDCCDDDCCCCCCCADB000ACACCCCCCCCCA99AAAAA
CCCCC9ABDDCCDDDCCCCCCDBABA0AAABCCCCCCCCCA99CCCCC
CCCCC9ABDDCCDDDCCCCCDEDCBADABCDDDCCCCCCCA99CCCCC
CCCCC9ABDDCCDDDCCCCCDFFEDCBCDDEEDCCCCCCCA99CCCCC
CCCCC9ABDDCCDDDCCCCCDFFFFECDEEEEDCCCCCCCA99CCCCC
CCCCC9ABDDCCDDDCCCCCDFFFFFDEEEEEDCCCCCCCA99CCCCC
CCCCC9ABDDDDDDDCCCCCDFFFFEDEEEEEDCCCCCCCA99CCCCC
ABBBAAAACDDDDDDCCCCCDEFFFEDEEEEDCCCCCCCCA9AABBBA
000000B8BCBBCDDCCCCCCDEFFFDEEEDCCCCCCCCCAA000000
0000000CDA8CBDDCCCCCCCCDEEDDDDCCCCCCCCCCAA000000
BBBBB9900009BDDCCCCCCCCCCDCDCCCCCCCCCCCCA99BBBBB
CCCCC9900009BDDCCCCCCCCCCCCCCCCCCCCCCCCCA99CCCCC
CCCCC9900009BDDDCCCCCCCCCCCCCCCCCCCCCCCCA99CCCCC
CCCCC990000ABDDCCCCCCCCCCCCCCCCCCCCCCCCBB99CCCCC
CCCCC990000ABAAAAAAAAAABBBBBBBAAAAAAAAAAA99CCCCC
CCCCC990000000000000089AAAAAAA8800000000099CCCCC
CCCCB9900000000000008B9AAAAAAA9790000000099BCCCC
BBBBBAA0000000099AAAAABBBBBBBBBAAAA990000AABBBBB
0000000000000009ABCCCCCCCCCCCCCCCCC9900000000000
AAAAA990000000099AAAAAAAAAAAAAAAAAA99000099AAAAA
CCCCB99000000000000000000000000000000000099BCCCC
CCCCC99000000000000000000000000000000000099CCCCC
CCCCC9999999999999D99999999A979999999B99999CCCCC
CCCCCCCB999BCCCCCBD9ABCCCCCA97BCCCCCBB99BCCCCCCC
CCCCCCCC999BCCCCCCD9ACCCCCCB97BCCCCCCB99CCCCCCCC
CCCCCCCC999BCCCCCCD9ACCCCCCB97BCCCCCCB99CCCCCCCC
BCCCCCCC999BCCCCCCD9ACCCCCCB97BCCCCCCB99CCCCCCCB
ABCCCCCC999BCCCCCBD9ACCCCCCB97BCCCCCCB99CCCCCCBA
}

!define MSIMG_AZUREVIRTUALMACHINESAVAILABILITYSETCOLOR_G <img:../sprites/Cloud/Azure_Virtual_Machines_Availability_Set_COLOR_gray.png>
!define MSIMG_AZUREVIRTUALMACHINESAVAILABILITYSETCOLOR_C <img:../sprites/Cloud/Azure_Virtual_Machines_Availability_Set_COLOR.png>
@enduml