@startuml
sprite $azureappserviceworkerpoolscolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFEDBBDFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEBBBBBBEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEBBBBBBBBEFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEBBBBBBBBBBEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEBBBBBBBBBBBBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBBBBBBBBBBBBBBEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEBBBBBBB88BBBBBBBEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEBBBBB99966998BBBBBEFFFFFFFFFFFFFF
FFFFFFFFFFFFFEBBBBBA66666644ABBBBBEFFFFFFFFFFFFF
FFFFFFFFFFFFEBBBBBBB76677446BBBBAABEFFFFFFFFFFFF
FFFFFFFFFFFEBBBBBBA9768AA7449ABAAAABEFFFFFFFFFFF
FFFFFFFFFFEBBBBBBB9666AAB94449BAAAAABEFFFFFFFFFF
FFFFFFFFFEBBBBBBBBA8669AA7447AAAAAAAABEFFFFFFFFF
FFFFFFFFEBBBBBBBBBBB76676446BBAAAAAAAABEFFFFFFFF
FFFFFFFEBBBBBBBBBBBA66444444AAAAAAAAAAABEFFFFFFF
FFFFFFEBBBBBBBBBBBBA88744887AAAAAAAAAAAABEFFFFFF
FFFFFEBBBBBBBBBBBBBBBBB66BBAAAAAAAAAAAAAABEFFFFF
FFFFEBBBBBBBBBBBBBBBBBBAABBAAAAAAAAAAAAAAABEFFFF
FFFEBBBBBB9ABBBBBBBBBBBBBBAAAAAAAAAAA9AAAAABEFFF
FFEBBBBABA67BAABBBBBBBBBBAAAAAAAAAAA968AAAAABEFF
FEBBBBA77766866ABBBBBBBBBAAAAAAAA977767747AAABEF
EBBBBBA76666446BBBBBBBBBAAAAAAAAA966666448AAAABE
DBBBBBA76799646ABBBBBBBAAAAAAAAAA966898448AAAAAB
BBBBB97669BB84449BBBBBBAAAAAAAAA8667AAA6446AAAAB
BBBBB9766ABB84449BBBBBAAAAAAAAAA8667AAA6446AAAAB
DBBBBBA76798446ABBBBBAAAAAAAAAAAA966897448AAAAAB
EBBBBBA66444446BBBBBBAAAAAAAAAAAA966444448AAAABE
FEBBBBA77444646ABBBBAAAAAAAAAAAAA867444647AAABEF
FFEBBBBAB946BAABBBBAAAAAAAAAAAAAAAAA847AAAAABEFF
FFFEBBBBBB89BBBBBBBAAAAAAAAAAAAAAAAAA89AAAABEFFF
FFFFEBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAABAAAABEFFFF
FFFFFEBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAABEFFFFF
FFFFFFEBBBBBBBBBBAAAAAA77AAAAAAAAAAAAAAABEFFFFFF
FFFFFFFEBBBBBBBBAAAA77866876AAAAAAAAAAABEFFFFFFF
FFFFFFFFEBBBBBBAAAAA76666644AAAAAAAAAABEFFFFFFFF
FFFFFFFFFEBBBBBAAAAA76798646AAAAAAAAABEFFFFFFFFF
FFFFFFFFFFEBBBAAAA97669BB84469AAAAAABEFFFFFFFFFF
FFFFFFFFFFFEBAAAAA96669AB94448AAAAABEFFFFFFFFFFF
FFFFFFFFFFFFEBAAAAA9768996449AAAAABEFFFFFFFFFFFF
FFFFFFFFFFFFFEBAAAAA76444446AAAAABEFFFFFFFFFFFFF
FFFFFFFFFFFFFFEBAAAA764444449AAABEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEBAAA9A944999AAABEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBAAAAA88AAAAABEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEBAAAAAAAAAABEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEBAAAAAAAABEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEBAAAAAABEFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEBAAAABEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEBBBBEFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREAPPSERVICEWORKERPOOLSCOLOR_G <img:../sprites/Cloud/Azure_App_Service_Worker_Pools_COLOR_gray.png>
!define MSIMG_AZUREAPPSERVICEWORKERPOOLSCOLOR_M <img:../sprites/Cloud/Azure_App_Service_Worker_Pools_COLOR_mono.png>
!define MSIMG_AZUREAPPSERVICEWORKERPOOLSCOLOR_C <img:../sprites/Cloud/Azure_App_Service_Worker_Pools_COLOR.png>
@enduml