@startuml
sprite $azurecognativeservicesweblanguagemodelcolor [48x48/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA99999AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA9890CD7A89AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA9DA000000A789AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA998D897777870899AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA9988977888877878A9AAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA887878888888877688AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA968B7888888888878779AAAAAAAAAAAAA
AAAAAAAAAAAAAAA88578888888888887499AAAAAAAAAAAAA
AAAAAAAAAAAAAA9D8B788888888888888769AAAAAAAAAAAA
AAAAAAAAAAAAAA9767888877888788887678AAAAAAAAAAAA
AAAAAAAAAAAAAA9766888778888778886578AAAAAAAAAAAA
AAAAAAAAAAAAAA9756887788888877886578AAAAAAAAAAAA
AAAAAAAAAAAAAA9766888778888778886678AAAAAAAAAAAA
AAAAAAAAAAAAAA9588888887888788887778AAAAAAAAAAAA
AAAAAAAAAAAAAAA995788888888888870979AAAAAAAAAAAA
AAAAAAAAAAAAAAA8778888888888888769D9AAAAAAAAAAAA
AAAAAAAAAAAAAAA99867888888888876989AAAAAAAAAAAAA
AAAAAAAAAAAAAAAA959677888888775AB79AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA94A9B767777A80089AAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA9A90000000000969AAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA986A0000000C78AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA95A000000089AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA9980000000899AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA998000000A889AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA9996B000000A69AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA9898D0000000899AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA96A000000009D89AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA8700000009A89AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA87C00C09899AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA9988999AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}

!define MSIMG_AZURECOGNATIVESERVICESWEBLANGUAGEMODELCOLOR_G <img:../sprites/Cloud/Azure_Cognative_Services_web_language_model_COLOR_gray.png>
!define MSIMG_AZURECOGNATIVESERVICESWEBLANGUAGEMODELCOLOR_C <img:../sprites/Cloud/Azure_Cognative_Services_web_language_model_COLOR.png>
@enduml