@startuml
sprite $azurestreamanalyticscolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFEBBBBEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFA6666BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF866668FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFD666666DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDEFFFFFFB666666AFFFFFFEBDFFFFFF
FFFFFFFFFFFFFFFE867BEFFFD76666667DFFFEB767DFFFFF
FFFFFFFFFFFFFFE866667AB866666666668BB766646DFFFF
FFFFFFFFFFFFFF966666666666666666666666664448FFFF
FFFFFFFFFFFFFFB6666789AA9876666666666664444BFFFF
FFFFFFFFFFFFFFF87ADEFFFFFFEB966666666644447FFFFF
FFFFFFFFFFFFFFFEEFFEEDDDDEEFFE966666644444BFFFFF
FFFFFFFFFFFFFFFFFEBBBBBBBBBBEFFB7666444447FFFFFF
FFFFFFFFFFFFFFFEBBBBBDDDDBBBBBEFE864444448FFFFFF
FFFFFFFFFFFFFFEBBBDEFFFFFFFDBBBEFE84444444EFFFFF
FFFFFEEFFFFFFDBBBEFFFFFFFFFFFDBBEFE7444444AFFFFF
FFFFFBBDFFFFDBBDFFFEBBAABDEFFFDBBFFD44444448BEFF
FFFFFEBBBBBBBBDFFEB99999999BEFFEEFFF74444444447A
FFFEFFEBBBBBBEFFD999BDEEDB99AEFFFFFFA44444444444
FFE9BFFFEEEEFFFD99BEFFFFFFEB9AEFFFFFB44444444444
FFEA9AEFFFFFFEB99BFFFFEEFFFFB9EFFFFFB44444444444
FFFEA99BDDEDB999DFFEA7667AEFFEFFFFFF944444444446
BEFFFBA9999999BEFFD74678646BFFFFFFFF6444444448BE
76DFFFEDBBBBDEFFFD648DFFEA66EFFFFFFB4444446BEFFF
D66BFFFFFFFFFFFFB648EFFFFFBBFFFFFFE6444444BFFFFF
FD748DFFFFFFFFD9649EFFB8BFFFFFFFFD64444446EFFFFF
FFE9667ABDBBA8646BFFE94449EFFFFEB444444448FFFFFF
FFFFB86444444469EFFE8444444788744444444446EFFFFF
FFFFFFEBA989ABEFFFB744444444444444444444449FFFFF
FFFFFFFFFFFFFFFEB86444444444444444444444444EFFFF
FFFFFFFFFFFFFFF96644444444444444444444444448FFFF
FFFFFFFFFFFFFFE66444444444444444444444444446FFFF
FFFFFFFFFFFFFFFA444446A84444444444499644444DFFFF
FFFFFFFFFFFFFFFF9446BEFFE84444444AEFFEB744DFFFFF
FFFFFFFFFFFFFFFFF9AEFFFFFD4444446FFFFFFFBDFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF744444AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFA44444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFD44446FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFA999BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURESTREAMANALYTICSCOLOR_G <img:../sprites/Cloud/Azure_Stream_Analytics_COLOR_gray.png>
!define MSIMG_AZURESTREAMANALYTICSCOLOR_M <img:../sprites/Cloud/Azure_Stream_Analytics_COLOR_mono.png>
!define MSIMG_AZURESTREAMANALYTICSCOLOR_C <img:../sprites/Cloud/Azure_Stream_Analytics_COLOR.png>
@enduml