@startuml
sprite $azurecacheincludingrediscolor [48x48/16] {
000000000000000000000000000000000000000000000000
0000000000CDBBBBBBBBBBBABDC000000000000000000000
000000BBBBBCCDDDDDDDDDDDDCCBBBB00000000000000000
0000AABCDDEEEEEEEEEEEEEEEEEDDCBAAD00000000000000
00DABCDEEEEEEEEEEEEEEEEEEEEEEEDCBAB0000000000000
00BBCEEEEEEEEEEEEEEEEEEEEEEEEEEECAA0000000000000
BBBBDEEEEEEEEEEEEEEEEEEEEEEEEEEEDAABBBB000000000
A99ABDEEEDDDDDDDDDCDDDDDDDDDEEEDBAAABAB000000000
AABABBCDDCCCCCCCCCCCCCCCCCCCDDCBAA0BBBB000000000
ABA96ABAABCCCCCCCCCCCCCCCCCBAAAA9ABCBDB000000000
ABBB99A9ABAAAAABBBBBBBBAAAAAABDAABCCBDB000000000
ABBBBBA999DB0000000000000C8AAABCCCCCBDB000000000
ABBBBBBBBAA9999999AAAAAAAABBCCCCCCCCBDB000000000
ABBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCBDB000000000
ABBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCBDB000000000
ABBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCBDB000000000
ABBBBBBBBBBBBBBBBBCCCCCCCCCCCBBAAAAAABBDD0000000
ABBBBBBBBBBBBBBBBBCCCCCCCCBABBCCCDDDDDCCBBBDB000
ABBBBBBBBBBBBBBBBBCCCCCCBABCDDEEEEEEEEEEEDDCBAC0
ABBBBBBBBBBBBBBBBBCCCCCCABDEEEEEEEEEEEEEEEEEDBAD
ABBBBBBBBBBBBBBBBBCCCCCB9BDEEEDDDDDDDDDDDEEEDB9A
ABBBBBBBBBBBBBBBBBCCCCCB85BDDDCCCCCCCCCCCDDCB899
ABBBBBBBBBBBBBBBBBCCCCCB988BAABBCCCCCCCBBAAC99A9
ABBBBBBBBBBBBBBBBBCCCCCB999877BCBAAAAABCB889AAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999998888999999AAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB9999999999AAAAAAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999AAAAAAABAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999AAAAAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999AAAA99AAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999AAA999AAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999AA9D9AAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999999A949AAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB999999999998659AAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999988789AAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999888C79999AAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999998C90CBA9A9AAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB9999998777A9C899AAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999980978AAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB9999999998709AAAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB9999999986A9AAAAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999999888AAAAAAAAAAAA9
ABBBBBBBBBBBBBBBBBCCCCCB99999998889AAAAAAAAAAAA9
9BBBBBBBBBBBBBBBBBCCCCCB99999988999AAAAAAAAAAAA9
AABBBBBBBBBBBBBBBBCCCCCB99999989999AAAAAAAAAAAA9
99ABBBBBBBBBBBBBBBCCCCCBA9999999999AAAAAAAAAAAA9
09B9ABBBBBBBBBBBBBCCCCCCBA99A999999AAAAAAAAAAA9A
000AB99AABBBBBBBBBCCCCCCCCBA9999999AAAAAAAAA98B9
000000AB999AABBBBBCCCCCCBBB98899999AAAAA9989CA00
}

!define MSIMG_AZURECACHEINCLUDINGREDISCOLOR_G <img:../sprites/Cloud/Azure_Cache_including_Redis_COLOR_gray.png>
!define MSIMG_AZURECACHEINCLUDINGREDISCOLOR_C <img:../sprites/Cloud/Azure_Cache_including_Redis_COLOR.png>
@enduml