@startuml
sprite $azurebiztalkserviceshybridconnectionmanager [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEBA88789BDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD864444444447BEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE8444444444444446BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB4444444444444444448EFFFFFFFFFFF
FFFFFFFFFFFFFFFA444444444444444444446EFFFFFFFFFF
FFFFFFFFFFFFFFB44444444444444444444446EFFFFFFFFF
FFFFFFFFFFFFFB444444446ABDDDB844444444AFFFFFFFFF
FFFFFFFFFFFFE64444446BFFFFFFFFE84444449FFFFFFFFF
FFFFFFFFFFFF94444447EFFFFFFFFFFFB44444BFFFFFFFFF
FFFFFFFFFFFE4444447EFFFFFFFFFFFFFB644AFFFFFFFFFF
FFFFFFFFFFFA444444EFFFFD9778BFFFFFEDEFFFFFFFFFFF
FFFFFFFFFFF744444AFFFFA4444447EFFFFFFFFFFFFFFFFF
FFFFFFFFFFE444444EFFFA444444446EFFFFFFFFFFFFFFFF
FDA99999997444448FFFE4444444444AFFFFD99999999ADF
B444444444444444AFFFA44444444446EFFB44444444444B
6444444444444444BFFF844444444444DFE6444444444446
4444444444444444BFFF844444444444DFE4444444444444
9444444444444444AFFF944444444444EFF7444444444447
E8444444444444448FFFD44444444448FFFD64444444447E
FFDBBBBBBBB444446EFFF9444444444DFFFFEBBBBBBBBBEF
FFFFFFFFFFF744444BFFFE84444444BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFA444446EFFFFB74469EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFE4444447EFFFFFEEEFFFFFD89DFFFFFFFFFFF
FFFFFFFFFFFF94444447EFFFFFFFFFFFB4444BFFFFFFFFFF
FFFFFFFFFFFFE64444446BFFFFFFFFD8444447FFFFFFFFFF
FFFFFFFFFFFFFB444444446ABEEDB844444446FFFFFFFFFF
FFFFFFFFFFFFFFA44444444444444444444449FFFFFFFFFF
FFFFFFFFFFFFFFFA444444444444444444447EFFFFFFFFFF
FFFFFFFFFFFFFFFFB4444444444444444448EFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD8444444444444446BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD844444444446BEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEBA87789BDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONMANAGER_G <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_connection_manager_gray.png>
!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONMANAGER_M <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_connection_manager_mono.png>
!define MSIMG_AZUREBIZTALKSERVICESHYBRIDCONNECTIONMANAGER_C <img:../sprites/Cloud/Azure_BizTalk_Services_Hybrid_connection_manager.png>
@enduml