@startuml
sprite $azurestreamanalytics [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFB6666DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF844449FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFE444446EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFA444444BFFFFFFEEFFFFFFF
FFFFFFFFFFFFFFFFB69DFFFFE64444448FFFFFB64BFFFFFF
FFFFFFFFFFFFFFFB44448BD96444444447BEB74444BFFFFF
FFFFFFFFFFFFFFD4444444444444444444444444446EFFFF
FFFFFFFFFFFFFFE4444444664444444444444444448FFFFF
FFFFFFFFFFFFFFFA448BDEFFEEB964444444444444DFFFFF
FFFFFFFFFFFFFFFEAEFFDBBBBDFFEB644444444447FFFFFF
FFFFFFFFFFFFFFFFFE9644444469DFE9444444444BFFFFFF
FFFFFFFFFFFFFFFE944468AA974449EFB44444444EFFFFFF
FFFFFFFFFFFFFFD6449DFFFFFFE9446EFD6444444AFFFFFF
FFFFFFBDFFFFFD647EFFFFFFFFFFD646EFE4444446EFFFFF
FFFFFE44BFFEB449FFFD97667ADFFE74BFFA4444446ADFFF
FFFFFF944676449FFE8444444449EFEAEFFE4444444446AF
FFFEBFFB64446BFFB446ADEEB9446EFFFFFF74444444444E
FFF94AFFFEDEFFFB44AEFFFFFFE747FFFFFF84444444444E
FFFD448DFFFFFE944BFFFEDDEFFE87FFFFFF84444444444E
FFFFD64479AA8444BFFD744447DFFFFFFFFF74444444447E
E8BFFEA64444448DFFB44689744AFFFFFFFD444444468BEF
E64BFFFEDBAABEFFFB449EFFFB47FFFFFFF8444444BEFFFF
FD449EFFFFFFFFFE944AFFFEFFDDFFFFFFB4444449FFFFFF
FFD646ADFFFFFEA644BFFE849FFFFFFFFA4444444DFFFFFF
FFFE9444677764447DFFE74446BEEEEB744444444EFFFFFF
FFFFFEA64444468BFFFD644444446644444444444BFFFFFF
FFFFFFFFEDDDEEFFFE944444444444444444444446EFFFFF
FFFFFFFFFFFFFFFE94444444444444444444444444BFFFFF
FFFFFFFFFFFFFFF9444444444444444444444444446FFFFF
FFFFFFFFFFFFFFF844444464444444444447444444AFFFFF
FFFFFFFFFFFFFFFE74447DFD944444444AEFE9644AFFFFFF
FFFFFFFFFFFFFFFFE87BFFFFFA444444BFFFFFEBBFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFD444444EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF644447FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF94444BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFD8888EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURESTREAMANALYTICS_G <img:../sprites/Cloud/Azure_Stream_Analytics_gray.png>
!define MSIMG_AZURESTREAMANALYTICS_M <img:../sprites/Cloud/Azure_Stream_Analytics_mono.png>
!define MSIMG_AZURESTREAMANALYTICS_C <img:../sprites/Cloud/Azure_Stream_Analytics.png>
@enduml