@startuml
sprite $azureappservicemobileappcolor [48x48/16] {
FFFFFFFFD866666666666666666666666444446DFFFFFFFF
FFFFFFFE76666666666666666666666644444446EFFFFFFF
FFFFFFFB66666666666BEEEEEEEEB66644444444BFFFFFFF
FFFFFFFB666666666669BBBBBBBB966444444444AFFFFFFF
FFFFFFFB66666666666666666666666644444444AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAABDDBAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAABBEFFEBBAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAABEFFFFFFEBAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAABDFFFFFFFFFFDBAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAABDFFFFFFFFFFFFFFDBAAAAA64AFFFFFFF
FFFFFFFB67AAAAABFFFFFFFFFFFFFFFFBAAAAA64AFFFFFFF
FFFFFFFB67AAAAAABEFFFFFFFFFFFFEBAAAAAA64AFFFFFFF
FFFFFFFB67AAAABBABBEFFFFFFFFFDBABBAAAA64AFFFFFFF
FFFFFFFB67AAABDEDBABDFFFFFFDBABBBBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEBBABEFFEBAABBDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEDBAABBAABBDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEDBAABBBDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEEEBBBDDDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEEEBBBDDDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEEEBBBDDDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEEEBBBDDDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAABDEEEEEEEEBBBDDDDDDDBAAAA64AFFFFFFF
FFFFFFFB67AAAABEEEEEEEEBBBDDDDDDBBAAAA64AFFFFFFF
FFFFFFFB67AAAAABDEEEEEEBBBDDDDBBBAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAABDEEEEBBBDDDBBAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAABBEEEBBBDBBBAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAABDEBBBBBAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAABBABAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB67AAAAAAAAAAAAAAAAAAAAAAAAAAAA64AFFFFFFF
FFFFFFFB66888888887777777777777777777744AFFFFFFF
FFFFFFFB66666666644444444444444444444444AFFFFFFF
FFFFFFFB66666666444444699644444444444444AFFFFFFF
FFFFFFFB66666666444446EEEE64444444444444AFFFFFFF
FFFFFFFB6666666644444BEBBEB4444444444444AFFFFFFF
FFFFFFFB6666666444444BEBBDB4444444444444AFFFFFFF
FFFFFFFB66666664444449EDDE94444444444444AFFFFFFF
FFFFFFFB66666644444444AEEA44444444444444BFFFFFFF
FFFFFFFE76666644444444444444444444444446EFFFFFFF
FFFFFFFFD866664444444444444444444444446BFFFFFFFF
}

!define MSIMG_AZUREAPPSERVICEMOBILEAPPCOLOR_G <img:../sprites/Cloud/Azure_App_Service_Mobile_App_COLOR_gray.png>
!define MSIMG_AZUREAPPSERVICEMOBILEAPPCOLOR_M <img:../sprites/Cloud/Azure_App_Service_Mobile_App_COLOR_mono.png>
!define MSIMG_AZUREAPPSERVICEMOBILEAPPCOLOR_C <img:../sprites/Cloud/Azure_App_Service_Mobile_App_COLOR.png>
@enduml