@startuml
sprite $azureiothub [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEAAAAAAAAAAAAEF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB444444444444AF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB444444444444AF
FFFFFFFFFFFFFFFFFEA778DFFFFFFFFFFB444444444444AF
FFFFFFFFFFFFFFFFE744444BFFFFFFFFFB444444444444AF
FFFFFFFFFFFFFFFF84444444EFFFFFFFFD444444444444AF
FFFFFFFFFFFFFFFE44444444BFFFFFFFFFEDDDDEB44444AF
FFFFFFFFFFFFFFFD444444449FFFFFFFFFFFFFFFD44444AF
FFFFFFFFFFFFFFFE44444444AFFFFFFFFFFFFFFFD44444AF
FFFFFFFFFFFFFFFF84444444DFFFFFFFFFFFFFFFD44444AF
FFFFFFFFFFFFFFFFE6444446FFFFFFFFFFFFFFFFD44444AF
FFFFFFFFFFFFFFFFFEA76744BFFFFFFFFFFFFFFFD44444AF
FFFFFFFFFFFFFFFFFFFFFF744DFFFFFFFFFFFFFFE64444BF
FFFFFFFFFFFFFFFFFFFFFFE447EFFFFFFFFFFFFFFEDDDDFF
FFFFFFFFFFFFFFFFFFFFFFFB449FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF844BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFE646B99ADFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFB4444444AFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFE44444444AFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF9444444444EFFFFFFFFFFFF
FFFFFFB878DFFFFFFFFFFFFED6444444444BFFFFFFFFFFFF
FFFFFB44444BEDDBBA98766444444444444AFFFFFFFFFFFF
FFFFF644444444444444444444444444444BFFFFFFFFFFFF
FFFFE4444444444667889ABBD7444444444DFFFFFFFFFFFF
FFFFE4444446DEEEFFFFFFFFFD444444449FFFFFFFFFFFFF
FFFFF944444BFFFFFFFFFFFFFF64444444EFFFFFFFFFFFFF
FFFFFE8444AFFFFFFFFFFFFFFB44877844AFFFFFFFFFFFFF
FFFFFFFEDEFFFFFFFFFFFFFFE647FFFF844EFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFA44DFFFFD448FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFD449FFFFFF944DFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFED746EFFFFFFE647FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB6444BFFFFFFFFB44BFFFFFFFFFF
FEBBBBDFFFFFFFFFFFFB444449FFFFFFFFF746DEFFFFFFFF
FA44444EFFFFFFFFFFF7444446EFFFFFFFFB44446BFFFFFF
FA44444DFFFFFFFFFFF6444444EFFFFFFFFB444444DFFFFF
FA44444DFFFFFFFFFFF8444446EFFFFFFFF74444448FFFFF
FA44444DFFFFFFFFFFFD44444BFFFFFFFFE44444446EFFFF
FA44444DFFFFFFFFFFFFD867BFFFFFFFFFE44444446EFFFF
FA44444DFFFFFFFFFFFFFFFFFFFFFFFFFFF64444448FFFFF
FA44444BBBBBBDFFFFFFFFFFFFFFFFFFFFFB444444DFFFFF
FA444444444444BFFFFFFFFFFFFFFFFFFFFFB6447DFFFFFF
FA444444444444BFFFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFF
FA444444444444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FA444444444444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FA444444444444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FEBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREIOTHUB_G <img:../sprites/Cloud/Azure_IoT_Hub_gray.png>
!define MSIMG_AZUREIOTHUB_M <img:../sprites/Cloud/Azure_IoT_Hub_mono.png>
!define MSIMG_AZUREIOTHUB_C <img:../sprites/Cloud/Azure_IoT_Hub.png>
@enduml