@startuml
sprite $azureapimanagement [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFDBA989ABEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEA64444444448BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFA444444444444447DFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE744444444444444444AFFFFFFFFFFF
FFFFFFFFFFFFFFFFD6444447ABDDDB96444449FFFFFFFFFF
FFFFFFFFFFFFFFFD644448DFFFFFFFFEB644449FFFFFFFFF
FFFFFFFFFFFFFFE64446BFFFFFFFFFFFFE94444AFFFFFFFF
FFFFFFFFFFFFFF84446EFFFFFFFFFFFFFFFA4444DFFFFFFF
FFFFFFFFFFFFFB4446EFFFFFFFFFFFFFFFFFA4447FFFFFFF
FFFFFFFFDBAAA6444BFFFFFFFFFFFFFFFFFFF7444BFFFFFF
FFFFFEA6444444448FFFFFFFFFFFFFFFFFFFFD4448FFFFFF
FFFFB64444444444DFFFFFFFFFFFFFFFFFFFFF8444EFFFFF
FFFB444444444446FFFFFFFFFFFFFFFFFFFFFFB444BFFFFF
FFB44446ADEEEB8AFFFFFFFFFFFFFFFFFFFFFFE444AFFFFF
FD44448EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6449FFFFF
F84449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7448FFFFF
D4447FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7448FFFFF
A444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7448FFFFF
7446FFFFFFFFFFFFFFFFEEEFFFFFFFFFFFFFFFE64448BFFF
4448FFFFFFFFFFFFEB8644468BEFFFFFFFFFFFD4444449FF
4449FFFFFFFFFFFE64444444446BFFFFFFFFFFA4444444AF
4448FFFFFFFFFFFF7444444444448EFFFFFFFFB9BA74444D
6446FFFFFFFFFFFFD46ABDBB744448FFFFFFFFFFFFFA4448
9444DFFFFFFFFFFFFDFFFFFFFD64449FFFFFFFFFFFFF7446
D4447FFFFFFFFFFFFFFFFFFFFFE7444BFFFFFFFFFFFFA444
F7444AFFFFFFFFFFFFFB7668DFFE6447FFFFFFFFFFFF9444
FD4444AFFFFFFFFFFE8444444BFFB444DFFFFFFFFFFE6446
FFA44446BEFFFFFFF944444444DFF644AFFFFFFFFFE8444A
FFFA44444466667774444444449FF944699999888864446E
FFFFB4444444444444444444446FFB4444444444444444DF
FFFFFE944444444444444444446FFB444444444444447DFF
FFFFFFFEBA98888884444444448FFA4446777777779BFFFF
FFFFFFFFFFFFFFFFF744444444BFF8447FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE64444449FFE444AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE84446BFFF9444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEDDFFFFB4448FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFA4444DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF9BEFFFEB74444BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB444677644444BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE644444444446BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB6444444469EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFDB989ABEFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZUREAPIMANAGEMENT_G <img:../sprites/Cloud/Azure_API_Management_gray.png>
!define MSIMG_AZUREAPIMANAGEMENT_M <img:../sprites/Cloud/Azure_API_Management_mono.png>
!define MSIMG_AZUREAPIMANAGEMENT_C <img:../sprites/Cloud/Azure_API_Management.png>
@enduml