@startuml
sprite $azureservicefabriccolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFEDBAAABEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFDBAAA9878DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFDAAAAA97778BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEAAAAAA877778DFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFBAAAAAA877777AFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEAAAAAA98777778EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDAAAAAA97777777DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDAAAAAA97777777BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDAAAAAA87777777BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEAAAAA987777777DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE99AAAA9877777776DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD8689AAA97777777444BFFFFFFFFFFFFFF
FFFFFFEEEFFFFB77778AAA877777764444AFFFFEEEFFFFFF
FFFFDBAAABBEB77777ABAA877778B8444449EB98889BEFFF
FFEBAAAAAAAA87777BFFEB9889BEFF944444877777779DFF
FEAAAAAAAAAA9867BFFFFFFEEFFFFFFB44477777777778EF
FBAAAAAAAAAAA98DFFFFFFFFFFFFFFFFB67777777777779F
DAAAAAAAAAAAAABFFFFFFFFFFFFFFFFFFB7777777777777B
BAAAAAAAAAAAAABFFFFFFFFFFFFFFFFFFA7777777777777A
AAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFF877777777777778
AAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFE877777777777778
BAAAAAAAAAAAAABFFFFFFFFFFFFFFFFFF977777777777779
BAAAAAAAAAAAAABFFFFFFFFFFFFFFFFFFA7777777777777B
EAAAAAAAAAAAAAEFFFFFFFFFFFFFFFFFFD8777777777778E
FDAAAAAAAAAAABFFFFFFFFFFFFFFFFFFFFA77777777777BF
FFBAAAAAAAAABFFFFFFFFFFFFFFFFFFFFFEA777777777AFF
FFFDAAAAAAABFFFFFFFFFFFFFFFFFFFFFFFFB8777778BFFF
FFFFEDA988BFFFFFFFFFFFFFFFFFFFFFFFFFF86668BEFFFF
FFFFFFB7769FFFFFFFFFFFFFFFFFFFFFFFFFE6444BFFFFFF
FFFFFFD7777EFFFFFFFFFFFFFFFFFFFFFFFFD4444EFFFFFF
FFFFFFF8777DFFFFFFFFFFFFFFFFFFFFFFFFA4447FFFFFFF
FFFFFFFA777AFFFFFFFFFFFFFFFFFFFFFFFF7444AFFFFFFF
FFFFFFFB7668EFFFFFFFFFFFFFFFFFFFFFFD4444DFFFFFFF
FFFFFFFE7789AABBEFFFFFFFFFFFFFFEB9886646FFFFFFFF
FFFFFFFFA9AAAAAAABFFFFFFFFFFFFB877777779FFFFFFFF
FFFFFFFDAAAAAAAAA8AFFFFFFFFFFA7777777778BFFFFFFF
FFFFFFEAAAAAAAAA987BFFFFFFFFB777777777778EFFFFFF
FFFFFFBAAAAAAAAA9778EFFFFFFE8777777777777AFFFFFF
FFFFFFAAAAAAAAAA9777BEEEEEEB77777777777778EFFFFF
FFFFFEAAAAAAAAAA87776444444677777777777778EFFFFF
FFFFFEAAAAAAAAA987776444444677777777777777DFFFFF
FFFFFEAAAAAAAAA977776444444677777777777778EFFFFF
FFFFFFAAAAAAAAA977776444444677777777777778EFFFFF
FFFFFFBAAAAAAAA87779EEEEEEEE9777777777777BFFFFFF
FFFFFFEAAAAAAAA8777BFFFFFFFFB777777777778EFFFFFF
FFFFFFFEAAAAAA9877BFFFFFFFFFFB7777777778DFFFFFFF
FFFFFFFFEBAAAA978BFFFFFFFFFFFFB87777779DFFFFFFFF
FFFFFFFFFFDBAAABEFFFFFFFFFFFFFFEB9889BEFFFFFFFFF
}

!define MSIMG_AZURESERVICEFABRICCOLOR_G <img:../sprites/Cloud/Azure_Service_Fabric_COLOR_gray.png>
!define MSIMG_AZURESERVICEFABRICCOLOR_M <img:../sprites/Cloud/Azure_Service_Fabric_COLOR_mono.png>
!define MSIMG_AZURESERVICEFABRICCOLOR_C <img:../sprites/Cloud/Azure_Service_Fabric_COLOR.png>
@enduml