@startuml
sprite $azurevirtualmachineslinuxpenguinshadowcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFEA74469DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB64444444AFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD44444446748FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF844444446444BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE4444444444446FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFD4444444444444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB4464444886444AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB4BD844BEEB4448FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB7AAD47E8AE6448FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFD776B68B44D7449FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFD697BBBB67D6448FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE49BDDDDDDB4446FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE6BDDDDEDDB4444EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE7BDDDDDBDB4444BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE79BDDBBBBB64767FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE6BBBBBBDEFA4444BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFA4EDAABDFFFE64447FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD49FFDDEFFFFFA4444AFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE66EFFFFFFFFFFE44444DFFFFFFFFFFF
FFFFFFFFFFFFFFFF84AFFFFFFFFFFFF744446EFFFFFFFFFF
FFFFFFFFFFFFFFFB44BFFFFFFFFFEDEB444449FFFFFFFFFF
FFFFFFFFFFFFFFE646BFFFFFFFFEDBBD644444BFFFFFFFFF
FFFFFFFFFFFFFFA44BFFFFFFFFFFFFEDA444447FFFFFFFFF
FFFFFFFFFFFFFE647EFFFFFFFFFFFFFFD644444BFFFFFFFF
FFFFFFFFFFFFFB44BFFFFFFFFFFFFFFFF9444447FFFFFFFF
FFFFFFFFFFFFF847FFFFFFFFFFFFFFFFFB444444DFFFFFFF
FFFFFFFFFFFFE44AFFFFFFFFFFFFFFFFFE4444449FFFFFFF
FFFFFFFFFFFF944BFFFFFEFFFFFFFFFFFE4444447FFFFFFF
FFFFFFFFFFFD446EFFFFFEFFFFFFFFFFFE6444444EFFFFFF
FFFFFFFFFFF9446EFFFFFEFFFFFFFFFFFE6444444EFFFFFF
FFFFFFFFFFF9447EFFFFFEFFFFFFFFFFFE6444446EFFFFFF
FFFFFFFFFFFDBB7DFFFFFEFFFFFFFFFFFD6444448FFFFFFF
FFFFFFFFFFFEEEB7BFFFFEFFFFFFFFFFED644447DFFFFFFF
FFFFFFFFFFDDEEEA4BFFFFFFFFFFFFFEDD64444BEFFFFFFF
FFFFFFFEDBDEEEED849FFFFFFFFFFFFDDD9646BDEFFFFFFF
FFFFFFDDDDDEEEEEB648EFFFFFFFFFFBBDBAABDEEEFFFFFF
FFFFFFDDEEEEEEEEDA449FFFFFFFFFFBBDDDDDEEEEEFFFFF
FFFFFFDDEEEEEEEEED749FFFFFFFFFE9BDDDDDEEEEEEFFFF
FFFFFBBDEEEEEEEEEEBBEFFFFFFFFF96BDEEEEEEEEEEEFFF
FFFFB4AEEEEEEEEEEEDDEFFFFFFFD847BDEEEEEEEEEDFFFF
FFFD44BDEEEEEEEEEEDDADEEEDB84448BDEEEEEEEDA7DFFF
FFFA44BDDDDDEEEEEEDD946644444449DDEEEEEDB644AFFF
FFFA447ABBBDDDDDDDDB944444444449BDDDDDB744449FFF
FFFD44444678ABBDDDBB744444444448BBBBB9644444BFFF
FFFFA4444444468ABBA74444444444469AAA84444449FFFF
FFFFFB644444444467644444444444444666444444BFFFFF
FFFFFFEB744444444444448BD964444444444446AEFFFFFF
FFFFFFFFFDB876444679BEFFFFEB9764444679BEFFFFFFFF
}

!define MSIMG_AZUREVIRTUALMACHINESLINUXPENGUINSHADOWCOLOR_G <img:../sprites/Cloud/Azure_Virtual_Machines_Linux_Penguin_shadow_COLOR_gray.png>
!define MSIMG_AZUREVIRTUALMACHINESLINUXPENGUINSHADOWCOLOR_M <img:../sprites/Cloud/Azure_Virtual_Machines_Linux_Penguin_shadow_COLOR_mono.png>
!define MSIMG_AZUREVIRTUALMACHINESLINUXPENGUINSHADOWCOLOR_C <img:../sprites/Cloud/Azure_Virtual_Machines_Linux_Penguin_shadow_COLOR.png>
@enduml