@startuml
sprite $azurecontainerservicecolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFEBDDBEFFFFFFFFFFFFBBEBEFFFFFFFFFFFFFF
FFFFFFFFFB8449B468BEFFFFFFD9648D448BEFFFFFFFFFFF
FFFFFFFF867ABAB444469DFFF8479D9D444468BFFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFE88BBDAB444446AFFF97BBE9D444446AFFFFFFFFF
FFFFFFFFB74679B4468BFFFFFB74488D4448BEFFFFFFFFFF
FFFFFFFFFFEA4AB7BEFFFFFFFFFEA48D7AEFFFFFFFFFFFFF
FFFB8AE9BEFFFEFFFFFFB8AE9BEFFFEFFFFFEB7BD9BFFFFF
D94468D4469DFFFFFD94468D4469DFFFFFB8446AB446ADFF
779BD9D444446AFFF86ABD9D444446AFFE779BBAB444447A
BADBD9D4444444EFFBADBD9D4444444EFEBBBDBAB4444444
BADBD9D4444444EFFBADBD9D4444444EFEBBBDBAB4444444
BADBD9D4444444EFFBADBD9D4444444EFEBBBDBAB4444444
BADBD9D4444444EFFBADBD9D4444444EFEBBBDBAB4444444
BADBD9D4444444EFFBADBD9D4444444EFEBBBDBAB4444444
BADBD9D4444446EFEBADBD9D4444446EFEBBBDBAB4444444
769BD9D444468BFFF869BD9D444468BFFE769BBAB444469D
EB7468D447BEFFFFFEB7468D447BEFFFFFEB644AB447BEFF
FFFD9BEADFFFFFFFFFFFE9AEADFFFFFFFFFFFD8BDADFFFFF
FFFFFFFFFFEA6AB7ADFFFFFFFFFEB69D7ADFFFFFFFFFFFFF
FFFFFFFFB74689B4447BEFFFFB74688D4447ADFFFFFFFFFF
FFFFFFFE88BBDAB4444448FFF97BBE9D4444448EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444446EFFBADBD9D4444444EFFFFFFFF
FFFFFFFEBABBDAB4444447EFFBADBD9D4444446EFFFFFFFF
FFFFFFFF847ABAB44447BEFFF8479D9D44447AEFFFFFFFFF
FFFFFFFFFB8449B469DFFFFFFFD8448D469DFFFFFFFFFFFF
FFFFFFFFFFFEABDBEFFFFFFFFFFFEBBEBEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_AZURECONTAINERSERVICECOLOR_G <img:../sprites/Cloud/Azure_Container_Service_COLOR_gray.png>
!define MSIMG_AZURECONTAINERSERVICECOLOR_M <img:../sprites/Cloud/Azure_Container_Service_COLOR_mono.png>
!define MSIMG_AZURECONTAINERSERVICECOLOR_C <img:../sprites/Cloud/Azure_Container_Service_COLOR.png>
@enduml