@startuml
sprite $logicappscolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFEDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDEFFFF
FFFBA99BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB99ABFFF
FFD9999BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD9999DFF
FFB99AEFFFFFFFFFFFFFDBBBBBBEFFFFFFFFFFFFFEA99BFF
FFB99BFFFFFFFFFFFFFB44444448FFFFFFFFFFFFFFB99AFF
FFA99DFFFFFFFFFFFFF744444444EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFF744BBB744EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFF746FFF944EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFF746FFF944EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFF746DDD844EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFF744444444EFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFFA44444447FFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFFFBA7679AEFFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFFFFFB9AFFFFFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFFFFFB9AFFFFFFFFFFFFFFFFFD99AFF
FFA99DFFFFFFFFFFFFFFFFB9AFFFFFFFFFFFFFFFFFD99AFF
FEA99EFFFFFFFFFFFFFFFFA9AEFFFFFFFFFFFFFFFFE99AEF
EB99AFFFFFFFFFFFFFEEBA999ABDEFFFFFFFFFFFFFFB99BE
A99AEFFFFFFFFFFFDAA999ABA9999ABDFFFFFFFFFFFEA99A
999AEFFFFFFFFFEA999ABBEFEBAA9999BFFFFFFFFFFEA999
EB99BFFFFFFFFFB99BDEFFFFFFFEEBB99BFFFFFFFFFA99BE
FEA99EFFFFFFFE99DFFFFFFFFFFFFFFB99EFFFFFFFE999EF
FFA99DFFFFFFFD9AFFFFFFFFFFFFFFFFA9DFFFFFFFD99AFF
FFA99DFFFFFFFD9AEFFFFFFFFFFFFFFFA9DFFFFFFFD99AFF
FFA99DFFFFFBA999ABEFFFFFFFFFFFBB99ABDFFFFFD99AFF
FFA99DFFFFE9899999BFFFFFFFFFFB9999989EFFFFD99AFF
FFA99DFFFFD9999999AFFFFFFFFFFA9999999DFFFFD99AFF
FFA99DFFFFD9999999AFFFFFFFFFFA9999999DFFFFD99AFF
FFA99DFFFFD9999999AFFFFFFFFFFA9999999DFFFFD99AFF
FFA99DFFFFD9999999AFFFFFFFFFFA9999999DFFFFD99AFF
FFA99DFFFFD9999998AFFFFFFFFFFA9999999DFFFFD99AFF
FFA99DFFFFFA999999DFFFFFFFFFFB9999999EFFFFD99AFF
FFA99DFFFFFFEDDDDEFFFFFFFFFFFFDBBBBDEFFFFFD99AFF
FFB99BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB99BFF
FFB99AEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA99BFF
FFD9999DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9999DFF
FFFBA99BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB99ADFFF
FFFFEDBEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBDEFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_LOGICAPPSCOLOR_G <img:../sprites/Cloud/Logic_Apps_COLOR_gray.png>
!define MSIMG_LOGICAPPSCOLOR_M <img:../sprites/Cloud/Logic_Apps_COLOR_mono.png>
!define MSIMG_LOGICAPPSCOLOR_C <img:../sprites/Cloud/Logic_Apps_COLOR.png>
@enduml