@startuml
sprite $logicapps [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFDBABFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBABEFFFF
FFF94448FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94449FFF
FFB44449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA4444BFF
FF8444BFFFFFFFFFFFFFDBBBBBBEFFFFFFFFFFFFFD6447FF
FF6449FFFFFFFFFFFFFB44444447FFFFFFFFFFFFFF9446FF
FF644AFFFFFFFFFFFFF744444444EFFFFFFFFFFFFFA446FF
FF644AFFFFFFFFFFFFF744BBB744DFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFF746FFF944DFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFF746FFF944DFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFF744DDD844DFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFF744444444EFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFFA44444447FFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFFFBA6449AEFFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFFFFF746EFFFFFFFFFFFFFFFFB446FF
FF644AFFFFFFFFFFFFFFFF746EFFFFFFFFFFFFFFFFB446FF
FF644BFFFFFFFFFFFFFFFF746EFFFFFFFFFFFFFFFFB446EF
FD444BFFFFFFFFFFFFFFFE644DFFFFFFFFFFFFFFFFB444DF
B7446EFFFFFFFFFFFFEB9644449BDFFFFFFFFFFFFFE6447B
4444DFFFFFFFFFFEA64444484444468BFFFFFFFFFFFD6444
4446DFFFFFFFFFD6444469DFE96444447EFFFFFFFFFD6444
B7446EFFFFFFFF7448BEFFFFFFFEB96448FFFFFFFFE6447B
FD444BFFFFFFFB44BFFFFFFFFFFFFFF944DFFFFFFFB444DF
FF644BFFFFFFFB44EFFFFFFFFFFFFFFE44BFFFFFFFB446EF
FF644AFFFFFFFA44EFFFFFFFFFFFFFFE64AFFFFFFFB446FF
FF644AFFFFF9644467DFFFFFFFFFFE974467BFFFFFB446FF
FF644AFFFFB44444447FFFFFFFFFF84444444DFFFFB446FF
FF644AFFFFB44444446FFFFFFFFFF64444444BFFFFB446FF
FF644AFFFFB44444446FFFFFFFFFF64444444BFFFFB446FF
FF644AFFFFB44444446FFFFFFFFFF64444444BFFFFB446FF
FF644AFFFFB44444446FFFFFFFFFF64444444BFFFFB446FF
FF644AFFFFB44444447FFFFFFFFFF64444444BFFFFB446FF
FF644AFFFFE6444444BFFFFFFFFFF94444444DFFFFB446FF
FF644AFFFFFEBBBBBDFFFFFFFFFFFFBAAAAADFFFFFA446FF
FF6449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9446FF
FF8446DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6448FF
FFB4444AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94444BFF
FFF94448FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8444AFFF
FFFFEB9BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9BEFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_LOGICAPPS_G <img:../sprites/Cloud/Logic_Apps_gray.png>
!define MSIMG_LOGICAPPS_M <img:../sprites/Cloud/Logic_Apps_mono.png>
!define MSIMG_LOGICAPPS_C <img:../sprites/Cloud/Logic_Apps.png>
@enduml