@startuml
sprite $networksecuritygroupcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEAAEFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEA99AEFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEB999999BEFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDB999999999ABDEFFFFFFFFFFFFFFFF
FFFFFFFFFEEEEDBBA999999BA999999ABBDEEEEFFFFFFFFF
FFFFFFDAAAA99999999999BDBA999999999999999DFFFFFF
FFFFFFB9999999999999ABEEBBA99999999888888BFFFFFF
FFFFFFB9999999999ABBDEEEBBBBAA99998888888BFFFFFF
FFFFFFB999ABBBBBDDEEEEEEBBBBBBBBAA9999888BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADEEEEEEEEEEEEEBBBBBBBBBBBBBA988BFFFFFF
FFFFFFB99ADBBDEEEDBDEEDA889BBBA98889BA988BFFFFFF
FFFFFFB99AD748EEEB4BEB64446BBA644444AA988BFFFFFF
FFFFFFB99AD744BEEB4BE64BBA9BA647AA98AA988BFFFFFF
FFFFFFB99AD7666DEB4BE66DBBBB847BBBBBBA988BFFFFFF
FFFFFFB99AD76B49EB4BE9469ABB64ABAAAAAA988BFFFFFF
FFFFFFB999B66B84BA4ADB8446BB64BB9444AB988BFFFFFF
FFFFFFB999B66BB66849BBBA847D74BEDA74BD988BFFFFFF
FFFFFFB999B66BB94649BBBBE84BA49EEEA4BD988BFFFFFF
FFFFFFB999B66BBB7449B89AB64DD649BB84BD988BFFFFFF
FFFFFFB999B66BBBA649A64444AEEB744446BD988BFFFFFF
FFFFFFB999BAABBBBA9ABA99BDEEEEDBBBBDED988BFFFFFF
FFFFFFB999BBBBBBBBBBBBBBEEEEEEEEEEEEED988BFFFFFF
FFFFFFB999BBBBBBBBBBBBBBDEEEEEEEEEEEED988BFFFFFF
FFFFFFD999ABBBBBBBBBBBBBDEEEEEEEEEEEEB888BFFFFFF
FFFFFFE999ABBBBBBBBBBBBBDEEEEEEEEEEEDA888DFFFFFF
FFFFFFFA999ABBBBBBBBBBBBDEEEEEEEEEEEB8889EFFFFFF
FFFFFFFB9999BBBBBBBBBBBBDEEEEEEEEEED9888BFFFFFFF
FFFFFFFEA9999ABBBBBBBBBBDEEEEEEEEEDA8889EFFFFFFF
FFFFFFFFD99989ABBBBBBBBBDEEEEEEEEDA8888DFFFFFFFF
FFFFFFFFFB99889ABBBBBBBBDEEEEEEEDA8888BFFFFFFFFF
FFFFFFFFFFB88889ABBBBBBBDEEEEEEB98888BFFFFFFFFFF
FFFFFFFFFFFB888889ABBBBBDEEEEDB98888AEFFFFFFFFFF
FFFFFFFFFFFFB888889ABBBBDEEEBA88888BFFFFFFFFFFFF
FFFFFFFFFFFFFB9888889ABBDEDA888889BFFFFFFFFFFFFF
FFFFFFFFFFFFFFD98888889BBB9888889DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEB88888889888888BEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFDA88888888889DFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEB98888889BEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEB9889BEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEAAEFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_NETWORKSECURITYGROUPCOLOR_G <img:../sprites/Cloud/Network_Security_Group_COLOR_gray.png>
!define MSIMG_NETWORKSECURITYGROUPCOLOR_M <img:../sprites/Cloud/Network_Security_Group_COLOR_mono.png>
!define MSIMG_NETWORKSECURITYGROUPCOLOR_C <img:../sprites/Cloud/Network_Security_Group_COLOR.png>
@enduml