@startuml
sprite $operationsmanagementsuiteomscolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFEDBBBBBBBEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFDBBAAAAAAAAABBEFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEBAAAAAAAAAAAAAABBEFFFFFFF
FFFFFFFFFFFFFFFFFFFFFBAAAAAAAAAAAAAAAAAABEFFFFFF
FFFFFFFFFFFFFFFFFFFEBAAAAAAAAAAAAAAAAAAAABDFFFFF
FFFFFFFFFFFFFFFFFFEBAAAAAAAAAAAAAAAAAAAAAAADFFFF
FFFFFFFFFFFFFFFFFFBAAAAAAAAAAAAAAAAAAAAAAAABEFFF
FFFFFFFFFFFFFFFFFDAAAAAAAAAAAAAAAAAAAAAAAAAABEFF
FFFFFFFFFFFFFFFFEBAAAAAAAAAAAAAAAAAAAAAAAAAAABFF
FFFFFFFFFFFFFFFFBAAAAAAAAAAAAAAAAAAAAAAAAAAAABEF
FFFFFFFFFFFFFFFEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABF
FFFFFFFFFFFFFFFDAAAAAAAAAAAAAAAAAAA7669AAAAAAABF
FFFFFFFFFFFFFFFBAAAAAAAAAAAAAAAAAAA4448AAAAAAAAE
FFFFFFFFFFFFFFEBAAAAAAAAAAAAAAAAAAA4448AAAAAAAAB
FFFFFFFFFFFFFFEAAAAAAA8778AAAAAAAAA4448AAAAAAAAB
FFFFFFFFFFFFFFEAAAAAAA6446AAAAAAAAA4448AAAAAAAAB
FFFFFFFEFEBBBFDAAAAAAA7446AAAAAAAAA4448AAAAAAAAB
FFFFFFDBFEBBBFDAAAAAAA7446AA9778AAA4448AAAAAAAAB
FFFFFBBBFEBBBFDAAAAAAA7446AA8444AAA4448AAAAAAAAB
FFFFFEEEFFEEEFDAAAAAAA7446AA8444AAA4448AAAAAAAAB
FFFFFFEFFFFFFFDAAAAAAA7446AA8444AAA4448AAAAAAAAD
FFBEFBBBFFFFFFDAAAAAAA7446AA8444AAA4448AAAAAAABE
FDBEFBBBFFFFFFDAAAAAAA7446AA8444AAA4448AAAAAAABF
EBBEFBBBFFFFFFDAAAAAAA7447AA8446AAA6448AAAAAAADF
FFFFFFFFFFFFFFDAAAAAAAA99AAAA99AAAAA99AAAAAAABFF
EEEFFEEEFFEEEFDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFF
BBBEFBBBFEBBBFDAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFFF
BBBEFBBBFEBBBFDAAAAAAAAAAAAAAAAAAAAAAAAAAAABFFFF
BBBEFBBBFEBBDFDAAAAAAAAAAAAAAAAAAAAAAAAAAABEFFFF
FFFFFFFFFFFFFFDAAAAAAAAAAAAAAAAAAAAAAAAAABEFFFFF
DDDFFFFFFEDDEFDAAAAAAAAAAAAAAAAAAAAAAAABBFFFFFFF
BBBEFFFFFEBBBFDAAAAAAAAAAAAAAAAAAAAAAABEFFFFFFFF
BBBEFFFFFEBBBFDAAAAAAAAAAAAAAAAAAABBDEFFFFFFFFFF
DDDFFFFFFEDDEFEDDDDDDDDDDDDDDDDDDEEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
BBBEFBBBFEBBDFEBBEFFFFFFBBBFEBBDFFFFFFFFFFFFFFFF
BBBEFBBBFEBBBFDBBDFFFFFFBBBEEBBBFFFFFFFFFFFFFFFF
BBBEFBBBFEBBBFDBBDFFFFFFBBBEEBBBFFFFFFFFFFFFFFFF
EEEFFEEEFFEEEFEEEEFFFFFFEEEFFEEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFBBBFEBBBFDBBDFDBBEFBBBEEBBEFFFFFFFFFFFFFFFF
FFFFFBBBFEBBBFDBBDFBBBEFBBBEEBDFFFFFFFFFFFFFFFFF
FFFFFBBBFEBBBFDBBDFDBBEFBBBEEBFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFEEEFFEEEFFFFFFEEEFFEEEFFFFFFFFFFFFFFFFFFFFF
FFFFFBBBFEBBBFFFFFFBBBEFBBBFFFFFFFFFFFFFFFFFFFFF
FFFFFFDBFEBBBFFFFFFBBBEFBDFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFEFEBBBFFFFFFBBBEFEFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_OPERATIONSMANAGEMENTSUITEOMSCOLOR_G <img:../sprites/Cloud/Operations_Management_Suite_OMS_COLOR_gray.png>
!define MSIMG_OPERATIONSMANAGEMENTSUITEOMSCOLOR_M <img:../sprites/Cloud/Operations_Management_Suite_OMS_COLOR_mono.png>
!define MSIMG_OPERATIONSMANAGEMENTSUITEOMSCOLOR_C <img:../sprites/Cloud/Operations_Management_Suite_OMS_COLOR.png>
@enduml