@startuml
sprite $unidentifiedfeatureobjectcolor [48x48/16] {
FFFFFFFFFFFFFFFFFFFFEEDDEEFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFDBBBBBBBBEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBBBBBBBBBBBBEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFDBBBBBBBBBBBBBBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFDBBBBBBBBBBBBBBBBEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBDFFFFFFFFFFFFFFF
FFFFFFFFFFFFEBBBBBBBBBBBBBBBBBBBBFFFFFFEEDEEFFFF
FFFFFFFFFFFFDBBBBBBBBBBBBBBBBBBBBEFFFFDDEEEEDEFF
FFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBDFFFDDEFFFFEDEF
FFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBDFFEDDEEDEFFDDF
FFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBDFFDDDDDDEFFDDE
FFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBDFEDDDDDEFFEDDD
FFFFFFFFFFFFBBBBBB78BBBBBA7ABBBBBEFEDDDDDFFEDDDD
FFFFFFFFFFFFDBBBBB47BBBBB949BBBBBEFEDDDDEFEDDDDD
FFFFFFFFFFFFEBBBBB9ABBBBBA7BBBBBBFFFDDDDDEDDDDDE
FFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBEFFFDDDDEFEDDDDF
FFFFFFFFFFFFFEBB9889EEBEEB999ABBFFFEDDDDEFFDDDEF
FFFFFFFFFFFFFFBB9667AB7AB86669BEFFFFFFEDDDDDDFFF
FFFFFFFFFFFFFFEBB876444446668BBFFFFFFFFFEEEFFFFF
FFFFFFFFFFFFFEEBBB9644444479BBEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFDDEEBBBA988767ABBDEEDEFFFFFFFFFFFFFF
FFFFFFFFFFFFEBBDBBBBBBBBBBBBBDBBDFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEBBBBBBBBBBBBBBBBBDFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEBBBBBBBBBBBBBBBDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFEEFFEBBBBBBBBBBBBBDFEBFFFFFFFFFFFFFFF
FFFFFFFFFFFEBDFFEBBBBBBBBBBBBFEBDFFFFFFFFFFFFFFF
FFFFFFFFFFFFBBBEFDBBBBBBBBBBEDBBEFFFFFFFFFFFFFFF
FFFFFFFFFFFFEBBBDDBBBBBBBBBDBBBBFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBEFFFFFFFFFFFFFFFF
FFFFFFFFFFEBBAABBBBABBBBBABBBB99ABEFFFFFFFFFFFFF
FFFFFFFFFB988878ABB79BBBA7BBA878889BFFFFFFFFFFFF
FFFFFFFFB877777778966BBB849877777778BEFFFFFFFFFF
FFFFFFDAB9777777777449BA446777777779BABFFFFFFFFF
FFFFFBA9BEBA9877776446B8446777789ABEB9ABEFFFFFFF
FFFEBAAAABEEEEDBBBA878B9789BBBDEEEEBAAAAADFFFFFF
FFEAAAAAAAABBDEEEEEEEEEEEEEEEEEDBBAAAAAAAABFFFFF
FEAAAAAAAAA9AAABBBBDDDDDDDBBBBAAA9AAAAAAAAABFFFF
EBAAAAAAAAAAAAA9999AAAAAAA9999AAAAAAAAAAAAAADFFF
B9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFFF
EB99AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99AEFFF
FFD9899AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9988BFFFFF
FFFFB878999AAAAAAAAAAAAAAAAAAAAAAAA99877AEFFFFFF
FFFFFEB87778999AAAAAAAAAAAAAAA999887779DFFFFFFFF
FFFFFFFEB877777888899999999888777778ADFFFFFFFFFF
FFFFFFFFFFDA8777777777777777777779BEFFFFFFFFFFFF
FFFFFFFFFFFFEDB987777777777789ABEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDBBBBBBBDDEFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_UNIDENTIFIEDFEATUREOBJECTCOLOR_G <img:../sprites/Cloud/Unidentified_feature_object_COLOR_gray.png>
!define MSIMG_UNIDENTIFIEDFEATUREOBJECTCOLOR_M <img:../sprites/Cloud/Unidentified_feature_object_COLOR_mono.png>
!define MSIMG_UNIDENTIFIEDFEATUREOBJECTCOLOR_C <img:../sprites/Cloud/Unidentified_feature_object_COLOR.png>
@enduml