@startuml
sprite $systemcenteradminconsole [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFFFFFFF
A4444444444444444444444444444444444446EFFFFFFFFF
44444444444444444444444444444444444444AFFFFFFFFF
448DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB44AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE64AFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9BFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB6447BFFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8444444BFFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFA44444444DFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFE6444444447FFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFD4444444444EFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFB4444444444DFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFB4444444444DFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFD4444444446EFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFF7444444449FFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFD44444446EFFFFFF
449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB444446DFFFFFFF
44466666666666666666666666667BFEFFEA88BEFFFFFFFF
7444444444444444444444444447EEA67DFFFFFFD87BFFFF
E98888888888887444444446889ED644449BEEB944448EFF
FFFFFFFFFFFFFFF64444444AFFFE644444444444444446EF
FFFFFFFFFFFFFFF84444444BFFFA444444444444444444AF
FFFFFFFFFFFFFFF74444444BFFF74444444444444444446F
FFFFFFFFFFFFEEA444444446BFE44444444444444444444E
FFFFFFFFB7666444444444444DE44444444444444444444B
FFFFFFFF64444444444444444DB44444444444444444444A
FFFFFFFFB8888888888888889EB444444444444444444448
FFFFFFFFFFFFFFFFFFFFFFFFFFA444444444444444444447
FFFFFFFFFFFFFFFFFFFFFFFFFF9444444444444444444446
FFFFFFFFFFFFFFFFFFFFFFFFFFDBBBBBBBBBBBBBBBBBBBBB
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_SYSTEMCENTERADMINCONSOLE_G <img:../sprites/System_Center/System_Center_admin_console_gray.png>
!define MSIMG_SYSTEMCENTERADMINCONSOLE_M <img:../sprites/System_Center/System_Center_admin_console_mono.png>
!define MSIMG_SYSTEMCENTERADMINCONSOLE_C <img:../sprites/System_Center/System_Center_admin_console.png>
@enduml