@startuml
!ifdef MS_SPRITESPATH
!else
!define MS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-microsoft-icons/master/sprites
!endif

!includeurl MS_SPRITESPATH/Enterprise/activedirectoryfederationservicesproxy.puml
!includeurl MS_SPRITESPATH/Enterprise/ad_fs.puml
!includeurl MS_SPRITESPATH/Enterprise/android_phone.puml
!includeurl MS_SPRITESPATH/Enterprise/application_blank.puml
!includeurl MS_SPRITESPATH/Enterprise/application_server.puml
!includeurl MS_SPRITESPATH/Enterprise/app_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/azure_pack.puml
!includeurl MS_SPRITESPATH/Enterprise/backup_local.puml
!includeurl MS_SPRITESPATH/Enterprise/backup_online.puml
!includeurl MS_SPRITESPATH/Enterprise/certificate.puml
!includeurl MS_SPRITESPATH/Enterprise/client_application.puml
!includeurl MS_SPRITESPATH/Enterprise/cloud.puml
!includeurl MS_SPRITESPATH/Enterprise/cluster_server.puml
!includeurl MS_SPRITESPATH/Enterprise/code_file.puml
!includeurl MS_SPRITESPATH/Enterprise/connectors.puml
!includeurl MS_SPRITESPATH/Enterprise/database_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/database_server.puml
!includeurl MS_SPRITESPATH/Enterprise/database_synchronization.puml
!includeurl MS_SPRITESPATH/Enterprise/device.puml
!includeurl MS_SPRITESPATH/Enterprise/direct_access_feature.puml
!includeurl MS_SPRITESPATH/Enterprise/document.puml
!includeurl MS_SPRITESPATH/Enterprise/domain_controller.puml
!includeurl MS_SPRITESPATH/Enterprise/enterprise_building.puml
!includeurl MS_SPRITESPATH/Enterprise/file_general.puml
!includeurl MS_SPRITESPATH/Enterprise/filter.puml
!includeurl MS_SPRITESPATH/Enterprise/firewall.puml
!includeurl MS_SPRITESPATH/Enterprise/folder.puml
!includeurl MS_SPRITESPATH/Enterprise/gateway.puml
!includeurl MS_SPRITESPATH/Enterprise/generic_code.puml
!includeurl MS_SPRITESPATH/Enterprise/healthy.puml
!includeurl MS_SPRITESPATH/Enterprise/healthy_grey.puml
!includeurl MS_SPRITESPATH/Enterprise/health_monitoring.puml
!includeurl MS_SPRITESPATH/Enterprise/import_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/internet.puml
!includeurl MS_SPRITESPATH/Enterprise/internet_hollow.puml
!includeurl MS_SPRITESPATH/Enterprise/keyboard.puml
!includeurl MS_SPRITESPATH/Enterprise/key_permissions.puml
!includeurl MS_SPRITESPATH/Enterprise/laptop_computer.puml
!includeurl MS_SPRITESPATH/Enterprise/load_balancer_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/load_balancer_generic_white.puml
!includeurl MS_SPRITESPATH/Enterprise/load_testing.puml
!includeurl MS_SPRITESPATH/Enterprise/lock_protected.puml
!includeurl MS_SPRITESPATH/Enterprise/lock_unlocked_accessible.puml
!includeurl MS_SPRITESPATH/Enterprise/maintenance.puml
!includeurl MS_SPRITESPATH/Enterprise/management_console.puml
!includeurl MS_SPRITESPATH/Enterprise/message.puml
!includeurl MS_SPRITESPATH/Enterprise/monitor.puml
!includeurl MS_SPRITESPATH/Enterprise/monitor_running_apps.puml
!includeurl MS_SPRITESPATH/Enterprise/mouse.puml
!includeurl MS_SPRITESPATH/Enterprise/network_card.puml
!includeurl MS_SPRITESPATH/Enterprise/not_allowed.puml
!includeurl MS_SPRITESPATH/Enterprise/performance.puml
!includeurl MS_SPRITESPATH/Enterprise/performance_monitor.puml
!includeurl MS_SPRITESPATH/Enterprise/phone.puml
!includeurl MS_SPRITESPATH/Enterprise/plug_and_play.puml
!includeurl MS_SPRITESPATH/Enterprise/powershell_script_file.puml
!includeurl MS_SPRITESPATH/Enterprise/protocol_stack.puml
!includeurl MS_SPRITESPATH/Enterprise/queue_general.puml
!includeurl MS_SPRITESPATH/Enterprise/rms_connector.puml
!includeurl MS_SPRITESPATH/Enterprise/router.puml
!includeurl MS_SPRITESPATH/Enterprise/rpd_remoting_file.puml
!includeurl MS_SPRITESPATH/Enterprise/script_file.puml
!includeurl MS_SPRITESPATH/Enterprise/secure_virtual_machine.puml
!includeurl MS_SPRITESPATH/Enterprise/server_blade.puml
!includeurl MS_SPRITESPATH/Enterprise/server_directory.puml
!includeurl MS_SPRITESPATH/Enterprise/server_farm.puml
!includeurl MS_SPRITESPATH/Enterprise/server_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/server_rack.puml
!includeurl MS_SPRITESPATH/Enterprise/settings.puml
!includeurl MS_SPRITESPATH/Enterprise/shared_folder.puml
!includeurl MS_SPRITESPATH/Enterprise/smartcard.puml
!includeurl MS_SPRITESPATH/Enterprise/startup_task.puml
!includeurl MS_SPRITESPATH/Enterprise/storage.puml
!includeurl MS_SPRITESPATH/Enterprise/stored_procedures.puml
!includeurl MS_SPRITESPATH/Enterprise/table.puml
!includeurl MS_SPRITESPATH/Enterprise/tablet.puml
!includeurl MS_SPRITESPATH/Enterprise/tool.puml
!includeurl MS_SPRITESPATH/Enterprise/triggers.puml
!includeurl MS_SPRITESPATH/Enterprise/tunnel.puml
!includeurl MS_SPRITESPATH/Enterprise/udf_function.puml
!includeurl MS_SPRITESPATH/Enterprise/unhealthy.puml
!includeurl MS_SPRITESPATH/Enterprise/usb.puml
!includeurl MS_SPRITESPATH/Enterprise/user_enterprise.puml
!includeurl MS_SPRITESPATH/Enterprise/user_permissions.puml
!includeurl MS_SPRITESPATH/Enterprise/video.puml
!includeurl MS_SPRITESPATH/Enterprise/virtual_machine.puml
!includeurl MS_SPRITESPATH/Enterprise/web.puml
!includeurl MS_SPRITESPATH/Enterprise/website_generic.puml
!includeurl MS_SPRITESPATH/Enterprise/web_server.puml
!includeurl MS_SPRITESPATH/Enterprise/windows_server.puml
!includeurl MS_SPRITESPATH/Enterprise/wireless_connection.puml
!includeurl MS_SPRITESPATH/Enterprise/workstation_client.puml
!includeurl MS_SPRITESPATH/Enterprise/xml_web_service.puml
@enduml