@startuml
sprite $applicationblank [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF76666666666666666666666666666666666666666667FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64444444444444444444444444444444444444444446FF
FF64BEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEB46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE46FF
FF64BEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEB46FF
FF64444444444444444444444444444444444444444446FF
FF76666666666666666666666666666666666666666667FF
FFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_APPLICATIONBLANK_G <img:../sprites/Enterprise/Application_blank_gray.png>
!define MSIMG_APPLICATIONBLANK_M <img:../sprites/Enterprise/Application_blank_mono.png>
!define MSIMG_APPLICATIONBLANK_C <img:../sprites/Enterprise/Application_blank.png>
@enduml