@startuml
sprite $connectors [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEEDDEFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD964444468BEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB64444444444449EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE74444444444444446BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFD6444444444444444444BFFFFFFFFFFFFF
FFFFFFFFFFFFFB44444448BBDDB9644447EFFFFFFFFFFFFF
FFFFFFFFFFFFD4444449EFFFFFFFFB747EFFFFFFFFFFFFFF
FFFFFFFFFFFF744446DFFFFFFFFFFFEBEFFFFFFFFFFFFFFF
FFFFFFFFFFFA44446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFE64444DFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFF
FFFFFFFFFFB4444BFFFFFFFEEFFFFFFFFFFFFE7BFFFFFFFF
FFFFFFFFFF74446EFFFFFD8646AEFFFFFFFFFF647EFFFFFF
FFFFFFFFFE4444AFFFFFB4444446EFFFFFFFFE6444BFFFFF
FB766666664444DFFFFE444444444666666666444447EFFF
A4444444444444EFFFF94444444444444444444444444BFF
44444444444446FFFFF7444444444444444444444444448D
44444444444446FFFFF6444444444444444444444444444A
A4444444444444EFFFF844444444444444444444444447DF
FB766666664444DFFFFB444444444666666666444444AFFF
FFFFFFFFFE4444AFFFFF84444444BFFFFFFFFE64447DFFFF
FFFFFFFFFF74446FFFFFF944446BFFFFFFFFFF644AFFFFFF
FFFFFFFFFFB4444BFFFFFFEBBBEFFFFFFFFFFF67DFFFFFFF
FFFFFFFFFFE64444DFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFF
FFFFFFFFFFFA44446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFE744446DFFFFFFFFFFFFABFFFFFFFFFFFFFFF
FFFFFFFFFFFFD444444AEFFFFFFFFB744BFFFFFFFFFFFFFF
FFFFFFFFFFFFFB44444448BDDDBA744444BFFFFFFFFFFFFF
FFFFFFFFFFFFFFB64444444444444444449FFFFFFFFFFFFF
FFFFFFFFFFFFFFFE74444444444444444BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB64444444444449EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB964444467BEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEDDDEEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_CONNECTORS_G <img:../sprites/Enterprise/Connectors_gray.png>
!define MSIMG_CONNECTORS_M <img:../sprites/Enterprise/Connectors_mono.png>
!define MSIMG_CONNECTORS_C <img:../sprites/Enterprise/Connectors.png>
@enduml