@startuml
sprite $internethollow [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFB9778BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB669BB964BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFA4BFFFFFFB68FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFA4EFFFFFFFFE68FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD4EFFFFFFFFFFE4BFDBABDFFFFFFFFFF
FFFFFFFFFFFFFFFF6AFFFFFFFFFFFFB46478764AFFFFFFFF
FFFFFFFFFFFFFFFD4FFFFFFFFFFFFFF9BFFFFFD66EFFFFFF
FFFFFFFFFFFFFFFA8FFFFFFFFFFFFFFFFFFFFFFF86FFFFFF
FFFFFFFFFFFFFFF7BFFFFFFFFFFFFFFFFFFFFFFFF78FFFFF
FFFFFFFFFFFFDBB4BFFFFFFFFFFFFFFFFFFFFFFFFE4DFFFF
FFFFFFFFFFB46774DFFFFFFFFFFFFFFFFFFFFFFFFF98FFFF
FFFFFFFFF86DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6FFFF
FFFFFFEE86FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4EFFF
FFFFB6446EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6DFFF
FFE66BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6DFFF
FE69FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF67FFF
F78FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE76EF
B4EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF87F
79FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B
4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6
4EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD4
4EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE4
4EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE4
4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE4
97FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6
E4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6B
FB4EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF97F
FF94DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF86EF
FFFB46ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB947EFF
FFFFEB7666666666666666666666666666666666678DFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_INTERNETHOLLOW_G <img:../sprites/Enterprise/Internet_hollow_gray.png>
!define MSIMG_INTERNETHOLLOW_M <img:../sprites/Enterprise/Internet_hollow_mono.png>
!define MSIMG_INTERNETHOLLOW_C <img:../sprites/Enterprise/Internet_hollow.png>
@enduml