@startuml
sprite $laptopcomputer [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFE86666666666666666666666666666666666668EFFFF
FFFF8446444444444444444444444444444444444449FFFF
FFFE46EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED46FFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE47FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFE48FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66EFFF
FFFB4499999999999999999999999999999999999844DFFF
FFD644444444444444444444444444444444444444446EFF
FE64444444444444444444444444444444444444444447EF
E7444444444444444444BDDDDDD74444444444444444448E
7444444444444444444AFFFFFFFB44444444444444444448
744444444444444444446666666644444444444444444446
E8666666666666666666666666666666666666666666668E
FFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_LAPTOPCOMPUTER_G <img:../sprites/Enterprise/Laptop_computer_gray.png>
!define MSIMG_LAPTOPCOMPUTER_M <img:../sprites/Enterprise/Laptop_computer_mono.png>
!define MSIMG_LAPTOPCOMPUTER_C <img:../sprites/Enterprise/Laptop_computer.png>
@enduml