@startuml
sprite $loadbalancergenericwhite [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFB6448DFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB444446DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD44444446EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF944444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF844444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF944444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB44444444EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF9444444BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFE94446BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFB4446EFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB444446EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB44444446EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB4444444446EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB444664494446EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB4446E944BB4446EFFFFFFFFFFFFFFFF
FFFFFFFDEFFFFFFB4446EF944BFB4446EFFFFFFEDFFFFFFF
FFFFFFB46EFFFFB4446EFF944BFFB4446EFFFFE64BFFFFFF
FFFFFF844DFFFB4446EFFF944BFFFB4446EFFFD448FFFFFF
FFFFFF844DFFB4446EFFFF944BFFFFB4446EFFD448FFFFFF
FFFFFF844DFB4446EFFFFF944BFFFFFB4446EFD448FFFFFF
FFFFFF844DD4446EFFFFFF944BFFFFFFB4446ED448FFFFFF
FFFFFF84494446EFFFFFFF944BFFFFFFFB4446B448FFFFFF
FFFFFF8444446EFFFFFFFF944BFFFFFFFFB4444448FFFFFF
FFFFFF844446DFFFFFFFFF944BFFFFFFFFFB444448FFFFFF
FFFFFF84444466668DFFFF944BFFFFD86666444448FFFFFF
FFFFFF844444444449FFFF944BFFFF944444444448FFFFFF
FFFFFF94444444444BFFFF944BFFFFB44444444449FFFFFF
FFFFFFEEEEEEEEEEEFFFFF944BFFFFFEEEEEEEEEEEFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEBBFFF944BFFEBBFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF944BFF944BFE644DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB444BF944BE6444EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE9444B944B8444BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE94444444444BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE944444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFE9444444BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFE94444BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFE944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFE9BFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_LOADBALANCERGENERICWHITE_G <img:../sprites/Enterprise/Load_balancer_Generic_white_gray.png>
!define MSIMG_LOADBALANCERGENERICWHITE_M <img:../sprites/Enterprise/Load_balancer_Generic_white_mono.png>
!define MSIMG_LOADBALANCERGENERICWHITE_C <img:../sprites/Enterprise/Load_balancer_Generic_white.png>
@enduml