@startuml
sprite $loadbalancergeneric [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFB7448EFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB444446DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD44444447FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF944444444DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF844444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF944444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFB44444446EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF8444444BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFA4446BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFD4447EFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD444447EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFD44444447EFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFD4444444447EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD444774484447EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD4447E944BD4447EFFFFFFFFFFFFFFFF
FFFFFFFDEFFFFFFD4446EF944BFB4447EFFFFFFEDFFFFFFF
FFFFFFA46EFFFFD4446EFF944BFFB4447EFFFFE64AFFFFFF
FFFFFF844DFFFD4446EFFF944BFFFB4447EFFFD448FFFFFF
FFFFFF844DFFD4447EFFFF944BFFFFB4447EFFD448FFFFFF
FFFFFF844DFD4447EFFFFF944BFFFFFB4447EFD448FFFFFF
FFFFFF844DD4447EFFFFFF944BFFFFFFB4447ED448FFFFFF
FFFFFF844A4447EFFFFFFF944BFFFFFFFB4447B448FFFFFF
FFFFFF8444447EFFFFFFFF944BFFFFFFFFB4444448FFFFFF
FFFFFF844446EFFFFFFFFF944BFFFFFFFFFB444448FFFFFF
FFFFFF84444466667DFFFF944BFFFFD76666444448FFFFFF
FFFFFF844444444448FFFF944BFFFF944444444448FFFFFF
FFFFFF84444444444BFFFF944BFFFFB44444444448FFFFFF
FFFFFFEEEEEEEEEEEFFFFF944BFFFFFEEEEEEEEEEEFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEABFFF944BFFEABFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF944AFF944BFE744DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFA444AF944BE7444EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF9444A944A7444BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF94444444444BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF944444444BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF9444444BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF94444BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF8BFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_LOADBALANCERGENERIC_G <img:../sprites/Enterprise/Load_balancer_Generic_gray.png>
!define MSIMG_LOADBALANCERGENERIC_M <img:../sprites/Enterprise/Load_balancer_Generic_mono.png>
!define MSIMG_LOADBALANCERGENERIC_C <img:../sprites/Enterprise/Load_balancer_Generic.png>
@enduml