@startuml
sprite $monitorrunningapps [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFD7666666666666666666666666666666666A
FFFFFFFFFFFF944444444444444444444444444444444444
FFFFFFFFFFFF944444444444444444444444444444444444
FFFFFFFFFFFF9448DDDDDDDDDDDDDDDDDDDDDDDDDDDDB444
FFFFFFFFFFFF9449FFFFFFFFFFFFFFFFFFFFFFFFFFFFD444
FFFFFFFFFFFF944AFFFFFFFFFFFFFFFFFFFFFFFFFFFFD444
FFFFFFFFFFFFB9DFFFEFFFFFFFFFFFFBEFFFFFFFFFFFD444
FFFFFFFFFFFFFFDA766679BEFFFFFFE4AFFFFFFFFFFFD444
FFFFFFFFFFFFB74444444446AEFFFF846EFFFFFFFFFFD444
FFFFFFFFFFE944468ABB974446DFFB4B6AFFFFFFFFFFD444
FFFFFFFFFE7447BFFFFFFFD9444DE6AFA6EFFFBBFFFFD444
FFFFFFFFF8449FFFFFFFFFFFB644DBEFE6AFFB46EFFFD444
FFFFFFFFA44AFFFFFFFFFFFFFD647EFFFA6EB496BFFFD444
FFFFFFFE449FFFFFFFFFFFFFFFB44AFFFE674AF96EFFD444
FFFFFFF946EFFFFEDFFFFFFFF8D946EFFFA4AFFE44AFD444
FFFFFFE64AFFFFF94DFFFFFFB48D44BFFFEBFFFFDBDFD444
FFFFFFD44DFFFFD447FFFFFE648F749FFFFFFFFFFFFFD444
FFFFFFB46FFFFE6444AFFFF846EFA47FFFFFFFFFFFFFD444
FFFFFFA47FFFFA46944BFFB44BFFB46FFFFFFFFFFFFFD444
FFFFFF947FEEB44BF846EE647FFFB46EFFFFFFFFFFFFD444
FFFFFFA47D64448FFE648944DFFFB46FFFFFFFFFFFFFD444
FFFFFFB44E7446EFFFB4444AFFFF947FFFFFFFFFFFFFD444
FFFFFFD44BEDDEFFFFF9447FFFFE64AFBAAAAAAAAAAA8444
FFFFFFF748FFFFFFFFFE64DFFFFB44DD4444444444444444
FFFFFFFB44DFFFFFFFFFDAFFFFE747F94444444444444446
FFFFFFFE646EFFFFFFFFFFFFFF944BFB999999999999999D
FFFFFFFFB447EFFFFFFFFFFFFA449FFFFFFFFFFFFFFFFFFF
FFFFFFFFD4446DFFFFFFFFFE8447EFFFFFFFFFFFFFFFFFFF
FFFFFFD94444448DEFFFFDA6447EFFFFFFFFFFFFFFFFFFFF
FFFFFB4444DB6444677764444AFFFFFFFFFFFFFFFFFFFFFF
FFFFB44449FFEB6444444469DFFFFFFFFFFFFFFFFFFFFFFF
FFFB44444DFFFFFDBA99BDEFFFFFFFFFFFFFFFFFFFFFFFFF
FFB44444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FB44444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
B44444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
64444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
6444BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
D77BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_MONITORRUNNINGAPPS_G <img:../sprites/Enterprise/Monitor_running_apps_gray.png>
!define MSIMG_MONITORRUNNINGAPPS_M <img:../sprites/Enterprise/Monitor_running_apps_mono.png>
!define MSIMG_MONITORRUNNINGAPPS_C <img:../sprites/Enterprise/Monitor_running_apps.png>
@enduml