@startuml
sprite $phone [48x48/16] {
FFFFFFFFFB6444444444444444444444444446AFFFFFFFFF
FFFFFFFFB444444444444444444444444444444BFFFFFFFF
FFFFFFFF7444444444BDBBBBBBBBDB6444444447FFFFFFFF
FFFFFFFF6444444444ABBBBBBBBBBB6444444446EFFFFFFF
FFFFFFFE64444444444444444444444444444446EFFFFFFF
FFFFFFFE64447777777777777777777777774446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE644AFFFFFFFFFFFFFFFFFFFFFFFFA446EFFFFFFF
FFFFFFFE6449EEEEEEEEEEEEEEEEEEEEEEEE9446EFFFFFFF
FFFFFFFE64444444444444444444444444444446EFFFFFFF
FFFFFFFE64444444444444444444444444444446EFFFFFFF
FFFFFFFE6444444444446BDDDDD9444444444446EFFFFFFF
FFFFFFFE6444444444449FFFFFFD444444444446EFFFFFFF
FFFFFFFF64444444444449AAAAA7444444444446EFFFFFFF
FFFFFFFF74444444444444444444444444444447FFFFFFFF
FFFFFFFFB444444444444444444444444444444BFFFFFFFF
FFFFFFFFFA4444444444444444444444444444AFFFFFFFFF
}

!define MSIMG_PHONE_G <img:../sprites/Enterprise/Phone_gray.png>
!define MSIMG_PHONE_M <img:../sprites/Enterprise/Phone_mono.png>
!define MSIMG_PHONE_C <img:../sprites/Enterprise/Phone.png>
@enduml