@startuml
sprite $queuegeneral [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFF
86777777777777777777777777777777777777777776EFFF
4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF98FFF
4ED87777777777AFA77777777777DE877777777779FE7BFF
4EB479999999846E648999999964AD469999999844EFB7EF
4EB46BFFFFFE746E648EFFFFFB44AD44BFFFFFE844EFF7AF
4EB684AFFFB6796E6866DFFF9496AB4948EFFD66A4EFFD6E
4EA6FB48EA49FB6E6BE84BE74BF7AB4EB67DB47ED4EFFF89
4EA6FFD644BFFB6E6BFFA447EFF7AB4EFE744AFFD4EFFFA6
4EA6FFFEADFFFB6E6BFFFBAEFFF7AB4EFFFABFFFD4EFFE6B
4EA6FFFFFFFFFB6E6BFFFFFFFFF7AB4EFFFFFFFFD4EFF98F
4EB4AAAAAAAAA76E67AAAAAAAAA4AD49AAAAAAAA84EFD6EF
4ED766666666669F966666666666BE766666666668EF7AFF
4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA7FFF
86888888888888888888888888888888888888888876DFFF
FBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_QUEUEGENERAL_G <img:../sprites/Enterprise/Queue_general_gray.png>
!define MSIMG_QUEUEGENERAL_M <img:../sprites/Enterprise/Queue_general_mono.png>
!define MSIMG_QUEUEGENERAL_C <img:../sprites/Enterprise/Queue_general.png>
@enduml