@startuml
sprite $rmsconnector [48x48/16] {
FFFFFFFFF84444444444444446DFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444448FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB447A99999999999447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB44BFFFFFFFFFFFE447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB446888888888887447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444447FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444444449FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB4444444444444448DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFB444444444444449FFDBBDFFFFFFFFFFFFFFFFFF
FFFFFFFFB44444444444446EF844447EFFFFFFFFFFFFFFFF
FFFFFFFFB4444444444444AF94AEEB48FFFFFFFFFFFFFFFF
FFFFFFFFB4444444444444DE48FFFFA4DFFFFFFFFFFFFFFF
FFFFFFFFB4444444444444DD4BFFFFE4BFFFFFFFFFFFFFFF
FFFFFFFFB4444444444444EB4DFFFFE4AFFFFFFFFFFFFFFF
FFFFFFFFB444444444446BFB4BEEEED49FFFFFFFFFFFFFFF
FFFFFFFFB44444444444AF944444444448FFFFFFFFFFFFFF
FFFFFFFFB44444444444BF744444444446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BF74444BB64446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BF74447FF94446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BF74444DE64446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BF74444AB44446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BF74444AB44446EFFFFFFFFFFFFF
FFFFFFFFB44ADDDDDDDDEF74444AB44446EFFFFFFFFFFFFF
FFFFFFFFB44BEEEEEEEEFF744446644446EFFFFFFFFFFFFF
FFFFFFFFB44444444444BFA66644446669FFFFFFFFFFFFFF
FFFFFFFFB44677777777BFFFFFB8AAFFFFFFFFFFFFFFFFFF
FFFFFFFFB44BFFFFFFFFFFFFFFB9ABFFFFFFFFFFFFFFFFFF
FFFFFFFFB448BBBBBFFFFFFFFB8777BFFFFFFFFFFFFFFFFF
FFFFFFFFB44444447FDAAAAA969AAA69AAAAADFFFFFFFFFF
FFFFFFFFB44444447FB4444446FFFF84444449FFFFFFFFFF
FFFFFFFFB44444447FB4444446EFFF84444449FFFFFFFFFF
FFFFFFFFEDDDDDDDEFEDDDDDB677777BDDDDDEFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFEDDDDEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_RMSCONNECTOR_G <img:../sprites/Enterprise/RMS_connector_gray.png>
!define MSIMG_RMSCONNECTOR_M <img:../sprites/Enterprise/RMS_connector_mono.png>
!define MSIMG_RMSCONNECTOR_C <img:../sprites/Enterprise/RMS_connector.png>
@enduml