@startuml
sprite $router [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEEEE
F9444446BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6444446
F8446999BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB9997444
F8444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7444
F84A44DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE74874
F84EB44DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE749F84
F84EFB44DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE749FF84
FB6EFFB44DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE749FFF87
FFBFFFFB6EFFFEEEEEEEEEEEEEEEEEEEEEEFFFFF88FFFFBE
FFFFFFFFEFFFB64444444444444444444448FFFFFFFFFFFF
FFFFFFFFFFFB4444444444444444444444448EFFFFFFFFFF
FFFFFFFFFFB444444444444444444444444448EFFFFFFFFF
FFFFFFFFFB44444444444444444444444444447EFFFFFFFF
FFFFFFFFA4444444444444444444444444444447EFFFFFFF
FFFFFFFA444444444444444444444444444444447EFFFFFF
FFFFFFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFF
FFFFFFE7444444444444444444444444444444446BFFFFFF
FFFFFFB44444444444444444444444444444444448FFFFFF
FFFFFFB44447744444467444444674444446744448FFFFFF
FFFFFFB4448FFA44448FFB44447EFB44447EFB4448FFFFFF
FFFFFFB444BFFD4444BFFE4444AFFE44449FFE4448FFFFFF
FFFFFFB4448EFA44447EFA44447EFB44446EFB4448FFFFFF
FFFFFFB44446644444466444444664444446644448FFFFFF
FFFFFFD44444444444444444444444444444444448FFFFFF
FFFFFFE8666666666666666666666666666666666DFFFFFF
FFFFFFFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDEFFFFFF
E9EFFF94BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE66EFFFAD
94EFF946EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF946EFF84
84EF946EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF946EF84
84D946EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF946D84
84747EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA4664
8446DFEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFE8444
84446668EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB6664444
B888888EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA888888
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_ROUTER_G <img:../sprites/Enterprise/Router_gray.png>
!define MSIMG_ROUTER_M <img:../sprites/Enterprise/Router_mono.png>
!define MSIMG_ROUTER_C <img:../sprites/Enterprise/Router.png>
@enduml