@startuml
sprite $tablet [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FD9999999999999999999999999999999999999999999ADF
B4444444444444444444444444444444444444444444444B
644444444444444444444444444444444444444444444446
444444444444444444444444444444444444444444444444
4446DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEED6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444
4446DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD6444
444444444444444444444666666444444444444444444444
64444444444444444444BEEEEEEB44444444444444444446
B44444444444444444448AAAAAA84444444444444444444B
FB98888888888888888888888888888888888888888889DF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_TABLET_G <img:../sprites/Enterprise/Tablet_gray.png>
!define MSIMG_TABLET_M <img:../sprites/Enterprise/Tablet_mono.png>
!define MSIMG_TABLET_C <img:../sprites/Enterprise/Tablet.png>
@enduml