@startuml
sprite $omsappwithchanges [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FA6666666666666666777777776AFFFFFFFFFFFFFFFFFFFF
E64444444444444444AD6BD6BB46FFFFFFFFFFFFFFFFFFFF
E64444444444444444BE6BE7DD46FFFFFFFFFFFFFFFFFFFF
E644444444444444446766767646FFFFFFFFFFFFFFFFFFFF
E64DEEEEEEEEEEEEEEEEEEEEED46FFFFFFFFFFFFFFFFFFFF
E64EFFFFFFFFFFFFFFFFFFFFFE68FFFFFFFFFFFFFFFFFFFF
E64EFFEDDDDDDDDDDDEFFEEEEDDDEEEEEEEEEEDEEDEDDEEF
E64EFE8777777777777D844444444444444446766747747F
E64EFFFFFFFFFFFFFFFF64444444444444444BF7BF7DE44E
E64EFFBBBBBBBBBBBBBE644444444444444449B69B7AB46E
E64EFE8888888888888D647777777777777778878878746E
E64EFFFFFFFFFFFFFFFF64EFFFFFFFFFFFFFFFFFFFFFE46E
E64EFEBBBBBFFFFFEFFF64EFFFEFFFFFFFFFFFFFFFFFE46E
E64EFE9999BFFFD7BFFF64EFFE6BFFFDAAAAAAAAABEFE46E
E64EFFFFFFFFEA448AAA449AA9448EFEA99999999AEFE46E
E64EFFFFFFFD644444444444444444BFFFFFFFFFFFFFE46E
E64EFFFFFFFD744444444444444446BFFFFFFFFFFFFFE46E
E64EFFFFFFFFFA448BBB44ABBA448EFE9888888889EFE46E
E64EFFFFFFFFFFD7BFFF64EFFE7BFFFDBBBBBBBBBBEFE46E
E64EFFFFFFFFFFFFFFFF64EFFFEFFFFFFFFFFFFFFFFFE46E
E64EFFFFFFFFFFFFFFFF64EFFFFFE7AFD777777778EFE46E
E647777777777777777D64EFFFFFD48FB444444444DFE46E
F744444444444444444B64EFFFFFFDEFEDDDDDDDDDFFE46E
FEDDDDDDDDDDDDDDDDEE64EFFFFFFFFFFFFFFFFFFFFFE46E
FFFFFFFFFFFFFFFFFFFF64EFFFFFE7777777777777EFE46E
FFFFFFFFFFFFFFFFFFFF64EFFFFFFEEEEEEEEEEEEEFFE46E
FFFFFFFFFFFFFFFFFFFF64EFFFFFFFFFFFFFFFFFFFFFE46E
FFFFFFFFFFFFFFFFFFFF64BEEEEEEEEEEEEEEEEEEEEED46E
FFFFFFFFFFFFFFFFFFFF644444444444444444444444446E
FFFFFFFFFFFFFFFFFFFFA66666666666666666666666669F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_OMSAPPWITHCHANGES_G <img:../sprites/OMS/OMS_App_with_changes_gray.png>
!define MSIMG_OMSAPPWITHCHANGES_M <img:../sprites/OMS/OMS_App_with_changes_mono.png>
!define MSIMG_OMSAPPWITHCHANGES_C <img:../sprites/OMS/OMS_App_with_changes.png>
@enduml