@startuml
sprite $xbox [48x48/16] {
00000000000000CABBBCCDDDDDDCCBBBAD00000000000000
000000000000BDBBCDDDDDDDDDDDDDDCBB9B000000000000
0000000000BDBCDDDDDDDDDDDDDDDDDDDDBB9B0000000000
0000000000BBCCCCDDDDDDDDDDDDDDDDCCCBCB0000000000
0000000000BBBBCBBBCDDDDDDDDDDCBBBC0BBB0000000000
0000000000000000DABBCDDDDDCBBBB00000000000000000
00000B7ABBCB0000000BCBCDCBB9C0000000C8BBB9B00000
0000B9BDDDCBAB0000000CDBBAC0000000DABBCDDB9C0000
000CABDDDDDDBCB000000000000000000B6BCDDDDDBAC000
000ABCDDDDDDDBBA0000000000000000BBBDDDDDDDCBA000
00BBCDDDDDDDDDCBAD0000000000000ABCDDDDDDDDDC0B00
0CABDDDDDDDDDDDCBA000000000000ABCDDDDDDDDDDDBAD0
0ABCDDDDDDDDDDDDCBA0000000000ABCDDDDDDDDDDDDCBA0
CABDDDDDDDDDDDDDDBA0000000000ABDDDDDDDDDDDDDDBAC
BBCDDDDDDDDDDDDDCBA0000000000ABCDDDDDDDDDDDDDCBB
ABDDDDDDDDDDDDDDBA00000000000DABDDDDDDDDDDDDDDBA
9CDDDDDDDDDDDDDBAB000000000000B9BDDDDDDDDDDDDDC9
BCDDDDDDDDDDDDCDB00000000000000BCCDDDDDDDDDDDDCB
BDDDDDDDDDDDDCBA00000DCCCC000000ABCDDDDDDDDDDDDB
BDDDDDDDDDDDDBAD0000BABCB0B00000BABDDDDDDDDDDDDB
CDDDDDDDDDDDB9B0000C9BDDDBBB00000BDCDDDDDDDDDDDC
CDDDDDDDDDDCBB0000B6BDDDDDCBA00000ABDDDDDDDDDDDC
CDDDDDDDDDDBAD000B8BDDDDDDDCAA0000CABDDDDDDDDDDC
CDDDDDDDDDB8B000B7BDDDDDDDDDCBB0000BBCDDDDDDDDDD
CDDDDDDDDCBA000B6BDDDDDDDDDDDCBA0000ABDDDDDDDDDD
CDDDDDDDDBAB00B9BDDDDDDDDDDDDDCBA000B6CDDDDDDDDC
CDDDDDDDCBB00BABDDDDDDDDDDDDDDDCBB000ABDDDDDDDDC
CDDDDDDDBAD0CABDDDDDDDDDDDDDDDDDCBB00B9BDDDDDDDC
BDDDDDDCBB0DABCDDDDDDDDDDDDDDDDDDBDB00ABDDDDDDDB
BDDDDDDBAD0ABCDDDDDDDDDDDDDDDDDDDDB9B0B9BDDDDDDB
BDDDDDCBB0BCCDDDDDDDDDDDDDDDDDDDDDDBAC0ABDDDDDDB
8CDDDDBACB9BDDDDDDDDDDDDDDDDDDDDDDDCBA0B8CDDDDC7
ABDDDDBA0ABDDDDDDDDDDDDDDDDDDDDDDDDDCBB0ABDDDDBA
ABCDDCDBBBCDDDDDDDDDDDDDDDDDDDDDDDDDDBACBBCDDDBA
BABDDBABABDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAB9CDDB9C
0ABDDBAABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDC5BABDDBA0
0BABDBAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBAABDB9B0
00ABCBABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC9ABCBB00
00DBBBABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBC00
000BBCABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBACCC000
000000ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBA000000
000000ABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBA000000
000000BCBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB9B000000
0000000BDBCDDDDDDDDDDDDDDDDDDDDDDDDDDCB9B0000000
00000000CABCDDDDDDDDDDDDDDDDDDDDDDDDCBAD00000000
0000000000BCBCDDDDDDDDDDDDDDDDDDDDCBDB0000000000
000000000000BBBBCDDDDDDDDDDDDDDCBBBB000000000000
00000000000000C7BBBCDDDDDDDCCBBB8C00000000000000
}

!define MSIMG_XBOX_G <img:../sprites/OtherMicrosoftProd/Xbox_gray.png>
!define MSIMG_XBOX_C <img:../sprites/OtherMicrosoftProd/Xbox.png>
@enduml