@startuml
sprite $companyportal [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFF
FF84444444444444444444444444444444444444444448FF
FB44444444444444444444444444444444477447744864BF
FA444444444444444444444444444444444DF64EE47FB49F
F94444444444444444444444444444444449A44A946B849F
F9444444444444444444444444444444444444444444449F
F9444444444444444444444444444444444444444444449F
F94AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA49F
F94BFFFEEFFFEEFFFEEFFFEEFFFEEFFFFFFFFFFFFFFFB49F
F94BFF946EFA46DFB46BFB46BFB44BFFFFFFFFFFFFFFB49F
F94BFF744EF844DFA44BFA44BFB44BFFFFFFFFFFFFFFB49F
F94BFFB89EFB89EFB88DFB88DFD88DFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F947AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA749F
F9444444444444444444444444444444444444444444449F
F948BAAAAAAAAB746AAAAAAAAAAAAAAAAAAAAAAAAAAB849F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFEEEEEEEFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BF7444446DFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFBBBBBBBEFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFEDDDDFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFB4444BFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFEDDDDFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFEBBBBEFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFB4446DFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFEEEEFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFBAAAAAAEFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BF7666666DFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
F94BFFFFFFFFFFB48FFFFFFFFFFFFFFFFFFFFFFFFFFFB49F
FB46888888888864488888888888888888888888888864BF
FF84444444444444444444444444444444444444444448FF
FFFDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_COMPANYPORTAL_G <img:../sprites/Intune/Company_portal_gray.png>
!define MSIMG_COMPANYPORTAL_M <img:../sprites/Intune/Company_portal_mono.png>
!define MSIMG_COMPANYPORTAL_C <img:../sprites/Intune/Company_portal.png>
@enduml