@startuml
sprite $conditionalaccessexchange [48x48/16] {
FFB444444444444444444444444444444446FFFFFFFFFFFF
FFB468888888888888888888888888888746FFFFFFFFFFFF
FFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFD66666666666666668FFFFFF76FFFFFFFFFFFF
FFB4DFFFFFD44444444444444448FFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFEEEEEEEEEEEEEEEEFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFEBBBBBBBBBBBBBBBBDFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFB44444444444444447FFFFFF76FFFFFFFFFFFF
FFB4DFFFFFEAAAAAAAAAAAAAAA9BFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFD66666666666666669FFFFFF76FFFFFFFFFFFF
FFB4DFFFFFD44444444444444448FFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFEEEEEEEEEEEEEEEEEFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76FFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFFFFFFFFEDBA9EFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFFEEDBA8766446DFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFFA664444444446DFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFF8444444444446DFFFFFFFFFFFF
FFB4DFFFFFFFFFFFFFFFFF84444444444448999999999EFF
FFB4DFFFFFFFFFFFFFFFFF8444444444444ABBBBBBBB7BFF
FFB4DFFFFFFFFFFFFFFFFF84444667644448BEFEAAAE9BFF
FFB4DFFFFFFFFFFFFFFFFF84448EEF9444487AE8776B9BFF
FFB4DFFFFFFFFFFFFFFFFF84448FBB74446DFE9AFE6B9BFF
FFB4DFFFFFFFFFFFFFFFFF84448F8444446DFBAFFE6B9BFF
FFB4DFFFFFFFFFFFFFFFFF84448FBA744449FDEDEB9F9BFF
FFB4BEEEEEEEEEEEEEEEFF84448FFFA44448AFFD8BFF9BFF
FFB44444444444444446EF84448F9764446DDEEED7AF9BFF
FFD77777777777777778EF84448F8644446DFDAFFD6D9BFF
FFFFFFFFFFFFFFFFFFFFFF84448FEEB4446DD8DDFE6B9BFF
FFFFFFFFFFFFFFFFFFFFFF84447BDEB444477BE7774B9BFF
FFFFFFFFFFFFFFFFFFFFFF84444446644448BFFDAAAE9BFF
FFFFFFFFFFFFFFFFFFFFFF8444444444444ABBBBBBBB7BFF
FFFFFFFFFFFFFFFFFFFFFF84444444444449AAAAAAAAAEFF
FFFFFFFFFFFFFFFFFFFFFF9644444444446DFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFEDBA87664446DFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDBA87EFFFFFFFFFFFF
}

!define MSIMG_CONDITIONALACCESSEXCHANGE_G <img:../sprites/Intune/Conditional_access_Exchange_gray.png>
!define MSIMG_CONDITIONALACCESSEXCHANGE_M <img:../sprites/Intune/Conditional_access_Exchange_mono.png>
!define MSIMG_CONDITIONALACCESSEXCHANGE_C <img:../sprites/Intune/Conditional_access_Exchange.png>
@enduml