@startuml
sprite $conditionalaccesssharepoint [48x48/16] {
FFF7444444444444444444444444444444447FFFFFFFFFFF
FFF6477777777777777777777777777777746FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFB7777777777777777AFFFFFF66FFFFFFFFFFF
FFF66FFFFFF944444444444444448FFFFFF66FFFFFFFFFFF
FFF66FFFFFFEDDDDDDDDDDDDDDDDEFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFEDDDDDDDDDDDDDDDDEFFFFFF66FFFFFFFFFFF
FFF66FFFFFF944444444444444448FFFFFF66FFFFFFFFFFF
FFF66FFFFFFB8888888888888888BFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFB8888888888888888BFFFFFF66FFFFFFFFFFF
FFF66FFFFFF944444444444444448FFFFFF66FFFFFFFFFFF
FFF66FFFFFFEBDDDDDDDDDDDDDDBEFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA9FFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEFFFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFFFFFEEBB98768FFFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFFDA97664444448FFFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFF7444444444448EEFFFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFF7444444444448A68EFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFF7444444444448944BFFFFFFFF
FFF66FFFFFFFFFFFFFFFFFF74444688644489448DFFFFFFF
FFF66FFFFFFFFFFFFFFFFFF74448EFF84448A6996BFFFFFF
FFF66FFFFFFFFFFFFFFFFFF7446ED7864448FEFFB7EFFFFF
FFF66FFFFFFFFFFFFFFFFFF7446ED6444448FFFFF87AEFFF
FFF66FFFFFFFFFFFFFFFFFF7444BFD744448FFFFF844AFFF
FFF66FFFFFFFFFFFFFFFFFF74446BFE74448FFFFE6447FFF
FFF649AAAAAAAAAAAAAABFF7444649FB4448FFFFF7449FFF
FFF744444444444444446FF7446B9AFA4448FFFFF879EFFF
FFFEDDDDDDDDDDDDDDDDEFF7446DFFD74448FFFFB7EFFFFF
FFFFFFFFFFFFFFFFFFFFFFF7444688644448B7AA6BFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF74444444444489447DFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF7444444444448944BFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF7444444444448947EFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF8644444444448EDEFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFEDBB987664448FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEBB979FFFFFFFFFFFF
}

!define MSIMG_CONDITIONALACCESSSHAREPOINT_G <img:../sprites/Intune/Conditional_access_Sharepoint_gray.png>
!define MSIMG_CONDITIONALACCESSSHAREPOINT_M <img:../sprites/Intune/Conditional_access_Sharepoint_mono.png>
!define MSIMG_CONDITIONALACCESSSHAREPOINT_C <img:../sprites/Intune/Conditional_access_Sharepoint.png>
@enduml