@startuml
sprite $deviceos [48x48/16] {
FFFFFFFFFA4444444444444444444444444444444444448E
FFFFFFFFD44444444444444444444444444444744664674A
FFFFFFFFB44444444444444444444444444447F94EB4BE48
FFFFFFFFB444444444444444444444444444449648747848
FFFFFFFFB444444444444444444444444444444444444448
FFFFFFFFB479999999999999999999999999999999999848
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FFFFFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
FB98889FB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
B444444EB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
8444444EB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
8444444EB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
8447778EB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE48
848FFFFFB4BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD48
848FFFFFE44666666666666666666666666666666666644B
848FFFFFFD888888888888888888888888888888888888BF
848FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFFB8BFFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
848FFFFFFFFFFFFFF948FFFFFFFFFFFFFFFFFFFFFFFFFFFF
847DDDDDDDDDDDDDD748FFFFFFFFFFFFFFFFFFFFFFFFFFFF
84444444444444444448FFFFFFFFFFFFFFFFFFFFFFFFFFFF
84444444466444444448FFFFFFFFFFFFFFFFFFFFFFFFFFFF
84444444DEED44444448FFFFFFFFFFFFFFFFFFFFFFFFFFFF
84444444EFFE44444448FFFFFFFFFFFFFFFFFFFFFFFFFFFF
84444444677644444448FFFFFFFFFFFFFFFFFFFFFFFFFFFF
A444444444444444444AFFFFFFFFFFFFFFFFFFFFFFFFFFFF
E844444444444444448EFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_DEVICEOS_G <img:../sprites/Intune/Device_OS_gray.png>
!define MSIMG_DEVICEOS_M <img:../sprites/Intune/Device_OS_mono.png>
!define MSIMG_DEVICEOS_C <img:../sprites/Intune/Device_OS.png>
@enduml