@startuml
sprite $devicehealth [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFF
E8644444444444444444444444444444444444444444448E
844444444444444444444444444444444444444444444447
444444444444444444444444444444444444444444444444
444BEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEA444
444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFAAFFFFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFB44BFFFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFF6446EFFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFB4444BFFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFF744447FFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFD444444BFFFFFFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFF8449B448FFFFFFFF96666666666BFB444
444DFFFFFFFFFFE444DE644DFFFFFFB44444444444AFB444
444DFFFFFFFFFFA448FFA449FFFFFE644444444444AFB444
444DFFFFFFFFFE644BFFE444EFFFFA446DEEEEEEEEEFB444
444DFFFFFFFFFB447FFFF944AFFFE444BFFFFFFFFFFFB444
444DFFFFFFFFF744BFFFFD446EFF9447FFFFFFFFFFFFB444
444DFE9999998446EFFFFF844BFD444BFFFFFFFFFFFFB444
444DFB444444444AFFFFFFD446E8448FFFFFFFFFFFFFB444
444DFB444444446EFFFFFFF7448444DFFFFFFFFFFFFFB444
444DFEBBBBBBBBEFFFFFFFFB444449FFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFFFFFFF64444EFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFFFFFFFB444AFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFFFFFFFE646EFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFFFFFFFFD9DFFFFFFFFFFFFFFFFB444
444DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB444
444ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB9444
44444444444444444444447BB74444444444444444444444
74444444444444444444447BB74444444444444444444447
E8444444444444444444444444444444444444444444448E
FFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_DEVICEHEALTH_G <img:../sprites/Intune/Device_health_gray.png>
!define MSIMG_DEVICEHEALTH_M <img:../sprites/Intune/Device_health_mono.png>
!define MSIMG_DEVICEHEALTH_C <img:../sprites/Intune/Device_health.png>
@enduml