@startuml
sprite $hybrid [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDEFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF846EFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF946DFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF944DFFFFFFFFFFFFF
A77777777777777777777777779EFF9444777777777BFFFF
444444444444444444444444444DFE6444444444444AFFFF
46DEEEEEEEEEEEEEEEEEEEEEE84DFFB446AAAAAAAAADFFFF
46FFFFFFFFFFFFFFFFFFFFFFF84DFFFB44BFFFFFFFFFFFFF
46FFFFFFFFFFFFFFFFFFFFFFF84DFFFFB44BFFFFBBEFFFFF
46FFFFFFFFFFFFFFFFFFFFFFF84DFFFFFB67DFFF946DFFFF
46FFFFFFFFFFFFFFFFFFFFFFFB9EFFFFFFFFFFFFF946DFFF
46FFFFFFFFFFFFFEBAAAAAAAABBABFFFFFFFFFFFFE846EFF
46FFFFFFFFFFFFFA4444444444444EFFE6666666664446EF
46FFFFFFFFFFFFFA49BBBBBBBBB64EFFD4444444444444BF
46FFFFFFFFFFFFFA4BFFFFFFFFF64EFFEBBBBBBBBB844AFF
46FFFFFFFFFFFFFA4BFFFFFFFFF64EFFFFFFFFFFFD44AFFF
46FFFFFFFFFFFFFA4BFFFFFFFFF64EFFB988BEFFB449FFFF
46FFFFFFFFFFFFFA4BFFFFFFFFF64EE8444446DE97AFFFFF
46FFFFFFFFFFFFFA4BFFFFFFFFF747648DEEA44DFFFFFFFF
46FFFFFFFFFFFFFA4BFFFFFFFFF74449FFFFFD47FFFFFFFF
449AAAAAAAAAAADA4BFFFFFFFFF64DDFFFFFFF94BFFFFFFF
44444444444444AA4BFFFFFFFFF64EFFFFFFFFD446BFFFFF
64444444444444AA4BFFFFFFFFF64EFFFFFFFFFBA647BEFF
EDDDDDDDDDDDDDEA4BFFFFFFFFF64EFFFFFFFFFFFE8646DF
FFFFFFFFFFFFFFFA4BFFFFFFFFF64EFFFFFFFFFFFFFEB46E
FFFFFFFFFFFFFFFA4BFFFFFFFFF64EFFFFFFFFFFFFFFFB49
FFFFFFFFFFFFFFFA4BFFFFFFFFF64EFFFFFFFFFFFFFFFE66
FFFFFFFFFFFFFFFA4BFFFFFFFFF64EFFFFFFFFFFFFFFFF74
FFFFFFFFFFFFFFFA49BBBBBBBBB64EFFFFFFFFFFFFFFFF64
FFFFFFFFFFFFFFFA4444444444444EFFFFFFFFFFFFFFFB48
FFFFFFFFFFFFFFFA44444AA744444EFFFFFFFFFFFFFFD64D
FFFFFFFFFFFFFFFA44444896444449AAAAAAAAAAAAA844BF
FFFFFFFFFFFFFFFB44444444444444444444444444446BFF
FFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDEFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_HYBRID_G <img:../sprites/Intune/Hybrid_gray.png>
!define MSIMG_HYBRID_M <img:../sprites/Intune/Hybrid_mono.png>
!define MSIMG_HYBRID_C <img:../sprites/Intune/Hybrid.png>
@enduml