@startuml
sprite $intuneemailprofiles [48x48/16] {
744444444444444444444444444444444446EFFFFFFFFFFF
646777777777777777777777777777777644EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFBAAAAAAAAAAAAAAAAAEFFFFFF74EFFFFFFFFFFF
64EFFFFFE444444444444444444BFFFFFF74EFFFFFFFFFFF
64EFFFFFFA99999999999999999EFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFA99999999999999999EFFFFFF74EFFFFFFFFFFF
64EFFFFFE444444444444444444BFFFFFF74EFFFFFFFFFFF
64EFFFFFFBBBBBBBBBBBBBBBBBBEFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFE877777777777777777DFFFFFF74EFFFFFFFFFFF
64EFFFFFE444444444444444444BFFFFFF74EFFFFFFFFFFF
64EFFFFFFDDDDDDDDDDDDDDDDDDEFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76EFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDFFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
64EFFFFFFFFFFFFFFFFFFB7666666666666666666666666A
64EFFFFFFFFFFFFFFFFFF844444444444444444444444446
64EFFFFFFFFFFFFFFFFFF846AAAAAAAAAAAAAAAAAAAAA646
64EFFFFFFFFFFFFFFFFFF847FFFFFFFFFFFFFFFFFFFFF946
64EFFFFFFFFFFFFFFFFFF844BFFFFFFFFFFFFFFFFFFFD646
64EFFFFFFFFFFFFFFFFFF84449EFFFFFFFFFFFFFFFEA4446
64EFFFFFFFFFFFFFFFFFF844446DFFFFFFFFFFFFFD744446
64EFFFFFFFFFFFFFFFFFF84694449EFFFFFFFFFEA4448746
64EFFFFFFFFFFFFFFFFFF847FB6447DFFFFFFFD7446BF946
64EFFFFFFFFFFFFFFFFFF847FFE8444AFFFFFA4448EFF946
64EFFFFFFFFFFFFFFFFFF847FFFFB6447DFD7446BFFFF946
64EFFFFFFFFFFFFFFFFFF847FFFFFE844484448EFFFFF946
64BEEEEEEEEEEEEEEDEFF847FFFFFFFB44446BFFFFFFF946
6444444444444444446EF847FFFFFFFFD748EFFFFFFFF946
A99999999999999999AFF847FFFFFFFFFFEFFFFFFFFFF946
FFFFFFFFFFFFFFFFFFFFF847FFFFFFFFFFFFFFFFFFFFF946
FFFFFFFFFFFFFFFFFFFFF847FFFFFFFFFFFFFFFFFFFFF946
FFFFFFFFFFFFFFFFFFFFF846BBBBBBBBBBBBBBBBBBBBB746
FFFFFFFFFFFFFFFFFFFFF844444444444444444444444446
FFFFFFFFFFFFFFFFFFFFFB4444444444444444444444444A
}

!define MSIMG_INTUNEEMAILPROFILES_G <img:../sprites/Intune/Intune_email_profiles_gray.png>
!define MSIMG_INTUNEEMAILPROFILES_M <img:../sprites/Intune/Intune_email_profiles_mono.png>
!define MSIMG_INTUNEEMAILPROFILES_C <img:../sprites/Intune/Intune_email_profiles.png>
@enduml