@startuml
sprite $microsoftintune [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FEBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFFFFFFFF
E744444444444444444444444444444444446EFFFFFFFFFF
D444444444444444444444444444444444444DFFFFFFFFFF
D447DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD844DFFFFFFFFFF
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFFD99BFFFFFFFFFFFFFB44DFFFFFFFFFF
D449FFFFFFFFFFFFB44449FFFFFFFFFFFFDABEFFFFFFFFFF
D449FFFFFFFFFFFE4444449AAAAAAAAAAAAAAAAAAAAAAADF
D449FFFFFFFFFFFB4444444444444444444444444444446E
D449FFFFFFFFFFFB4444444444444444444444444444444D
D449FFFFFFFFFFFE644444BDDDDDDDDDDDDDDDDDDDDDB44D
D449FFFFFFFFFFFFD6446BFFFFFFFFFFFFFFFFFFFFFFE44D
D449FFFFFFFFFFFFFEDDEFFFFFFFFFFFFFFFFFFFFFFFE44D
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44D
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE44D
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFE44D
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8AFFFFFE44D
D449FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF748EFFFE44D
D446AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4446DFFE44D
E44444444444444444444444444444444444444444BFE44D
F84444444444444444444444444444444444444447EFE44D
FFDDDDDDDDDDDDD94444448DDDDDDDDDDDDDD6449FFFE44D
FFFFFFFFFFFFFFFB4444449FFFFFFFFF97DFF74BFFFFE44D
FFFFFFFFFFFFFFF94444448FFFFFFFFF64BFFADFFFFFE44D
FFFFFFFFFFFFFFE64444444EFFFFFFFF64BFFFFFFFFFE44D
FFFFFFFFFFFEEB7444444446BEEFFFFF64BFFFFFFFFFE44D
FFFFFFFE7766444444444444446677DF64BFFFFFFFFFE44D
FFFFFFFD4444444444444444444444BF64BFFFFFFFFFE44D
FFFFFFFEBBBBBBBBBBBBBBBBBBBBBBEF64BFFFFFFFFFE44D
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF64BEEEEEEEEED44D
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF644444444444444D
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6444448BA444444D
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF744444466444446E
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAAAAAAAAAABDF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define MSIMG_MICROSOFTINTUNE_G <img:../sprites/Intune/Microsoft_Intune_gray.png>
!define MSIMG_MICROSOFTINTUNE_M <img:../sprites/Intune/Microsoft_Intune_mono.png>
!define MSIMG_MICROSOFTINTUNE_C <img:../sprites/Intune/Microsoft_Intune.png>
@enduml