@startuml
!define MS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-microsoft-icons/master/sprites
!includeurl MS_SPRITESPATH/Cloud/Accounts_Microsoft_account.puml
!includeurl MS_SPRITESPATH/Cloud/Accounts_Work_account.puml
!includeurl MS_SPRITESPATH/Cloud/Analysis_Service.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Acitve_Directory_Access_Control.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Active_Directory.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Active_Directory_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Active_Directory_Health_Monitoring.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Active_Directory_Health_monitoring_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Advisor.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_alert.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_API_Management.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_API_Management_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Application_Gateway.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Application_Gateway_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Application_Insights.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Application_Insights_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Azure_API_Apps.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Azure_API_Apps_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Mobile_App_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Mobile_App_was_Mobile_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Web_App_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Web_App_was_Websites.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Worker_Pools.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_App_Service_Worker_Pools_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Automation.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Automation_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Automation_Runbooks.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Automation_Runbooks_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Backup.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Backup_Backup_Agent.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Backup_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Backup_Recovery_Vault.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Batch.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_BizTalk_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_BizTalk_Services_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_BizTalk_Services_Hybrid_Connections.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_BizTalk_Services_Hybrid_Connections_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_BizTalk_Services_Hybrid_connection_manager.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cache_including_Redis.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cache_including_Redis_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cache_Redis_Product_icon_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Service.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Services_Web_role.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Services_Web_roles.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Services_Worker_role.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Services_Worker_roles.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cloud_Service_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_Computer_Vision_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_emotion_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_luis_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_recommendations_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_Speech_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_textanalytics_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognative_Services_web_language_model_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cognitive_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Compute_Autoscaling.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Container_Service.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Container_Service_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Content_Delivery_Network_CDN.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Content_Delivery_Network_CDN_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Cortona_Management_Suite.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Database_General_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DataServices_category_rollup.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Catalog.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Catalog_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Factory.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Factory_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Lake.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Lake_Analytics.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Lake_Analytics_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Lake_Store.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Lake_Store_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Warehouse.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Data_Warehouse_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DevTest_Labs.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DevTest_Labs_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DNS.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DNS_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB_database.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB_DocDB_account.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB_DocDB_collections_1.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_DocumentDB_document_2.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Event_Hubs.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Event_Hubs_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_ExpressRoute.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Express_Route_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Functions.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Functions_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_HDInsight.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_HDInsight_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_HockeyApp.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_HockeyApp_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_IoTHub_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_IoT_Hub.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_KeyVault_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Key_Vault.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_load_balancer_automatic.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Load_Balancer_feature.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Load_Balancer_feature_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Machine_Learning.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Machine_Learning_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Management_Portal.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Management_Portal_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Media_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Media_Services_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Mobile_Engagement.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Mobile_Engagement_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Multi_Factor_Authentication.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Multi_Factor_Authentication_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_MySQL_ClearDB_database.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_MySQL_ClearDB_database_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Notification_Hubs.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Notification_Hubs_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_RemoteApp.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_RemoteApp_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Rights_Management_RMS.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Scheduler.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SDK.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SDK_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Search.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Search_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Security_Center.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Security_Center_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_Queues.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_Queues_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_Relay.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_Topics.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Bus_Topics_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Fabric.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Service_Fabric_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Site_Recovery.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Site_Recovery_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Database.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Database_generic.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Database_generic_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Database_Premium.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_DataSync.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_DataWarehouse.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_DataWarehouse_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Stretch_Database.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_SQL_Stretch_Database_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Stack.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Storage.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Storage_Blob.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Storage_Files.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Storage_Queue.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Storage_Table.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Store.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Store_Marketplace.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Store_Marketplace_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_StorSimple.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_StorSimple_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Stream_Analytics.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Stream_Analytics_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_subscription.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Traffic_Manager.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Traffic_Manager_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machine.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machines_Availability_Set.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machines_Availability_Set_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machines_Linux_Penguin_shadow_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machine_2_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Machine_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Network.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_Virtual_Network_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VM_container.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VM_Scale_Set.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VM_Scale_Set_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VM_symbol_only.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VPN_Gateway.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_VPN_Gateway_color.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_WebApp_WebJobs.puml
!includeurl MS_SPRITESPATH/Cloud/Azure_WebApp_WebJobs_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Bot_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Cloud_Office_365.puml
!includeurl MS_SPRITESPATH/Cloud/Container_Service.puml
!includeurl MS_SPRITESPATH/Cloud/Logic_Apps.puml
!includeurl MS_SPRITESPATH/Cloud/Logic_Apps_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Microsoft_Azure.puml
!includeurl MS_SPRITESPATH/Cloud/Monitor.puml
!includeurl MS_SPRITESPATH/Cloud/Network_Security_Group.puml
!includeurl MS_SPRITESPATH/Cloud/Network_Security_Group_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/NewArt_NativeSize.puml
!includeurl MS_SPRITESPATH/Cloud/Office_365.puml
!includeurl MS_SPRITESPATH/Cloud/Office_365_subscription.puml
!includeurl MS_SPRITESPATH/Cloud/OMS_Log_Analytics.puml
!includeurl MS_SPRITESPATH/Cloud/Operations_Management_Suite_OMS.puml
!includeurl MS_SPRITESPATH/Cloud/Operations_Management_Suite_OMS_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/OS_image.puml
!includeurl MS_SPRITESPATH/Cloud/Power_BI_Embedded.puml
!includeurl MS_SPRITESPATH/Cloud/ResourceGroup_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Resource_Group.puml
!includeurl MS_SPRITESPATH/Cloud/Service_Bus.puml
!includeurl MS_SPRITESPATH/Cloud/Service_Endpoint.puml
!includeurl MS_SPRITESPATH/Cloud/SQL_Database_Pools.puml
!includeurl MS_SPRITESPATH/Cloud/SQL_Elastic_Pools.puml
!includeurl MS_SPRITESPATH/Cloud/Storage.puml
!includeurl MS_SPRITESPATH/Cloud/Unidentified_feature_object.puml
!includeurl MS_SPRITESPATH/Cloud/Unidentified_feature_object_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/VHD.puml
!includeurl MS_SPRITESPATH/Cloud/VHD_data_disk.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Bitbucket_code_source.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Bitbucket_code_source_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_CodePlex_source.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_CodePlex_source_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Dropbox_code_source.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Dropbox_code_source_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_GitHub.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_GitHub_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Git_repository.puml
!includeurl MS_SPRITESPATH/Cloud/Visual_Studio_Team_Services_Git_repository_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks_COLOR.puml
!includeurl MS_SPRITESPATH/Cloud/webhooks_mono.puml@enduml