@startuml
!include Enterprise/ActiveDirectoryFederationServicesProxy.puml
!include Enterprise/AD_FS.puml
!include Enterprise/Android_Phone.puml
!include Enterprise/Application_blank.puml
!include Enterprise/Application_server.puml
!include Enterprise/App_generic.puml
!include Enterprise/Azure_pack.puml
!include Enterprise/Backup_local.puml
!include Enterprise/Backup_online.puml
!include Enterprise/Certificate.puml
!include Enterprise/Client_application.puml
!include Enterprise/Cloud.puml
!include Enterprise/Cluster_server.puml
!include Enterprise/code_file.puml
!include Enterprise/Connectors.puml
!include Enterprise/Database_generic.puml
!include Enterprise/Database_server.puml
!include Enterprise/Database_synchronization.puml
!include Enterprise/Device.puml
!include Enterprise/Direct_Access_feature.puml
!include Enterprise/Document.puml
!include Enterprise/Domain_controller.puml
!include Enterprise/Enterprise_Building.puml
!include Enterprise/File_general.puml
!include Enterprise/Filter.puml
!include Enterprise/Firewall.puml
!include Enterprise/Folder.puml
!include Enterprise/Gateway.puml
!include Enterprise/Generic_code.puml
!include Enterprise/Healthy.puml
!include Enterprise/Healthy_grey.puml
!include Enterprise/Health_monitoring.puml
!include Enterprise/Import_generic.puml
!include Enterprise/Internet.puml
!include Enterprise/Internet_hollow.puml
!include Enterprise/Keyboard.puml
!include Enterprise/Key_permissions.puml
!include Enterprise/Laptop_computer.puml
!include Enterprise/Load_balancer_Generic.puml
!include Enterprise/Load_balancer_Generic_white.puml
!include Enterprise/Load_Testing.puml
!include Enterprise/Lock_protected.puml
!include Enterprise/lock_unlocked_accessible.puml
!include Enterprise/Maintenance.puml
!include Enterprise/Management_console.puml
!include Enterprise/Message.puml
!include Enterprise/Monitor.puml
!include Enterprise/Monitor_running_apps.puml
!include Enterprise/Mouse.puml
!include Enterprise/Network_card.puml
!include Enterprise/Not_allowed.puml
!include Enterprise/Performance.puml
!include Enterprise/Performance_monitor.puml
!include Enterprise/Phone.puml
!include Enterprise/Plug_and_play.puml
!include Enterprise/Powershell_script_file.puml
!include Enterprise/Protocol_stack.puml
!include Enterprise/Queue_general.puml
!include Enterprise/RMS_connector.puml
!include Enterprise/Router.puml
!include Enterprise/rpd_Remoting_file.puml
!include Enterprise/Script_file.puml
!include Enterprise/Secure_virtual_machine.puml
!include Enterprise/Server_blade.puml
!include Enterprise/Server_directory.puml
!include Enterprise/Server_farm.puml
!include Enterprise/Server_generic.puml
!include Enterprise/Server_rack.puml
!include Enterprise/Settings.puml
!include Enterprise/Shared_folder.puml
!include Enterprise/Smartcard.puml
!include Enterprise/Startup_task.puml
!include Enterprise/Storage.puml
!include Enterprise/stored_procedures.puml
!include Enterprise/Table.puml
!include Enterprise/Tablet.puml
!include Enterprise/Tool.puml
!include Enterprise/triggers.puml
!include Enterprise/Tunnel.puml
!include Enterprise/UDF_Function.puml
!include Enterprise/Unhealthy.puml
!include Enterprise/USB.puml
!include Enterprise/User_Enterprise.puml
!include Enterprise/User_permissions.puml
!include Enterprise/Video.puml
!include Enterprise/Virtual_Machine.puml
!include Enterprise/Web.puml
!include Enterprise/WebSite_generic.puml
!include Enterprise/Web_server.puml
!include Enterprise/Windows_Server.puml
!include Enterprise/Wireless_connection.puml
!include Enterprise/Workstation_client.puml
!include Enterprise/XML_web_service.puml
@enduml