@startuml
!define MS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-microsoft-icons/master/sprites
!includeurl MS_SPRITESPATH/Intune/Account_portal.puml
!includeurl MS_SPRITESPATH/Intune/Administration.puml
!includeurl MS_SPRITESPATH/Intune/Alerts.puml
!includeurl MS_SPRITESPATH/Intune/Apps.puml
!includeurl MS_SPRITESPATH/Intune/Certificate_compliance.puml
!includeurl MS_SPRITESPATH/Intune/Client_software_deployment_wizard.puml
!includeurl MS_SPRITESPATH/Intune/Company_portal.puml
!includeurl MS_SPRITESPATH/Intune/Computer_inventory.puml
!includeurl MS_SPRITESPATH/Intune/Conditional_access_Exchange.puml
!includeurl MS_SPRITESPATH/Intune/Conditional_access_Sharepoint.puml
!includeurl MS_SPRITESPATH/Intune/Connector.puml
!includeurl MS_SPRITESPATH/Intune/Dashboard.puml
!includeurl MS_SPRITESPATH/Intune/Data_migration_wizard.puml
!includeurl MS_SPRITESPATH/Intune/Detected_software.puml
!includeurl MS_SPRITESPATH/Intune/Device_group.puml
!includeurl MS_SPRITESPATH/Intune/Device_health.puml
!includeurl MS_SPRITESPATH/Intune/Device_history.puml
!includeurl MS_SPRITESPATH/Intune/Device_OS.puml
!includeurl MS_SPRITESPATH/Intune/End_protection.puml
!includeurl MS_SPRITESPATH/Intune/Exchange_connector.puml
!includeurl MS_SPRITESPATH/Intune/Groups.puml
!includeurl MS_SPRITESPATH/Intune/Hybrid.puml
!includeurl MS_SPRITESPATH/Intune/Intune_certificate_profiles.puml
!includeurl MS_SPRITESPATH/Intune/Intune_email_profiles.puml
!includeurl MS_SPRITESPATH/Intune/Intune_managed_app.puml
!includeurl MS_SPRITESPATH/Intune/Intune_mobile_application_management.puml
!includeurl MS_SPRITESPATH/Intune/Intune_VPN_profiles.puml
!includeurl MS_SPRITESPATH/Intune/Intune_Wi_Fi_profiles.puml
!includeurl MS_SPRITESPATH/Intune/Inventory_license.puml
!includeurl MS_SPRITESPATH/Intune/Inventory_software.puml
!includeurl MS_SPRITESPATH/Intune/License_group.puml
!includeurl MS_SPRITESPATH/Intune/License_installation.puml
!includeurl MS_SPRITESPATH/Intune/Microsoft_Intune.puml
!includeurl MS_SPRITESPATH/Intune/Mobile_inventory.puml
!includeurl MS_SPRITESPATH/Intune/Noncompliant_apps.puml
!includeurl MS_SPRITESPATH/Intune/Policy.puml
!includeurl MS_SPRITESPATH/Intune/Protection.puml
!includeurl MS_SPRITESPATH/Intune/Reports.puml
!includeurl MS_SPRITESPATH/Intune/Settings.puml
!includeurl MS_SPRITESPATH/Intune/Subscription_portal.puml
!includeurl MS_SPRITESPATH/Intune/Terms_and_conditions.puml
!includeurl MS_SPRITESPATH/Intune/Update.puml
!includeurl MS_SPRITESPATH/Intune/User_group.puml
!includeurl MS_SPRITESPATH/Intune/User_management.puml@enduml