@startuml
!include Intune/Account_portal.puml
!include Intune/Administration.puml
!include Intune/Alerts.puml
!include Intune/Apps.puml
!include Intune/Certificate_compliance.puml
!include Intune/Client_software_deployment_wizard.puml
!include Intune/Company_portal.puml
!include Intune/Computer_inventory.puml
!include Intune/Conditional_access_Exchange.puml
!include Intune/Conditional_access_Sharepoint.puml
!include Intune/Connector.puml
!include Intune/Dashboard.puml
!include Intune/Data_migration_wizard.puml
!include Intune/Detected_software.puml
!include Intune/Device_group.puml
!include Intune/Device_health.puml
!include Intune/Device_history.puml
!include Intune/Device_OS.puml
!include Intune/End_protection.puml
!include Intune/Exchange_connector.puml
!include Intune/Groups.puml
!include Intune/Hybrid.puml
!include Intune/Intune_certificate_profiles.puml
!include Intune/Intune_email_profiles.puml
!include Intune/Intune_managed_app.puml
!include Intune/Intune_mobile_application_management.puml
!include Intune/Intune_VPN_profiles.puml
!include Intune/Intune_Wi_Fi_profiles.puml
!include Intune/Inventory_license.puml
!include Intune/Inventory_software.puml
!include Intune/License_group.puml
!include Intune/License_installation.puml
!include Intune/Microsoft_Intune.puml
!include Intune/Mobile_inventory.puml
!include Intune/Noncompliant_apps.puml
!include Intune/Policy.puml
!include Intune/Protection.puml
!include Intune/Reports.puml
!include Intune/Settings.puml
!include Intune/Subscription_portal.puml
!include Intune/Terms_and_conditions.puml
!include Intune/Update.puml
!include Intune/User_group.puml
!include Intune/User_management.puml
@enduml