@startuml
!include OMS/OMS_alerts.puml
!include OMS/OMS_App_with_changes.puml
!include OMS/OMS_Assessments.puml
!include OMS/OMS_Capacity.puml
!include OMS/OMS_Config_Assessment.puml
!include OMS/OMS_Dashboard.puml
!include OMS/OMS_Dependency_Monitor.puml
!include OMS/OMS_Diagnostics.puml
!include OMS/OMS_Jobs.puml
!include OMS/OMS_Log_Management.puml
!include OMS/OMS_Log_Search.puml
!include OMS/OMS_Malware_Assessment.puml
!include OMS/OMS_Overview.puml
!include OMS/OMS_Security.puml
!include OMS/OMS_Server_with_changes.puml
!include OMS/OMS_Services.puml
!include OMS/OMS_Solutions.puml
!include OMS/OMS_System_update.puml
!include OMS/OMS_Track_Changes.puml
!include OMS/OMS_Wire_Data.puml
@enduml