@startuml
!include OtherMicrosoftProd/Access.puml
!include OtherMicrosoftProd/BI_Product.puml
!include OtherMicrosoftProd/Cortana_blue.puml
!include OtherMicrosoftProd/Cortana_blue_2.puml
!include OtherMicrosoftProd/Excel.puml
!include OtherMicrosoftProd/Exchange.puml
!include OtherMicrosoftProd/Exel.puml
!include OtherMicrosoftProd/Lync.puml
!include OtherMicrosoftProd/Microsoft.puml
!include OtherMicrosoftProd/Outlook.puml
!include OtherMicrosoftProd/PowerApps.puml
!include OtherMicrosoftProd/PowerPoint.puml
!include OtherMicrosoftProd/Sharepoint.puml
!include OtherMicrosoftProd/Skype.puml
!include OtherMicrosoftProd/Visio.puml
!include OtherMicrosoftProd/Windows.puml
!include OtherMicrosoftProd/Word.puml
!include OtherMicrosoftProd/Xbox.puml
!include OtherMicrosoftProd/XBox_One.puml
@enduml